[개인 미션 - 성능 오답노트] 세인(이세민) 미션 제출합니다.
woowacourse/perf-basecamp pull request #101
Opened 2023-09-07 04:29 UTC by semnil5202

Look So Good~~ 리뷰 잘 부탁드립니다! 🫡

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://d6oi44f66mhrh.cloudfront.net/
- 개선 전후 성능 측정 결과 
  - **개선 전 (GitHub Pages) : [WebPageTest](https://www.webpagetest.org/result/230907_AiDc7S_106/)**
<img width="1427" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/5c28f7a6-03f2-4a4b-825f-5bf157e67b2a">
  
<img width="1470" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/15a469b1-5073-4d7c-a805-3b13b3de0afb">

  - **개선 후 (CloudFront) : [WebPageTest](https://www.webpagetest.org/result/230907_AiDc7S_106/)**
<img width="1403" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/9012b6b1-23ac-4d09-8075-516f814b5bc3">

<img width="1470" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/a2f194ae-0b36-4ec4-8dfd-8e3174550186">

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
  <img width="765" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/89b284db-0a02-4bb8-9356-9bb53fa394eb">
  - 284KB -> 54.5KB 로 줄였습니다.
  - webpack 5 내장된 플러그인으로 압축 및 난독화 진행했습니다.
  - mini-css-extract-plugin 으로 css 파일을 병렬 다운로드하도록 진행했습니다.
  - css-minimizer-webpack-plugin 으로 css 파일을 압축했습니다.

- [x] 이미지 크기 줄이기
  <img width="855" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/89172499/3cc54aeb-cd7b-4037-bb9d-9bedeaa5fcba">
  - hero 이미지 10.7MB -> 118KB로 줄였습니다.
  - hero 이미지를 브라우저 사이즈에 맞게 데스크탑, 태블릿, 모바일 사이즈를 받아오도록 하였습니다.
  - gif 파일들을 webm 으로 변경하고 img 태그 대신 video 및 source 태그를 활용하였습니다. (KB 단위까지 줄였으며, 환경에따라 B 크기로 받아오기도 합니다.)

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
  - React.lazy 로딩을 통해 리소스 분리를 진행하였습니다.
- [x] 아이콘 패키지 Tree Shaking
  - "@babel/preset-env" 옵션에서 `"modules": false`를 지정하여 CommonJS로 모듈 시스템이 변경되는 것을 방지하였고, 이를 통해 트리쉐이킹이 정상적으로 진행될 수 있도록 하였습니다.

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
  - 캐시 정책의 경우 기본 값을 적용했습니다. 응답 헤더 max-age 1년으로 설정했습니다.
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
  - CacheStorage를 활용하여 캐싱을 진행하였습니다.

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - GifItem컴포넌트에 React.memo를 적용하였습니다.
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
  - CustomCursor 컴포넌트에서 top, left 스타일링 대신 transform: translate 사용
  - GifItem 컴포넌트에서 호버링 top 스타일링 대신 transform: translate 사용
  - Help Pannel 컴포넌트에서 rigth 스타일링 대신 transform: translate 사용
- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

* 폰트 최적화 : link 태그에서 font를 다운로드 받을 시 다운로드를 받는 동안 blocking 되는 현상이 있었습니다. 이는 미묘하지만 LCP 에 영향을 주었습니다. 따라서 프로젝트에서 사용하는 font만 사용하도록 하기위해 CSS 파일 내부에서 font-face 속성을 사용하여 지정하였고, 사용하지 않는 font 관련 태그는 모두 삭제했습니다.

2023-09-09 14:13 UTC, woo-jk requested changes
인세인~ 반갑습니다 ㅎㅎ 리뷰가 조금 늦어서 죄송합니다 ㅠ

단순히 요구사항만 맞춘게 아니라 그 이상으로 최적화하려고 노력하신 점이 눈에 띄었어요!

리뷰를 많이 드리고 싶었지만 전체적으로 되게 잘 되어있어서 생각보다 많이 드리지 못했습니다🥲
Search 페이지도 성능 측정 돌려보고, CPU 쓰로틀링도 걸어서 측정해봤는데.. 딱히 껀덕지가 안나오네요 ㅋㅋㅋ
그 대신 최적화 관련해서 궁금한 점이 많아서 그 부분들에 대해 코멘트 드렸으니 확인 부탁드려요~!

2023-09-11 06:25 UTC, semnil5202 commented on src/App.tsx
>  import Home from './pages/Home/Home';
보통 페이지를 접속하면 (거의 모든 경우에) 홈 페이지로 접속하므로 Search 페이지만 lazy loading을 적용하면 되지 않을까 해서 적용하지 않았습니다.

하지만 확인해보니 차이가 있더군요. 개발환경 기준으로 다음과 같습니다.

* main 번들 사이즈 :  532KB -> 514KB
* Home 번들 사이즈 : 0KB -> 17.9KB

홈 페이지로 접속했을 때 다운로드 받는 총량은 같지만, 브라우저는 평균 6개 파일을 병렬적으로 받아오는 사실을 감안해보면 Home 페이지 로딩을 더 빠르게 진행할 수 있을 것이라고 생각됩니다.

또한 Home 컴포넌트가 로딩이 완료될 때까지 `loading...` 이란 문구를 보여주어 사용자에게 명시적으로 페이지가 로딩되고 있음을 알려줄 수 있을 것 같아 페이지 이탈률을 줄일 수도 있겠군요. 🤔

덕분에 생각을 한 번 더 해볼 수 있었습니다. 좋은 리뷰 감사드립니다!

2023-09-11 06:25 UTC, semnil5202 commented on src/apis/gifAPIService.ts
> +    const responseCache = await cacheStorage.match(TRENDING_GIF_API);
가장 큰 차이점은 Promise 객체 반환 여부인 것 같습니다. 캐시스토리지는 `open()` 시 Promise 객체를 반환하기 때문에 코드를 동기적으로 실행하고자 한다면 `async await` 구문을 사용해주어야 합니다.

주 사용 사례는 네트워크 리소스를 임시로 저장하여 네트워크 요청 수를 줄이고, 로딩 속도를 높이는데 사용할 때입니다.

2023-09-11 06:25 UTC, semnil5202 commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(100vw);
아하 그렇네요. right 옵션을 아예 쓰지 않아야겠다 라고만 생각하다보니 위와 같은 코드가 되었던 것 같습니다. calc 연산자가 성능에 미치는 요인도 확인해볼 필요가 있겠군요. 🤔

수정해보겠습니다!

2023-09-11 06:25 UTC, semnil5202 commented on src/pages/Search/components/HelpPanel/HelpPanel.tsx
> +          <img src="https://giphy.com/static/img/artistdirectory_1040.gif" loading="lazy" />
img loading="lazy" 의 효과를 간략하게 정리하면 '당장 보여줄 필요가 없는 이미지는 나중에 때가 되면 받아오겠다.' 가 되겠습니다. 따라서 사용자가 스크롤 등의 동작을 하지 않으면 몇몇 이미지는 로딩을 아예 하지 않을 수도 있겠습니다.

이를 통해서 얻을 수 있는 장점은 다음과 같습니다.
* 페이지 로딩 속도 향상
* 서버 통신 비용 감소

몇몇 이미지에는 lazy 옵션을 달아주지 않은 이유는 페이지 접속 즉시 받아와야하는 이미지들이기 때문입니다. 사실 lazy 옵션을 달았다고 해서 필요한 이미지를 즉시에 받아오지 않는 것은 아니지만 미묘한 차이가 있을 것 같기에 (사용자의 뷰포트 위치와 스크롤 위치 연산 등) 위와 같이 진행했습니다.

2023-09-11 06:25 UTC, semnil5202 commented on webpack.config.js
> +    })
넵. gz 파일로 압축하면 약 40% 정도 효과가 있었던 걸로 기억합니다. 그런데 cloudfront에서도 설정할 수 있어서 굳이 해당 옵션을 쓰지 않아도 될 것 같습니다. 😃

2023-09-11 06:43 UTC, semnil5202 commented
안녕하세요 룩소~ 꼼꼼한 리뷰 감사드립니다~~ 덕분에 애매한 개념들을 다시 복습할 수 있었어요! 👍👍

피드백 주신 부분 반영했습니다. 추가로 ArtistInfo 컴포넌트에 memo 적용하여 불필요한 리렌더링을 방지하였고 development 모드에서는 webpack의 style-loader를 사용하도록 변경하였습니다.

[노센세 말씀에 의하면](https://github.com/woowacourse/perf-basecamp/pull/113#discussion_r1320779954) 개발모드에서 style-loader를 쓰는 것이 여러 이점이 있더군요.

리뷰 감사드립니다! 😀

2023-09-11 08:21 UTC, woo-jk approved these changes
궁금했던 점 답변해주셔서 감사합니다~! 덕분에 저도 많이 얻어갑니다 ㅎㅎ 고생하셨어요~~!!!

2023-09-11 08:21 UTC, merged