[개인 미션 - 성능 오답노트] 쵸파(유강현) 미션 제출합니다.
woowacourse/perf-basecamp pull request #106
Opened 2023-09-07 05:48 UTC by bassyu

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://dpofndulyum0.cloudfront.net/
- 개선 전후 성능 측정 결과
  - 개선 후 (CloudFront)
<img width="500" alt="스크린샷 2023-09-07 오후 1 09 06" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/13628526-fa06-4ab1-ba06-a3a73cdeb5ec">

## ✅ 개선 작업 목록

### **1 요청 크기 줄이기**

#### 소스코드 크기 줄이기

webpack의 옵션으로 난독화 하여 번들 크기를 줄였습니다.

```js
optimization: {
  minimize: true
}
```

#### 이미지 크기 줄이기

`resize` -> `compression` -> `.webp` 순서대로 이미지 크기를 줄였습니다.

<img width="353" alt="스크린샷 2023-09-07 오후 2 37 59" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/dca0861c-097c-4474-b96a-e84ec35a9b7b">

### **2 필요한 것만 요청하기**

#### 페이지별 리소스 분리

`dynamic import` + `React.lazy + Suspense` + `webpack` 의 조합으로 손쉽게 번들을 분리할 수 있었습니다!

| 전 | 후 |
|--------|--------|
| <img width="218" alt="스크린샷 2023-09-03 오후 3 51 37" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/f1bb08ff-569d-4270-8726-c4d7253566f8"> |   <img width="239" alt="스크린샷 2023-09-03 오후 3 59 29" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/a48a75a8-9861-473a-84e1-b7a16e062220"> | 

<img width="1904" alt="스크린샷 2023-09-03 오후 4 05 50" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/09b164ed-ef3e-4f9d-93a0-76e868cd23c3">

#### 아이콘 패키지 Tree Shaking

@react-icons/all-files 를 적용했습니다.

| 전 | 후 |
|--------|--------|
| <img width="561" alt="스크린샷 2023-09-02 오후 5 00 08" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/0cbca459-6597-4d2e-b3ef-b58bdb2b4a0f"> | <img width="567" alt="스크린샷 2023-09-02 오후 4 59 47" src="https://github.com/woowacourse/perf-basecamp/assets/54442420/d22ae57c-c4e0-4ee8-91e3-92c40697f865"> | 

### **3 같은 건 매번 새로 요청하지 않기**

#### CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)

캐시정책: https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=eu-north-1#/policies/cache/91d06267-2385-4dfa-9c34-d5ee648778b6

#### GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

### **4 최소한의 변경만 일으키기**

#### 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
#### Layout Shift 없이 애니메이션이 일어나야 한다.
#### Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

2023-09-07 09:52 UTC, feb-dain requested changes
안녕하세요 쵸파😄
전반적으로 성능 최적화를 잘 해주신 것 같습니다!
그리고 PR에 캐시 관련해서 자세한 설명이 되어있어 이해가 잘 되고 좋았습니다👍👍
마지막에 정리해주셔서 가독성도 좋았구요!
css 관련해서 minify한 건 없던데 일부러 안하신 건지 궁금합니다 😮

2023-09-07 09:52 UTC, feb-dain commented on src/App.tsx
> +      <Suspense fallback={<>loading</>}>
이렇게 fallback에 사이즈가 없는 로딩 컴포넌트를 넣으면 로딩 되었다가 다른 컴포넌트가 렌더링 되었을 때 Layout Shift가 발생하지 않나요??  😮
그리고 `NavBar`와 `Footer`는 빠르게 렌더링될텐데 다 같이 Suspense 안에 묶으신 이유가 있을까요?

2023-09-07 09:52 UTC, feb-dain commented on src/App.tsx
> +const Search = React.lazy(() => import('./pages/Search/Search'));
[질문] 저는 Search에만 lazy를 적용했는데 쵸파는 Home까지 적용하셨군요! 그 이유가 궁금합니다 😄

2023-09-07 09:52 UTC, feb-dain commented on src/apis/gifAPIService.ts
> +let trendings: GifImageModel[] | null = null;
[질문] 아예 전역 변수로 빼셨군요! 클로저 대신 이러한 방식을 사용한 이유가 궁금합니다. 이렇게 하면 장단점이 어떤 게 있을까요?

2023-09-07 09:52 UTC, feb-dain commented on src/pages/Search/components/GifItem/GifItem.module.css
> +  transform: translate(0, -0.75rem);
```suggestion
  transfrom: translateY(-0.75rem);
```

2023-09-07 09:52 UTC, feb-dain commented on webpack.config.js
> +    filename: '[name].[contenthash:8].js',
[질문] `contenthash`뒤에 8은 무엇을 의미하나요? 그리고 `chunkhash`를 사용하지 않은 이유도 궁금합니다!

2023-09-07 10:45 UTC, bassyu commented on src/App.tsx
> +const Search = React.lazy(() => import('./pages/Search/Search'));
Home 크기가 아주 크지 않으니 그 방법도 좋겠네요!
저는 url을 통해 Search 페이지에 먼저 접근한다면 Home 관련 리소스를 불러오고 싶지 않아서 분리했습니다~

2023-09-07 10:48 UTC, bassyu commented on src/App.tsx
> +      <Suspense fallback={<>loading</>}>
잠깐이지만 NavBar와 Footer가 먼저 그려지고 마저 그려지는 것보다,
준비가 되면 모두 한번에 보여주는 것을 선호해서 Suspense 안에 넣었습니다!

2023-09-07 10:50 UTC, bassyu commented on src/apis/gifAPIService.ts
> +let trendings: GifImageModel[] | null = null;
클로저로 만들 수도 있겠네요! trendings를 어디서든 참조할 수 있으니 오염되지 않도록 주의해야 하는게 단점인 것 같습니다.

2023-09-07 11:02 UTC, bassyu commented on webpack.config.js
> +    filename: '[name].[contenthash:8].js',
- 8을 주면 해시값을 8글자에서 자릅니다!

- chunkhash는 저도 궁금해서 찾아봤는데요!
하나의 엔트리 포인트에서 나온 파일들을 청크라고 부릅니다.
chunkhash는 청크를 기준으로 해시값을 주고, contenthash는 청크가 같더라도 각 파일의 내용을 기준으로 해시값을 줍니다.
같은 청크에도 .js와 .css가 분리되는 경우 contenthash를 사용하는 것 같습니다.
현재는 하나의 청크에 하나의 번들이 나와서 chunkhash를 사용해도 무방할 것 같아요!

2023-09-07 11:44 UTC, bassyu commented
빠르게 리뷰해주셔서 감사합니다!
코멘트 남겨주신 부분 적용해봤어요!

css minify는 지금 환경에서 큰 차이는 없어서 적용하지 않았습니다~

2023-09-07 11:45 UTC, bassyu commented
빠르게 리뷰해주셔서 감사합니다!
코멘트 남겨주신 부분 적용해봤어요!

css minify는 지금 환경에서 큰 차이는 없어서 적용하지 않았습니다~

2023-09-07 11:55 UTC, bassyu commented
빠르게 리뷰해주셔서 감사합니다!
코멘트 남겨주신 부분 적용해봤어요~

css minify는 적용해봤을 때에도 큰 차이가 없어서 포함하지 않았습니다!

2023-09-10 08:54 UTC, feb-dain commented on src/App.tsx
> +      <Suspense fallback={<>loading</>}>
아하 저는 NavBar가 먼저 렌더링 되는 것이 사용자 경험이 더 좋을 거라고 생각했어요! (바로 검색창으로 갈 수도 있으니까요)

2023-09-10 09:07 UTC, feb-dain approved these changes
피드백 반영한 것 모두 확인했습니다! 고생하셨어요👍🏻

저는 `MiniCssExtractPlugin`, `CssMinimizerPlugin` 2가지 플러그인을 사용해서 최적화를 진행했습니다! 초반에 적용하고 확인해서 그런지 유의미하게 사이즈가 줄어들더라구요. 
그리고 저는 조금이라도 속도가 빨라지거나 사이즈가 줄어들면 적용하는 편입니다! 적용 시간이 그렇게 오래 걸리지 않는다면요 ㅎㅎ

2023-09-10 09:14 UTC, merged