[개인 미션 - 성능 오답노트] 우스(김영길) 미션 제출합니다.
woowacourse/perf-basecamp pull request #107
Opened 2023-09-07 05:57 UTC by Gilpop8663

노아 안녕하세요 😀 기분좋은 하루 보내시길 바랄게요 화이팅!
프로젝트랑 미션을 같이 진행하니 어렵네요. 특히 성능 최적화에 대해서 무지한 상태로 시작해서 어렵다고 느꼈어요 😁

## 🔥 결과

### 개선 목표

• Desktop 기준

- [x] Lighthouse performance 95점 이상
- [x] Home 페이지에서 불러오는 스크립트 리소스 크기 < 60kb
- [x] 히어로 이미지 크기 < 120kb
- [x] 프랑스 파리에서 Fast 3G 환경으로 접속했을 때

  - [x] Home 첫 번째 로드시 LCP < 2.5s
  - [ ] Home 두 번째 이후 로드시 LCP < 1.2s => 실패

- [x] CPU 6x slowdown Network Fast 3G 환경에서
      화면 버벅임 최소화

  - Dropped Frame 없음.

  - Partially Presented Frame 최소화.

- 배포한 CloudFront 접근 경로: https://d2upyd0imvzhwr.cloudfront.net/

--------

- 개선 전후 성능 측정 결과

## 개선 전 (GitHub Pages)

## 개선 전 성능

### Network 탭 Fast 3g 설정에서의 성능

bundle.js 사이즈 : 285kB

hero.png: 10.7MB

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/8539bf99-8392-48b8-aefe-3744d6b629ae)

### 프랑스 파리에서 Fast 3G 환경으로 접속했을 때

https://www.webpagetest.org/result/230902_BiDcZ6_A4F/

#### 첫번째 Home 접속 시

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/7ab68828-e2b5-4bd1-b430-aace1b255a40)

페이지 불러오는 속도: 85.1초

First Contentful Paint: 2.8초

Largest Contentful Paint: 2.8초

Start Render: 2.8초

Page Weight: 15,582KB

#### 두번째 Home 접속 시

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/809d0bad-a18b-471d-9e52-0ef8292d73ab)

페이지 불러오는 속도: 84.8초

First Contentful Paint: 2.5초

Largest Contentful Paint: 2.5초

Start Render: 2.6초

Page Weight: 15,582KB

### LightHouse 점수

점수 : 75점

FCP 0.5초
LCP 9.2초

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/4fd147a1-9b97-4991-9d28-ce2b8d9c4842)

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/81f41ebf-5357-4694-8c6a-5a0d95c5cbbf)

### 퍼포먼스 탭 CPU 6x slowdown Network Fast 3G 환경

- Partially Presented Frame 이 많이 발생함

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/172520d7-54ac-45b9-8228-e554b38f45c0)

### 번들링되는 모듈

#### giphy 모듈이 포함되어 있음

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/312b99c1-9fdf-4ecf-8094-5ab7a14e4910)

#### react-icons 모듈의 크기: 628KB

![image](https://github.com/Gilpop8663/perf-basecamp/assets/80146176/df19e077-bea7-411a-bdc5-10bb7b6d3367)

--------

## 개선 후 (CloudFront)

#### bundle.js 사이즈 (홈)

- react.bundle.js: 42.1 kB
- 113.bundle.js: 11.4 kB
- main.bundle.js 13.1 kB

<img width="1064" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/becde4ed-0575-4222-84aa-9560f88adba1">

#### bundle.js 사이즈 (검색)

- 891.chunk.bundle.js: 13.6 kB
- search.chunk.bundle.js: 4.7 kB

<img width="1440" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/6ba5b50b-0207-47fa-b5b6-209d282ffa9d">

총 번들 사이즈: 84.9 kB

### Network 탭 Fast 3g 설정에서의 성능(작은 화면)

md-hero.avif: 44.7 kB

<img width="1064" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/becde4ed-0575-4222-84aa-9560f88adba1">

### Network 탭 Fast 3g 설정에서의 성능(큰 화면)

lg-hero.avif: 71.2 kB

<img width="1332" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/ef8359d1-fb07-49f1-8bfe-4361e1223198">

### 프랑스 파리에서 Fast 3G 환경으로 접속했을 때

https://www.webpagetest.org/result/230907_AiDc8F_45N/

#### 첫번째 Home 접속 시

<img width="1431" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/80146176/ac450dcb-bda5-4528-9124-54a04e39fa89">

페이지 불러오는 속도: 2.6초

First Contentful Paint: 1.6초

Largest Contentful Paint: 2.2초

Start Render: 1.6초

Page Weight: 941KB

#### 두번째 Home 접속 시

<img width="1440" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/80146176/3e4494f0-ea5c-4e8d-a423-e0ffbc8f5881">

페이지 불러오는 속도: 2.6초

First Contentful Paint: 1.6초

Largest Contentful Paint: 2.2초

Start Render: 1.6초

Page Weight: 941KB

### LightHouse 점수

점수 : 100점

FCP 0.5초
LCP 0.5초

<img width="1037" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/0475f047-f87d-42a6-a915-f43c3dc4879b">

<img width="1036" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/cca7cdec-2a4e-4c3c-ace1-53f9b43c8133">

<img width="1043" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/70aa0263-902a-4a0e-9073-5d3a9b417c98">

### 퍼포먼스 탭 CPU 6x slowdown Network Fast 3G 환경

#### 홈 화면

- Partially Presented Frame 발생하지 않음

<img width="1440" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/6a2f38ba-fe40-47ec-b267-86f2dfb20998">

#### 검색 화면

- Partially Presented Frame 발생하지 않음

<img width="1440" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/35d84b4b-3e3f-4989-a05b-d560037ef5d8">

<img width="1293" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/def04c4e-03bb-49fb-84ef-c1c2dc2b258e">

### 번들링되는 모듈

#### 홈에서 불러오는 스크립트에 giphy 모듈이 포함되어 있지 않음

<img width="1436" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/8da1293a-efbf-4d37-81be-89eafeef3fec">

#### 번들에 포함된 react-icons 모듈의 크기: 0KB

<img width="1440" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/4648f903-5e42-4f68-bfe5-2635fb08f8c2">

<img width="1437" alt="image" src="https://github.com/Gilpop8663/perf-basecamp/assets/80146176/2ac6bddb-ca60-45d1-8e22-6dd2066e0454">

------ 

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
    - 요청 크기를 줄이기 위해 코드 스플릿, 트리 쉐이킹을 통해 js 번들러의 용량을 줄이려고 했습니다

- [x] 이미지 크기 줄이기
    - 이미지 크기 줄이기는 squoosh를 사이트와 gif to mp4로 변환하는 사이트를 이용하여 이미지 용량을 줄였습니다 처음에는 webpack을 통해 동적으로 하려고 했지만 웹팩에 적용을 한다면 resize 옵션을 통해 크기가 작은 이미지도 크기를 크게 늘릴 것이 우려되어서 수동으로 변환해주었어요 그리고 이미지 확장자 같은 경우 avif, webp, jpeg를 사용하였고, 중간, 큰 사이즈의 이미지를 활용하였습니다.  picture 태그를 이용해서 avif => webp=> jpeg 순서로 지원하는 브라우저에 따라 다르게 설정했습니다. 그리고 화면 크기에 따라 중간, 큰 사이즈를 요청하도록 했어요

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
    - 페이지별 리소스를 분리하기 위해 리엑트의 lazy를 이용해서 다이나믹 임포트를 했습니다

- [x] 아이콘 패키지 Tree Shaking
    - 트리 쉐이킹 같은 경우는 production 모드로 빌드를 하게 되면 자동으로 적용된다고 하여 , package.json에 sideEffects에 css만 설정해주어 트리쉐이킹을 적용했습니다

**3 같은 건 매번 새로 요청하지 않기**

- [ ] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
    - 클라우드 프론트에서 캐시 설정은 따로 하지 않았지만, s3에서 캐싱을 할 수 있다고 하여 s3에서는 옵션을 설정해보았어요 하지만 제대로 적용이 안된건지 파리에서 테스트했던 결과에서는 첫번째, 두번째 결과가 똑같아서 제대로 설정이 되지 않았다고 생각해요
<img width="1440" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/80146176/f87f24ac-4858-4a13-a9f3-c9997ed3529b">
<img width="1069" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/80146176/8c24a7f7-1b4a-4f9f-be0c-3d20f4057fde">

- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
    -  fetch의 cache-control에서 max-age를 설정해보았지만 캐시가 되지 않아서, useContext와 cacheStorage를 고민했습니다.  cacheStorage는 한번 저장하면 삭제하기 전까진 계속 보관하는 것으로 이해해서 useContext가 더 적합해 보였지만, cacheStorage를 사용해보고 싶어서 사이트가 켜질때 저장된 cacheStorage를 삭제하도록 해서 구현했습니다

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
   -   gifItem에 React.memo를 적용했습니다

- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
    -   애니메이션의 CSS 코드 중 움직이는 부분을 transform: translate 속성을 이용해서 성능을 높이려고 했습니다

- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

무한 스크롤을 프로젝트에서도 하고 있는데 memo를 아이템에 적용해주면 기존 데이터는 리렌더가 일어나지 않을까요? 제가 한 것이 맞게 한지 모르겠어요 ㅠㅠ

2023-09-08 13:36 UTC, nlom0218 reviewed
안녕하세요 우스! 

프로젝트와 함께 개인 미션도 진행하시느라 고생많으셨어요! 👍

미션 목표와 함께 더불어 몇몇개의 리뷰 남겼으니 확인해주세요 :)

## WebPageTest

제가 실제로 우스가 배포한 사이트를 바탕으로 `webpagetest`를 해보았습니다. 결과는 다음과 같아요!

<img width="1476" alt="스크린샷 2023-09-08 오후 9 54 13" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/a6d0207e-49e9-4d72-9a8b-515340272bff">

사진을 보시면 Home 첫 번째 로드시 LCP, 두 번째 이후 로드시 LCP 모두 개선 목표에 도달한 것을 확인할 수 있어요! 또한 배포된 사이트의 네트워크를 살펴보면 `X-Cache`의 값이 Hit from cloudfront입니다. 이는 `cloudfront`에서 캐시된 값을 가져왔다고 해석하고 있는데요. 이렇듯 캐쉬 설정이 잘 되었다고 생각합니다 :)
우스도 다시 한 번 확인해보시겠어요?

<img width="938" alt="스크린샷 2023-09-08 오후 9 56 58" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/da72695e-0773-41e6-afc6-a0ede3de02c0">

## React.memo

크롬 개발자 도구에서 Profiler의 `profiling(녹화?기능)`을 사용하기 위해 `package.json`의 스크립트 - `serve`을 다음과 같이 변경했어요. 

```json
"serve": "webpack serve --mode=development",
```

기존에는 `development`을 설정하지 않아서 웹팩에서 설정한 `production`모드로 실행되었다고 생각합니다. 때문에 `profiling` 기능도 함께 사용하지 못했었고요! 

저는 `profiling` 기능을 잘 사용했는데 왜 우스 로컬에서는 안되는지 살펴보다가 차이점을 찾았어요!

아무튼..! 검색 후 짤을 더 불러왔을 때 `SerchResult` 컴포넌트는 다음과 같이 렌더링이 됩니다.

<img width="592" alt="스크린샷 2023-09-08 오후 10 13 37" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/3921074d-8a58-4bc2-bfd3-bbc9b94297e8">

살펴보시면 이전에 불러왔던 `GifItem`은 렌더링이 일어나지 않았다는 것을 확인할 수 있어요. 때문에 우스가 걱정했던

> 무한 스크롤을 프로젝트에서도 하고 있는데 memo를 아이템에 적용해주면 기존 데이터는 리렌더가 일어나지 않을까요? 제가 한 것이 맞게 한지 모르겠어요 ㅠㅠ

이 부분은 해결이 되었을 것이라 믿습니다!

2023-09-08 13:36 UTC, nlom0218 commented on package.json
> +  ],
`sideEffects`없이 빌드가 된다면 어떤 차이가 있을까요? 제가 해본 결과 `아이콘 패키지 Tree Shaking`에 대해서는 이전과 이후의 차이는 찾지 못했어요! 그 이유는 오늘 공원 수업때도 등장했으니 참고해주세요 :)

2023-09-08 13:36 UTC, nlom0218 commented on src/App.tsx
> +              </Search>
기존에 있던 구조에서 `HelpPanel` 컴포넌트를 `children`으로 뺀 이유가 있을까요?

2023-09-08 13:36 UTC, nlom0218 commented on src/App.tsx
>          <Route path="/" element={<Home />} />
저는 `Home` 컴포넌트도 `lazy`를 적용해주었는데요, 그 이유는 사용자가 `/search` 주소에 바로 접근을 할 수도 있다는 가정이 있었기 때문이에요! 우스는 어떻게 생각하시나요?

2023-09-08 13:36 UTC, nlom0218 commented on src/App.tsx
> +      await caches.delete('gifList');
`caches`... 멋집니다! 저는 클로저를 활용했는데 `CacheStorage`도 굉장히 흥미로워 보입니다 :)

2023-09-08 13:36 UTC, nlom0218 commented on src/apis/gifAPIService.ts
> +    const responseCache = await cacheStorage.match(TRENDING_GIF_API);
👍👍👍

2023-09-08 13:36 UTC, nlom0218 commented on src/pages/Home/components/CustomCursor/CustomCursor.module.css
> -  }
삭제된 css부분이 성능에 영향을 끼쳤나요? 궁금합니다!

2023-09-08 13:36 UTC, nlom0218 commented on src/pages/Search/components/HelpPanel/HelpPanel.tsx
> +          [styles.closeSheet]: !isShow
생각지도 못했던 방법이네요! 저는 어차피 `className`이 사라지게 된다면 해당 `className`의 css도 사라지게 될테니 `. showSheet`에서만 `right`을 `transform`으로 바꾸었어요

하지만 우스가 리팩터링한 코드를 보니 확실히 열리고 닫혔을 때, 어떻게 css가 바뀌는지 한 눈에 파악을 할 수 있네요! 👍

2023-09-08 13:36 UTC, nlom0218 commented on src/pages/Search/components/SearchBar/SearchBar.tsx
> +export default memo(SearchBar);
👍👍👍

2023-09-08 13:36 UTC, nlom0218 commented on webpack.config.js
> +  },
오! 이건 어떤 설정인지 간단하게 설명해주실 수 있을까요?

2023-09-08 13:43 UTC, nlom0218 requested changes
안녕하세요 우스!

프로젝트와 함께 개인 미션도 진행하시느라 고생많으셨어요! 👍

미션 목표와 함께 더불어 몇몇개의 리뷰 남겼으니 확인해주세요 :)

2023-09-11 06:21 UTC, Gilpop8663 commented
코드 리뷰 해주셔서 감사합니다 노아 

memo가 잘 작동하는 지 확인하기 위해서 profiling 설정하는 방법 알려주셔서 정말 감사합니다 😀

그리고 파리에서 잘 안되는 줄 알았는데 캐시되어서 그런거였나봐요 알아봐주셔서 감사합니다 👍

2023-09-11 08:19 UTC, nlom0218 commented on src/App.tsx
> +      await caches.delete('gifList');
오 감사합니다! 이번 프로젝트 때 필요했는데, 참고하여 적용해보겠습니다 :)

2023-09-11 08:20 UTC, nlom0218 approved these changes
우스! 고생많으셨습니다:)

남은 미션도 파이팅입니다! 😁

2023-09-11 08:21 UTC, merged