[개인 미션 - 성능 오답노트] 지니(손진영) 미션 제출합니다.
woowacourse/perf-basecamp pull request #116
Opened 2024-09-06 02:27 UTC by jinyoung234

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://d15rmgawdy85hf.cloudfront.net/
- 개선 전후 성능 측정 결과
  - 개선 전 (GitHub Pages)
    <div align="center">
    <img width="300" src="https://github.com/user-attachments/assets/b769676b-88bc-4be9-a887-334da9654ecb"/>
    <img width="300" src="https://github.com/user-attachments/assets/1e8719aa-627f-451c-93be-ffacdc6cee31"/>
    </div>

  - 개선 후 (CloudFront)
    <div align="center">
    <img width="300" src="https://github.com/user-attachments/assets/a045cab6-d882-482a-80a4-1a84dfe9a012"/>
    <img width="300" src="https://github.com/user-attachments/assets/618da3f9-de3e-4aad-98a9-7c55ea8d7114"/>
    </div>

각각 데스크톱, 모바일 입니다!

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기

    <div align="center">
    <img width="600" src="https://github.com/user-attachments/assets/7410f8e4-b5a3-4511-831f-0f022220626a"/>
    <img width="600" alt="image" src="https://github.com/user-attachments/assets/6e338106-7018-45d4-8e6c-db476090cdc4"/>
    </div>

각각 before after 입니다!

소스 코드를 줄이기 위해, `css/js minify, uglify` 키워드를 살펴볼 수 있었는데요!

### js minify, uglify

webpack 5부턴 terser-webpack-plugin을 통해 자동으로 minify 및 uglify를 지원하는데요!
production mode의 경우 해당 플러그인이 자동으로 들어가서 제가 추가적으로 설정할 건 없었습니다.

minimize 옵션이 false로 되어있어 true로 변경했습니다.

<div align="center">
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/842cbefc-99aa-4f56-8a4e-c850834c373d"/>
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/d90f3534-6cae-4a08-9dfb-28b80a7fd49d"/>
</div>

각각 before, after 입니다!

### js 내 css 파일 분리
![image](https://github.com/user-attachments/assets/801668e6-4947-47df-bdca-a73e62b7dfc2)

webpack bundle analyzer를 통해 번들 사이즈를 측정했을 때, 번들 파일 내 css 파일이 들어가 있는 것을 확인했습니다.

MiniCssExtractPlugin를 통해서 js 파일 내 있는 css 모듈을 css 파일로 분리하고, CssMinimizerPlugin를 통해 minify 하였습니다.

이 과정에서, style-loader가 충돌하기 때문에 의존성을 제거해주었습니다.

- [x] 이미지 크기 줄이기

ImageMinimizerWebpackPlugin를 통해 이미지를 최적화 할 수도 있지만, 해당 방향으론 진행하지 않았고 수동으로 이미지 리사이징 및 압축을 진행했습니다.

이미지 크기의 경우, webp 형식은 jpeg나 png 보다 25~30% 작으며, gif는 mp4나 webm으로 대체가 가능하다고 확인했습니다.

<div align="center">
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/f0176276-c135-4d50-a89c-e8caff527c60"/>
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/f26ede93-c861-4568-a5ec-da20e9a827d5"/>
</div>

hero.png - 10.7mb -> 84.5kb
trending.gif - 1.3mb -> 429b
find.gif - 2.0mb -> 429b
free.gif - 1.7mb -> 429b

개선 결과 다음과 같이 이미지 크기가 개선된 것을 확인할 수 있습니다.

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리

[코드 스플리팅 적용](https://github.com/woowacourse/perf-basecamp/commit/7935a0d0deb832b436d3fc1c376c5db55de0d611)을 통해 페이지별로 리소스를 분리해보려 했습니다.

<img width="266" alt="image" src="https://github.com/user-attachments/assets/52c9ac41-9049-427d-a625-8805ea37fcca">

빌드 결과 다음과 같이 분리되는 것을 확인할 수 있습니다. 다만, cloudfront로 페이지를 접근하면 bundle.js로 합쳐지는 것 같은데 정확한 원인은 모르겠네요,,,

- [x] 아이콘 패키지 Tree Shaking

<div align="center">
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/a990f535-c403-4a63-95ee-fe98c46101d9"/>
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/2feec710-5235-4fc7-91de-7830fd0497f5"/>
</div>

webpack bundle analyzer로 확인한 결과 react-icons/ai 모듈 전체를 사용하는 것을 확인할 수 있었습니다.

```tsx
// SearchBar.tsx
import { AiOutlineSearch } from '@react-icons/all-files/ai/AiOutlineSearch';

// HelpPanel.tsx
import { AiOutlineInfo } from '@react-icons/all-files/ai/AiOutlineInfo';
import { AiOutlineClose } from '@react-icons/all-files/ai/AiOutlineClose';
```

@react-icons을 지우고 @react-icons/all-files 의존성을 추가함으로써, 필요한 아이콘만 해당 파일에서 가져올 수 있었습니다.

<div align="center">
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/59f3f148-7dee-4f99-8be5-fdab2f504560"/>
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/c11910fb-3851-4fb9-a9f7-8730ee87655d"/>
</div>

다시 webpack bundle analyzer를 확인해보면 특정 아이콘만 import하는 것을 확인할 수 있으며 번들 사이즈도 2kb 정도 더 줄일 수 있었습니다.

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 / S3 메타데이터 설정 (설정값, 해당 값을 설정한 이유 포함)

![image](https://github.com/user-attachments/assets/d212e15f-3a0b-4035-943e-a77f48a1e66c)

cloudfront의 응답 헤더 캐시 정책을 추가하여 캐시 설정을 진행했습니다.

<div align="center">
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/9127a5ae-5cc9-4657-89c6-86715f513170"/>
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/8f64d9bd-dabf-4121-865f-153feb5a238a"/>
</div>

before의 경우 200으로 응답을 내려주지만 after의 경우 max-age가 아직 지나지 않았기 때문에 브라우저에서 서버에 요청을 보내지 않고 디스크 or 메모리 캐시에서 읽어오기 때문에 304를 내려주는 것을 확인할 수 있었습니다.

- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

해당 요구 사항의 경우 메모이제이션을 자체적으로 구현해 특정 시간 동안에 대해 들어온 요청은 캐싱된 데이터를 제공하고, 일정 시간이 지나면 다시 패칭 된 데이터를 제공해야겠다고 이해했습니다.

그래서 CacheStore라는 `캐싱`과 관련된 책임을 가지는 클래스를 만든 후, 다음과 같은 과정을 통해 메모이제이션을 구현했습니다.

1. 설정한 캐싱 타임이 지나지 않았는지 확인(현재 시간 - 캐시에 있는 타임 스탬프의 값이 캐싱 타임보다 작은지 확인)
2. 아직 지나지 않았다면 cache에서 데이터를 가져와 해당 데이터를 반환
3. 지났다면 callback 함수에서 데이터 패칭 후 해당 데이터를 cache에 저장(이 때, 데이터 및 타임스탬프를 함께 보관)
4. 데이터 반환

자세한 구현은 [feat(gifAPIService): trending api에 대한 캐싱 구현](https://github.com/woowacourse/perf-basecamp/commit/7cc7f74337b398c9cd9c91f271c2ace5a08a5969) 해당 커밋에서 확인할 수 있습니다!

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.

![image](https://github.com/user-attachments/assets/38196b11-539a-4f34-ba93-a5c06fb2ee80)

이 요구 사항의 경우 load more 버튼을 눌렀을 때 검색 결과에 있는 기존 GifItem이 렌더링 되지 않고 새로운 GifItem만 렌더링 되는 것으로 이해했습니다.

<div align="center">
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/439ae302-8730-4e89-80a1-5f57b3ea794d"/>
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/05289563-7816-4a99-b287-a0bbc8cf3c45"/>
</div>

react profiler를 통해 측정했고 기존 GifItem이 렌더링 되는 것을 확인할 수 있었습니다. 이를 개선하기 위해, React의 memo api를 생각하게 되었고, props에 변경 사항이 없다면 메모이제이션 된 GifItem을 그대로 반환해야겠다고 생각했습니다.

<div align="center">
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/af92aba1-4241-4384-9f9e-8f91cb5d0bb6"/>
  <img width="350" alt="image" src="https://github.com/user-attachments/assets/98fdb782-a097-4e4d-9de7-4090a6f47a8c"/>
</div>

다시 측정한 결과, 기존 GifItem이 memo 되어 다시 리렌더링이 발생하지 않으며 새로운 item만 렌더링 하는 것을 확인할 수 있습니다.

- [x] Layout Shift 없이 애니메이션이 일어나야 한다.

https://github.com/user-attachments/assets/854ae887-1fc6-4ffa-a1a0-6e50e226dfc1

![image](https://github.com/user-attachments/assets/284f6f53-448e-491d-9b26-ff7d2afde9a3)

대표적으로 CustomCursor를 움직일 때 layout shift가 발생했으며, 개발자도구의 performance 탭에서 확인할 수 있었습니다.

이 원인의 경우, position 프로퍼티가 reflow에 영향을 주기 때문이라고 확인할 수 있었고, 이를 개선하기 위해 transform 프로퍼티를 통해 개선해보고자 했습니다. ([feat: Layout shift 현상 개선](https://github.com/woowacourse/perf-basecamp/commit/466c6fdeefdd87fce83e46dd608f4e7afa715572) 참고)

![image](https://github.com/user-attachments/assets/ef30a0a3-d447-4e0a-a25a-f22c78675e9e)

다시 확인해보면 layout shift가 사라진 것을 확인할 수 있었습니다.

- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

Frame drop뿐 아니라 Partially Presented Frame도 개발자 도구 탭에서 따로 확인이 되지 않았기 때문에 따로 리팩터링을 진행하진 않았습니다.

## 🧐 공유

- https://devocean.sk.com/blog/techBoardDetail.do?ID=164863&boardType=techBlog
- https://www.youtube.com/watch?v=EP7g5R-7zwM
- https://developer.mozilla.org/ko/docs/Glossary/Code_splitting
- https://ui.toast.com/weekly-pick/ko_20200128
- https://velog.io/@sehyunny/the-definitive-guide-to-image-optimization
- https://toss.tech/article/smart-web-service-cache

참고했던 레퍼런스들 공유해봅니다!

2024-09-09 13:37 UTC, soi-ha reviewed
안녕하세요, 지니! 🧞
제가 지니의 리뷰어가 되다니.. 너무나도 영광입니다..>!🥹

지니의 PR을 읽으면서 제가 놓쳤던 부분들을 알게 되었어요! 정말 감사합니댜..👍
그리고 지니의 깔끔한 코드 너무 잘 봤어요~! 제가 남겨둔 대부분의 코멘트는 코드를 읽으며 생긴 궁금증이니 가벼운 마음으로 답변 남겨주세요 :)

2024-09-09 13:37 UTC, soi-ha commented on src/App.tsx
> +    <Router basename={'/'}>
단순 질문입니다만! basename을 지우지 않고 `'/'`로 남겨두신 이유가 있을까요?!

2024-09-09 13:37 UTC, soi-ha commented on src/App.tsx
> +const Loading = () => <div>Loading...</div>;
전 냅다 fallback에 작성했었는데, Loading까지 분리..👍👍

2024-09-09 13:37 UTC, soi-ha commented on src/utils/cache.ts
> +class CacheStore<T> {
와... Cache 저장을 위한 클래스를 직접 만드실 줄은...ㄷㄷ
코드 역시 깔끔해서 이해하는데 어려움이 전혀 없었어요! 대-지니.

단순히 궁금한 점은 CacheStore를 만드신 이유가 궁금해요! 저 같은 경우는 캐시 스토리지를 사용했거든요. 캐시 스토리지가 아니더라도 다른 스토리지를 활용할 수 있었을 것 같은데, 직접 구현하시게 된 이유가 궁금합니다!

2024-09-09 13:37 UTC, soi-ha commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +        <source src={imageSrc} type="video/webm" />
mp4와 webm 둘다 해주시다니.. 🫡 귀찮아했던 저를 반성합니다..

2024-09-09 13:37 UTC, soi-ha commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +        <source src={fallbackImageSrc} type="video/mp4" />
mp4가 fallbackImage인데 webm이 불가능한 브라우저일 경우 mp4로 대체하기 위함이 맞을까요??

2024-09-09 13:37 UTC, soi-ha commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" />
전 화끈하게 png는 버려줬는데, 지니는 png도 살려주셨군요..! 
맞아요.. 생각해보면 webp보다는 png로 된 이미지가 더 많을텐데.. 저도 png 무작정 버리는 건 고려해보긴 해야겠네요🤔

2024-09-09 13:37 UTC, soi-ha commented on src/pages/Home/Home.tsx
> +            sizes="(max-width: 500px) 500px, (max-width: 1000px) 1000px, 2000px"
srcSet에 width를 정해줌에도 sizes를 사용해주신 이유가 있을까요? 궁금해요!

2024-09-09 13:37 UTC, soi-ha commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(-320px) translateX(100vw);
`translateX(100vw)`도 해주신 이유가 궁금해요!

2024-09-09 13:37 UTC, soi-ha commented on src/types/images.d.ts
> +declare module '*.webp';
혹시 avif 확장자를 모르신다면 avif도 가볍게 찾아보시는 것을 추천드려요! webp보다 더 작고 이미지 품질도 좋다고 알고 있어요. 다만,, webp보다 범용성이 안 좋습니당... 
지식 공유차 말씀드려요!😊

2024-09-09 13:37 UTC, soi-ha commented on webpack.config.js
> +// const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
주석으로 남겨주신 이유가 있으실까용?

2024-09-09 13:48 UTC, soi-ha requested changes
지니! 프로젝트 진행하시면서 미션도 하시느라 고생 많으셨어요 :)
따로 수정할 부분은 없는데, 제가 궁금한 것들이 많아서.. 바로 approve하지 않고 RC했습니다! 그러니 코멘트에 대한 답만 시간 나실때 천천히 달아주세요ㅎㅎ

2024-09-10 07:46 UTC, jinyoung234 commented on src/App.tsx
> +    <Router basename={'/'}>
basename을 지워도 default가 '/'인 것을 처음 알게 되었습니다 ㅎㅎ!! 알려주셔서 감사해요 :)

2024-09-10 07:49 UTC, jinyoung234 commented on src/utils/cache.ts
> +class CacheStore<T> {
큰 이유는 없고, 이번 미션에서 api 캐싱을 처음 구현해보게 되었는데 직접 캐시를 구현해서 적용해보면 더 많은 학습이 될 거 같아 직접 캐시를 구현해 적용해보았습니다 :)

2024-09-10 07:50 UTC, jinyoung234 commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +        <source src={fallbackImageSrc} type="video/mp4" />
맞습니다! webm의 경우 지원되지 않는 브라우저들이 존재하기 때문에 이에 대응하기 위해 넣은거라고 이해해주시면 좋을거 같아요 ㅎㅎ

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/7ed7aee7-bdc7-4c9e-ab1a-fce0ed53a74f">

2024-09-10 07:59 UTC, jinyoung234 commented on src/pages/Home/Home.tsx
> +            sizes="(max-width: 500px) 500px, (max-width: 1000px) 1000px, 2000px"
전에 사용할땐 sizes 없었을때 문제가 되었던거 같았는데 다시 확인해보니 아무런 문제가 없네요! 확인 후 추가 커밋 남겨놓겠습니다 :)

2024-09-10 08:04 UTC, jinyoung234 commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(-320px) translateX(100vw);
100vw를 하지 않으면 요소가 이상한 곳으로 이동해버리더라구여,,, ㅜㅜ 원랜 translateX(100vw - 320px)로 했었는데 이것도 제대로 적용이 되지 않아 다음과 같은 코드를 구성하게 되었습니다. 혹시 다른 방법이 있을까요..?!

2024-09-10 08:06 UTC, jinyoung234 commented on src/types/images.d.ts
> +declare module '*.webp';
avif가 webp보다 더 압축률이 높다고 하네요!! 감사합니다 :)

2024-09-10 08:06 UTC, jinyoung234 commented on webpack.config.js
> +// const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
아 BundleAnalyzerPlugin 혹시 확인할 일이 있으실까 싶어 주석으로 남겨놨는데 코멘트를 따로 안드렸네요 ㅎㅎ..

2024-09-10 08:07 UTC, jinyoung234 commented
> 지니! 프로젝트 진행하시면서 미션도 하시느라 고생 많으셨어요 :) 따로 수정할 부분은 없는데, 제가 궁금한 것들이 많아서.. 바로 approve하지 않고 RC했습니다! 그러니 코멘트에 대한 답만 시간 나실때 천천히 달아주세요ㅎㅎ

안녕하세요 소하 :) 코멘트에 대한 답들 다 남겨놓았으니 시간 되실 때 한번 확인해보시면 좋을거 같습니다 !!

2024-09-11 00:50 UTC, soi-ha commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(-320px) translateX(100vw);
요소가 이상한 곳으로 이동한다는게 이해가 안됩니다..!
저는 단순하게 ` transform: translateX(-320px);`만 해줬어요~ 이 코드로 적용하면 HelpPanel을 열게 됐을 때, 정상적으로 우측에 붙어있어요!

2024-09-11 00:51 UTC, soi-ha commented on webpack.config.js
> +// const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
아항! 친절한 주석 감사합니댱 :)

2024-09-11 00:55 UTC, soi-ha approved these changes
안녕하세요, 지니! 
남겨주신 코멘트 잘 확인했습니다 :) HelpPanel에 대해 남긴 코멘트만 확인해주시면 될 것 같아요!
코멘트 확인 이외에는 수정할 부분은 없어서 일단 merge하겠습니다! 미션하시느라 고생 많으셨어요 지니~!

2024-09-11 00:56 UTC, merged