[개인 미션 - 성능 오답노트] 다르(이상엽) 미션 제출합니다.
woowacourse/perf-basecamp pull request #123
Opened 2024-09-07 12:52 UTC by pp449

## 🔥 결과

[배포한 CloudFront 접근 경로](https://do45yvz5viikt.cloudfront.net) 

<details>
  <summary>개선 전후 성능 측정 결과</summary>
  
---

### 개선 전 (GitHub Pages)
[github pages 링크](https://pp449.github.io/perf-basecamp/)

<img width="837" alt="ghpages 성능" src="https://github.com/user-attachments/assets/636f9a0d-c021-4b10-a3f7-e602e2efd37c">

### 개선 후 (CloudFront)

<img width="915" alt="cloudfront 개선 후 성능" src="https://github.com/user-attachments/assets/c82c12f7-bd90-4749-945d-a06649135b50">

<img width="1459" alt="프랑스 파리 접근 성능" src="https://github.com/user-attachments/assets/8febbf36-431c-43a9-a452-8a37acfd1bf2">

---
  
</details>

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] [소스코드 크기 줄이기](44a7d37a5b3c39c74ef6e7da41be19f0a87d1d59)
- webpack 에서 번들링 시 prod 환경이면 코드의 공백, 주석, 불필요한 문법 등을 제거하여 js 파일 크기 줄이기
- [x] [이미지 크기 줄이기](2b6db4b9537deb3e8f46bfcb9d03b25928fcc9bd)
- png 파일을 webp, gif 파일을 mp4 파일로 변환

**2 필요한 것만 요청하기**

- [x] [페이지별 리소스 분리](f6c03418822628977c6108cf97c9ae4f3e0f4599)
- search 페이지는 lazy 로딩으로 유저가 필요할 때 불러오도록 구성 (개인적으로 search 의 크기가 크지 않아 lazy loading 하는게 더 안좋은거 같네요 ㅎㅎ)
- [x] [아이콘 패키지 Tree Shaking](a7473b9dcc5329caad908e5262ff1cce6f22bb5b)
- `@react-icons/all-files` 라이브러리를 이용하여 필요한 아이콘만 가져오도록 구성

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 / S3 메타데이터 설정 (설정값, 해당 값을 설정한 이유 포함)
- Cloudfront를 `자동으로 객체 압축`을 허용하여 데이터 요청 시 인코딩이 가능하다면 압축하여 전송하도록 구성
- 응답헤더에 `Cache-Control: max-age=60` 에 추가하여 응답을 받은 1분동안 브라우저에서 캐싱하도록 구성 (1분으로 설정한 이유는 새로 배포된 경우에도 유저가 최신화된 정적 파일(html, js)을 가져올 수 없기에 짧은 시간으로 설정했어요!)
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
- [tanstack query 를 이용하여 서버의 응답을 모두 캐싱하여 이미 불러온 데이터는 다시 네트워크 요청을 하지 않도록 구성](62b6db7587dddcda67a723651acc264ef269bf03) (페이지를 사용하는 동안 한번 불러온 데이터를 최신화 할 필요가 없다 판단해여 staleTime, gcTime 을 Infinity로 설정해줬어요!)

**4 최소한의 변경만 일으키기**

- [x] [검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.](72635c07d73e3da00f0b7977f069d9a1145f8aaf)
- `GifItem` 컴포넌트를 React.memo 를 이용하여 메모이제이션 최적화 
- [x] [Layout Shift 없이 애니메이션이 일어나야 한다.](3a2209eda02c0ce3052a3054c53427b24ca5ccdf)
- top, left 등 위치 기반으로 애니메이셔닝을 모두 translate를 이용하여 처리하도록 변경
- [ ] Frame Drop이 일어나지 않아야 한다. (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.
- Frame Drop이 일어나지 않는거 같아 추가적으로 작업을 하지 않았어요.. ㅎㅎ 😅
## 🧐 공유

### [LCP 를 줄이기 위한 노력](127023ae95ef26594a859f6ae21b8b648ea4477c)
hero 이미지 파일이 가장 크기에 LCP에 영향을 끼친다 판단하여 hero 이미지가 필요할 때 요청을 하는게 아닌 html 파일이 처리될 때 미리 hero 파일을 가져오도록 했어요.

위에서 언급했듯이 Cloudfront 의 응답헤더를 이용하여 1분동안은 캐싱이 되기에 Home이 렌더링이 될 때 hero 이미지를 요청 시에는 캐싱된 이미지를 사용하기에 LCP 를 단축시킬 수 있었어요

<img width="835" alt="image" src="https://github.com/user-attachments/assets/e9408378-a338-40fa-997c-fd7fe8eac046">

해당 이미지와 같이 hero 이미지를 2번 요청을 보내는데 1번째는 초기에 불러오고 2번째에는 캐시에서 가져오는 것을 확인할 수 있어요.
(preload 옵션을 이용하여 js 파일을 실행하기 전에 해당 이미지 파일을 읽기에 html 파일이 파싱이 되고 js 파일이 실행되기 전 hero 이미지 로드까지 처리하기에 2번째는 캐시된 이미지를 사용함을 보장할 수 있어요)

### 🧑‍🔬 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더의 성능 측정
실제로 memo 를 이용했을 때 성능이 더 좋아졌는지 확인하기 위해 실험을 해봤어요. 

검색창에 `otter` 를 검색한 후 react dev tools 의 profile 을 활성화하고 모든 gif 이미지를 불러올때까지 더보기를 누른 후 profile 의 결과를 확인해봤어요.

**React.memo 를 적용 전**
이미지가 적게 있는 경우 `SearchResult` 의 렌더링 시간이 1.6ms 가 걸렸음을 확인할 수 있었어요.
<img width="555" alt="gif 이미지 초기 렌더링" src="https://github.com/user-attachments/assets/49e0b92e-9d4c-4ec7-9b7f-fd5e752efb9f">

이미지를 많이 있는 경우 `SearchResult` 의 렌더링 시간을 보면 5.9ms 가 걸리며 이미지가 많을수록 렌더링 시간이 늘어남을 확인할 수 있었어요.
<img width="612" alt="gif 이미지 나중 렌더링" src="https://github.com/user-attachments/assets/d3bd8e29-3a2b-4cfe-a6c3-bc47fd4bfb4f">

**React.memo 를 적용 후**

메모이제이션을 적용한 후 이미지를 많이 로드했을 때 메모이제이션의 이점을 크게 볼 수 있었는데 `SearchResult` 의 렌더링 시간이 1.1ms 로 생각보다 렌더링 시간의 많은 차이가 있음을 확인할 수 있었어요!
<img width="549" alt="memo 적용 후 나중 렌더링 (전체)" src="https://github.com/user-attachments/assets/21927edc-b3ae-43e6-9bb2-51b558788997">

2024-09-10 07:26 UTC, healim01 requested changes
안녕하세요 다르~! 
잘지내고 계신가요? 다른 캠퍼스다보니 이전에 우연히 만난 뒤로 볼 수가 없네요~ 

이번에도 다르의 깔끔한 코드와 꼼꼼한 설명 덕분에 많은 걸 배워갑니다! 

다만, 배포된 사이트에서 발견된 작은 버그가 있어서 확인 한번 해주시면 너무 좋을거 같아요~ ☺️

2024-09-10 07:26 UTC, healim01 commented on src/App.tsx
>          <Route path="/" element={<Home />} />
Home page 는 lazy 적용을 안해주신 특별한 이유가 있나요~?

2024-09-10 07:26 UTC, healim01 commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      <img className={styles.featureImage} src={imageSrc} alt={title} />
`alt` 추가 너무 좋네요~! 👍

2024-09-10 07:26 UTC, healim01 commented on webpack.config.js
> +  };
오 이런 옵션도 있군요!? production 환경일 때만 압축화를 해주는 건가요?

2024-09-10 07:26 UTC, healim01 commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      <img className={styles.featureImage} src={imageSrc} alt={title} />
그런데 지금 git 파일이 보이지 않고 있네요,,,~~ 
아무래도 `gif` -> `mp4` 로 변경된 후 코드 변경이 없어서 그런거 같아요~ 

이 파일 코드가 변해야할거 같습니당 힌트 투척하고 갑니다~~!! 

<img width="1680" alt="스크린샷 2024-09-10 오전 10 21 25" src="https://github.com/user-attachments/assets/e521f0ca-5d6a-4878-ae03-72b6d4804a7f">

2024-09-10 07:26 UTC, healim01 commented on src/pages/Search/components/GifItem/GifItem.tsx
> +export default memo(GifItem);
지금 코드 상으로는 memo 가 되는거 같은데 배포된 사이트에서 `load more` 클릭하니 위에 결과가 다시 재랜더되는거 같네요,,,!! 
확인 한번 해주시면 너무 좋을거 같아요! 

참고 영상 


https://github.com/user-attachments/assets/6e2e6609-9025-4bc5-bbf5-a5bebc04a3c2

2024-09-10 07:26 UTC, healim01 commented on index.html
크기가 큰 사진이다보니 preload 설정하는 것이 좋을거 같네요!!

그런데 지금 preload 때문에 초반 랜더될 때 hero 사진이 두번 불러오는 걸까요?  

<img width="1148" alt="스크린샷 2024-09-10 오후 3 54 47" src="https://github.com/user-attachments/assets/19b9641a-718f-4fa9-90c6-4673ac9a7cbc">

2024-09-10 07:26 UTC, healim01 commented on index.html
그리고 PR에 보면 헤더에 Cache-Contro를 적용하였고 이후에 캐시 적용이 되고 있다고 적혀 있는데요!
새로고침을 하고 네트워크 창을 확인해보니 사이즈가 잡히고 있어서요...~ 
제가 알기로는 캐싱되게 되면 사이즈가 `disk cache` 나 `memory cache`로 잡히는걸로 알고 있는데 다른 방식도 있는걸까요...?

한번 확인해주시면 너무 좋을거 같아요~!! 

**참고 사진**
<img width="620" alt="스크린샷 2024-09-10 오후 4 17 36" src="https://github.com/user-attachments/assets/62eb8dcb-2d82-4682-a253-0d257b0b2099">

2024-09-10 09:56 UTC, pp449 reviewed
꼼꼼하게 봐주셔서 감사합니다 헤일리!

제가 놓친부분이 한 두개가 아니었군요.. ㅋㅋㅋㅋㅋ
저는 그냥저냥 지내고 있어요! 헤일리도 잘 지내고 계시죠?!

피드백 반영과 더불어 선택 요구사항도 반영해봤어요!

> 도움말 패널은 많은 수의 엘리먼트를 포함하고 있습니다. 이 패널 자체를 최적화하는 작업은 위의 요구사항들을 모두 진행한 뒤에 원한다면 추가적으로 시도해보세요 :)

`DUMMY_ARTISTS_LENGTH = 10000` 으로 바꾸니 search 페이지에서부터 확실히 느려지는 현상이 있었어요. Profile 로 측정해본 결과 아래와 같이 한 번에 모든 데이터를 가져와 렌더링 처리를 하느라 인터렉션의 지연됨을 확인할 수 있었어요!

<img width="499" alt="Screenshot 2024-09-10 at 6 25 15 PM" src="https://github.com/user-attachments/assets/33a019ac-6fd2-4991-9f5d-25be5288ad1c">

ArtistList 컴포넌트를 렌더하는데 약 3초가 걸렸네요

그래서 `IntersectionObserver`를 이용하여 현재 화면에 보이는 만큼만 동적으로 렌더링 하도록 구성했어요 그리고 아래 결과를 확인해보면

<img width="646" alt="Screenshot 2024-09-10 at 6 27 58 PM" src="https://github.com/user-attachments/assets/62eba23b-d074-4904-b0c2-7766779e6103">

결과와 같이 `ArtistList`의 정보를 일괄적으로 렌더링하는게 아닌 동적으로 필요한 만큼만 렌더링하니 프레임이 쪼개지면서 렌더링되어 최적화를 시킬 수 있었어요!

동적으로 불러오는 컨텐츠에 렌더링 애니메이션도 추가해줬어요

https://github.com/user-attachments/assets/77a27483-baf7-4854-b190-afa3b1c74d7a

2024-09-10 09:56 UTC, pp449 commented on index.html
요거 마위가 알려줬는데 html 파일에서 불러올 때 `crossorigin="anonymous"` 해당 옵션을 이용하니 제대로 캐싱이 안되더라구요. 

그래서 브라우저가 2번째 요청을 보내는 방식이었는데 수정하겠습니당

2024-09-10 09:56 UTC, pp449 commented on index.html
위에서 수정되어 아마 이제 2번 요청은 안갈것 같은데 

2번째 요청에서 이미지 파일을 그대로 요청하는게 아닌 현재 캐싱된 이미지가 최신 데이터인지 확인하는 데이터 요청을 주고 받는거 같아요!

2024-09-10 09:56 UTC, pp449 commented on src/App.tsx
>          <Route path="/" element={<Home />} />
유저가 높은 확률로 Home 화면부터 마주한다 생각하여 lazy 로딩을 적용하면 FCP 가 줄어들거라 예상하여 적용하지 않았아요

2024-09-10 09:56 UTC, pp449 commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      <img className={styles.featureImage} src={imageSrc} alt={title} />
엇 gif를 처음에 바꿨다가 안보여서 이때까지 메인 화면에 gif 가 없는게 당연한건줄 알았네요.. ㅋㅋㅋㅋㅋㅋㅋㅋ

감사합니당 😄

2024-09-10 09:56 UTC, pp449 commented on src/pages/Search/components/GifItem/GifItem.tsx
> +export default memo(GifItem);
이게 확인해보니 로컬에서 작업한것을 cloudfront에 반영을 안했었더라구요.. 바로 반영했습니다!

2024-09-10 09:56 UTC, pp449 commented on webpack.config.js
> +  };
넵 꼭 production에서만 적용할 필요는 없는것 같지만 비교해보기 위해서 prod 에만 적용되도록 했어요!

2024-09-11 07:02 UTC, healim01 approved these changes
코멘트를 멋지게 반영해주셨군요 다르~!! 

너무 좋습니당 요구사항도 모두 충족하시고 추가 과제까지 멋지게 진행해주셔서 더 이상 코멘트 드릴께 없네용~!
이만 approve 하겠습니다! 수고하셨습니당

2024-09-11 07:04 UTC, merged