[개인 미션 - 성능 오답노트] 렛서(김다은) 미션 제출합니다.
woowacourse/perf-basecamp pull request #124
Opened 2024-09-07 16:50 UTC by llqqssttyy

## 🔥 결과

### 배포한 CloudFront 접근 경로

[🚀 개선 사이트](https://doyts9o3bxwvh.cloudfront.net/)

### 개선 전후 성능 측정 결과

<table>
  <thead>
    <tr>
      <th align="center">버전</th>
      <th align="center">Lighthouse</th>
      <th align="center">WebPageTest</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th><a href="https://llqqssttyy.github.io/perf-basecamp/">🔗 개선 전</a></th>
      <td><img src="https://github.com/user-attachments/assets/0b8578f5-818b-46db-b338-ae017ae71f7d" /></td>
      <td><img src="https://github.com/user-attachments/assets/ddb347b4-e767-4052-a0f2-d60258337d6b" /></td>
    </tr>
    <tr>
      <th><a href="https://doyts9o3bxwvh.cloudfront.net/">🔗 개선 후</a></th>
      <td><img src="https://github.com/user-attachments/assets/e8afc9bd-85cd-490a-a46c-36cefd8ca8e9" /></td>
      <td><img src="https://github.com/user-attachments/assets/ddb347b4-e767-4052-a0f2-d60258337d6b" /></td>
    </tr>
  </tbody>
</table>

<br/>

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기

  - JS Minify는 webpack v5에서 자동으로 적용되므로 별도의 설정은 하지 않았습니다.
  - `MiniCssExtractPlugin`으로 prod 버전에서 CSS 코드를 bundle.js와 분리했습니다.
  - `CssMinimizerPlugin`으로 추출된 파일을 Minify 해주었습니다.

- [x] 이미지 크기 줄이기
  - png 이미지는 jpg와 webp로, gif는 mp4와 webm으로 변환했습니다.
  - 기본적으로 webp, webm을 렌더링하고, 해당 형식을 지원하지 않는 브라우저는 jpg, gif를 보여주도록 했습니다.
  - 이미지 변환은 ImageMagick webpack의 `ImageMinimizerWebpackPlugin`으로, mp4와 webm은 ffmpeg cli로 수동 압축했습니다.
  - 디스플레이 크기에 따라 적절한 hero 이미지를 받아오도록 srcSet 설정을 했습니다.

<br/>

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
  - Route에 들어가는 페이지를 동적 import로 변경해 리소스를 분리했습니다.
- [x] 아이콘 패키지 Tree Shaking
  - webpack은 기본적으로 사용되는 모듈만 번들링되므로 별도의 설정을 해주진 않았습니다.

<br/>

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 / S3 메타데이터 설정 (설정값, 해당 값을 설정한 이유 포함)
  - CloudFront의 캐시 정책을 ['CachingOptimized'](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html?icmpid=docs_console_unmapped#compressed-content-cloudfront-notes)로 설정해 크기가 큰 오브젝트는 Gzip으로 자동 전송되게 했습니다.
  - 재방문 시 페이지 로딩 속도를 향상시키기 위해서 S3의 모든 오브젝트에 `Cache-Control` 메타데이터를 추가해 캐싱이 되도록 했습니다. max-age는 1일입니다.
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
  - Cache API를 사용해 응답을 캐싱하도록 했습니다.
  - url을 키로 하여 캐시된 데이터가 존재하면 요청을 보내지 않습니다.
  - stale time은 1시간입니다.

<br/>

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - `GiftList`와 `GifItem` 컴포넌트를 메모이제이션해 추가된 목록만 렌더되도록 했습니다.
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
  - `CustomCursor`와 `HelpPanel` 컴포넌트에서 layout shift가 일어나지 않도록 transform 속성이 변하도록 수정했습니다.
- [x] Frame Drop이 일어나지 않아야 한다.

  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

  ![FPS](https://github.com/user-attachments/assets/81356243-04a3-4be8-aa36-7faf171891b0)

<br/>

## 🧐 공유

### Trouble Shooting

CacheManager 클래스를 구현하면서 다음과 같은 에러를 마주했습니다.

```shell
Uncaught (in promise) TypeError: Failed to execute 'json' on 'Response': body stream already read
```

이 에러는 Response 객체의 본문(body)이 ReadableStream이기 때문에 발생합니다. ReadableStream은 데이터 스트림을 한 번만 읽을 수 있는 일회성 객체입니다. 즉, 한 번 response.json()으로 본문을 읽으면 그 스트림은 소진되며 이후 다시 읽을 수 없게 됩니다.

문제가 된 코드를 보면, cacheResponse 함수에서 Response 객체를 캐싱한 후에 다시 response.json()으로 본문을 읽으려고 시도하면서 에러가 발생했습니다.

```ts
// CacheManager.ts
async cacheResponse(cacheKey: string, response: Response): Promise<void> {
  // ...
  await this.cacheStorage.put(cacheKey, response);
}

// apiClient.ts
await cacheManager.cacheResponse(cacheKey, response);
return response.json(); // 에러 발생
```

cacheResponse에서 Response를 그대로 캐시로 저장한 후 다시 읽으려고 할 때, 이미 본문이 읽혔기 때문에 스트림이 소진된 상태라 json() 메서드가 실패합니다.

#### 해결 방법

response.clone()을 사용하면 같은 내용을 가진 새로운 Response 객체를 생성하도록 변경했습니다. 이렇게 하면 하나는 캐시로 저장하고, 다른 하나는 본문을 읽는 데 사용할 수 있습니다.

```ts
// CacheManager.ts
async cacheResponse(cacheKey: string, response: Response): Promise<void> {
  // ...
  await this.cacheStorage.put(cacheKey, response.clone());
}
```

2024-09-10 13:46 UTC, simorimi requested changes
안녕하세요 렛서 좋은 코드들 잘 봤습니다. 
미션이 꽤 많았을텐데도 불구하고 하나하나 깊게 고민한 흔적이 보였어요. 그리고 깊게 고민한 끝에 좋은 결과물을 낸 거 같네요! 
코드 리뷰를 진행하면서 피드백 보다는 오히려 제가 모르던 부분이 보여 하나하나 학습하는 시간이 되었네요. 크게 수정사항은 없습니다! 제가 남긴 코멘트 보시고 다시 리뷰 요청 주세요.

추가로 이번 미션에서 frame drop이 일어나지 않아서 수정사항이 없는 것으로 봤는데 requestAnimationFrame에 대해서 한 번 참고해도 좋을 것 같습니다!

2024-09-10 13:46 UTC, simorimi commented on webpack.config.js
> +  cache: false,
해당 부분을 설정한 의도가 있을까요? cache를 비활성화 하게 되면 development에서 빌드 속도가 느려질 것으로 보여서요

2024-09-10 13:46 UTC, simorimi commented on webpack.config.js
> +      excludeAssets: [/node_modules/]
내부 속성을 설정한 것 좋네요! 덕분에 공부 해봤습니다

2024-09-10 13:46 UTC, simorimi commented on webpack.config.js
> +    minimizer: ['...', new CssMinimizerPlugin()]
...을 왜 사용하였는지 보니 CssMinimizerPlugin만 적으면 기존의 TerserPlugin을 이용하지 못해서 그렇군요 하나 또 배워갑니다

2024-09-10 13:46 UTC, simorimi commented on webpack.config.js
> +    minRatio: 0.8
gzip 압축 설정이 꼭 필요한가요? gzip이 있더라도 cloudfront에서 brotli 방식을 선택하지는 않던가요?

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +              png: { quality: 80 },
png를 jpeg로 개선했더라고요! 해당 부분은 없어도 괜찮지 않을까요?

2024-09-10 13:46 UTC, simorimi commented on src/pages/Home/Home.tsx
> +        </picture>
반응형을 고려한 디테일이 좋네요

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +              gif: { quality: 80 }
이 부분도 결국에 gif를 없애고 webm 과 mp4만 활용하였다면 없어도 괜찮지 않을까요?

2024-09-10 13:46 UTC, simorimi commented on src/pages/Home/Home.tsx
> +          <h2 className={styles.subtitle}>gif search engine for you</h2>
테그까지 신경쓰는 꼼꼼함이 좋네요

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> -    }),
오 이전 커밋에서는 봤는데 다시 제거가 되었군요 좋습니다

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +      new TerserPlugin(),
얘를 다시 부활시킨 이유가 있을까요?

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +    sideEffects: true,
얘를 추가한 이유는 무엇일까요?

2024-09-10 13:46 UTC, simorimi commented on src/App.tsx
> +      <Suspense fallback={<div style={{ height: '100vh' }}>Loading...</div>}>
loading...만 있는 경우 footer layout shift가 일어나서 이러한 작업을 해준 것을 보이네요! 이 부분은 성능 지표를 보면서 개선한 것으로 보이는데 하나 배우고 갑니다

2024-09-10 13:46 UTC, simorimi commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +    () => (
저의 경우는 memo만 써도 충분했었는데 useMemo를 쓰신 이유가 있나요?

2024-09-10 13:46 UTC, simorimi commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +
memo를 쓰게 되면 성능 확인에서 gifItem이 아니라 Anonymous 이런식으로 보여지지 않던가요? displayname이라는 속성을 활용하면 해결할 수 있더라고요 참고바랍니다

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +              jpeg: { quality: 60 }
숫자를 80에서 60으로 바꾸신 이유가 있을까요?

2024-09-10 13:46 UTC, simorimi commented on webpack.prod.js
> +              jpeg: { quality: 40 }
이번에는 40으로 줄었군요!

2024-09-10 13:46 UTC, simorimi commented on src/pages/Search/components/ArtistInfo/ArtistInfo.tsx
> +      <img className={styles.profileImage} src={profileImageUrl} loading="lazy" />
loading에 lazy를 추가하셨군요 좋네요!

2024-09-10 13:46 UTC, simorimi commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +        {gifList.length
사소하지만 해당 부분 hasGifItem 정도로 해서 조금 더 직관적으로 읽을 수 있으면 더 좋겠다는 생각이 듭니다

2024-09-10 13:46 UTC, simorimi commented on src/utils/CacheManager.ts
> + */
주석이 없어도 충분할 거 같아요

2024-09-10 13:46 UTC, simorimi commented on src/utils/apiClient.ts
> +    staleTime: number = 60 * 60 * 24 * 365 // 1 year
여기 가독성을 고려하여 주석과 분 초 시 년 이렇게 구분해서 적은 거 좋네요

2024-09-10 13:46 UTC, simorimi commented on src/utils/CacheManager.ts
> +    this.cacheStorage = await caches.open(this.name);
caches가 무엇인지 고민했는데 해당 부분이 cache api군요 덕분에 새로 알아갑니다

2024-09-11 04:45 UTC, llqqssttyy commented on webpack.config.js
> +  cache: false,
초기 세팅이고 최종버전에서는 지워서 정확한 이유는 기억나지 않네요..!😅
미션 초반에 dist가 생기지 않는 문제가 있었는데, 이를 해결하기 위한 방법 중 하나였을 거라고 추측해봅니다ㅎㅎ

2024-09-11 04:58 UTC, llqqssttyy commented on webpack.config.js
> +    minRatio: 0.8
압축해서 올리지 않더라도 1,000bytes가 넘는 오브젝트는 CloudFront가 자동으로 gzip으로 압축한다는 정보를 안 뒤로는 위 코드를 제거했습니다! 요건 제거하기 전 코드네요.😅

> gzip이 있더라도 cloudfront에서 brotli 방식을 선택하지는 않던가요?

S3에 gzip을 직접 올릴 때 오브젝트의 메타 데이터로 Content-Encoding을 명시하면 gzip으로 보내주었습니다.
압축까지 CloudFront에 맡길 경우엔 brotli로 보내더라구요. 

> [aws - 압축된 파일 제공](https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html)
> CloudFront는 Gzip 및 Brotli 압축 형식을 사용하여 객체를 압축할 수 있습니다. 최종 사용자가 두 형식을 모두 지원하고 연결된 캐시 서버에 두 형식이 모두 있는 경우 CloudFront는 Brotli를 선호합니다. 캐시 서버에 압축 형식이 하나만 있는 경우 CloudFront는 압축 형식을 반환합니다.

위 설명에 따르면 CloudFront는 최신 알고리즘인 brotli를 선호하는 것 같아서, 둘 다 없는 경우엔 brotli로 보내는 게 아닐까.. 추측해봅니다.

2024-09-11 05:02 UTC, llqqssttyy commented on webpack.prod.js
> +      new TerserPlugin(),
하핫 설정을 만지다가 다 지우고 제거를 안했네요~ 지워서 커밋했어요. [chore: TerserPlugin 제거](https://github.com/woowacourse/perf-basecamp/pull/124/commits/3f8b25485a934d40d8264cc50f71b5fcaea5b581)

2024-09-11 05:05 UTC, llqqssttyy commented on webpack.prod.js
> +    sideEffects: true,
트리 쉐이킹을 위해서 별도의 설정이 필요한 줄 알고 추가했습니다. 찾아보니 기본값이 true라서 최종에선 제거했어요!

2024-09-11 05:27 UTC, llqqssttyy commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +    () => (
아하, 페이지가 이동됐을 때 메모이제이션된 리스트를 보여줄 거란 생각을 했는데 실제로는 그렇지 않네요.
메모이제이션은 생명주기 안에서만 유효하다고 합니다. 시모 피드백 덕분에 하나 더 배웠네요.👍

2024-09-11 05:34 UTC, llqqssttyy commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +    () => (
반영해서 올렸습니다~ [refactor: gifList memoization 제거](https://github.com/woowacourse/perf-basecamp/pull/124/commits/ac1dfcc318f77618916531d49b42617224908b1a)

2024-09-11 05:37 UTC, llqqssttyy commented on webpack.prod.js
> +              jpeg: { quality: 40 }
용량이 크더라구요..🤣

2024-09-11 05:40 UTC, llqqssttyy commented on src/utils/CacheManager.ts
> + */
cache storage에 대한 백그라운드가 없는 개발자라면 init으로 초기화해야 한다는 것을 모르고 메서드만 사용할 것 같아 주석을 추가해줬습니다.☺️

2024-09-11 06:55 UTC, llqqssttyy commented on src/pages/Search/components/SearchResult/SearchResult.tsx
> +        {gifList.length
좋은 제안 감사해요, 시모.
해당 코드가 `gifList.length === 0`처럼 쓰였거나 더 복잡한 조건문이라면 hasGifItem이라는 변수로 만들어도 좋지만, 
제 의견으로는 이해하기 어려운 코드는 아니라서 해당 내용은 반영하지 않을게요.🤗

2024-09-11 07:00 UTC, llqqssttyy commented
안녕하세요 시모~ 
정성스러운 코멘트 모두 확인했습니다! 새로운 것들도 얻어가는 감사한 시간이었어요.
변경 제안주신 부분 반영하고 코멘트 남겨주신 부분 답글을 달아뒀으니 확인해주세요!
 
이틀 뒤면 긴 연휴가 기다리고 있네요. 조금만 더 힘냅시닷.💪

2024-09-11 08:54 UTC, simorimi commented
렛서 고생하셨습니다! 렛서 의견에 설득당한 것도 많네요
너무 고생하셨고 이만 merge 하겠습니다!

2024-09-11 08:54 UTC, simorimi commented
렛서 고생하셨습니다! 렛서 의견에 설득당한 것도 많네요
너무 고생하셨고 이만 merge 하겠습니다!

2024-09-11 08:55 UTC, merged