[개인 미션 - 성능 오답노트] 소하(최소연) 미션 제출합니다.
woowacourse/perf-basecamp pull request #132
Opened 2024-09-08 18:33 UTC by soi-ha

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://d23xsk46hx6md3.cloudfront.net/
- 개선 전후 성능 측정 결과
- [x]  Lighthouse performance **`95점`** 이상

    - 개선 전
        
       <img width="582" alt="스크린샷 2024-09-04 11 01 24" src="https://github.com/user-attachments/assets/a7b6b949-112b-4abb-955c-67d9b3cad231">
        
    - 개선 후
        
       <img width="1512" alt="최종결과_lighthouse" src="https://github.com/user-attachments/assets/8bbcf1f6-f608-41fa-b2dd-9b39b65dd398">
        
- [x]  Home 페이지에서 불러오는 스크립트 리소스 크기 **`< 60kb` &&** 히어로 이미지 크기 **`< 120kb`**
    - 개선 전
       

        <img width="686" alt="스크린샷 2024-09-04 11 05 11" src="https://github.com/user-attachments/assets/de7f9f87-0cf9-4d91-afaf-9be409679cb3">
        
    - 개선 후
        
       <img width="1512" alt="최종결과_리소스크기" src="https://github.com/user-attachments/assets/21b0afa6-8af7-462f-a9fb-0e3e9cff8825">

- [x]  **`프랑스 파리`** 에서 **`Fast 3G`** 환경으로 접속했을 때
    - Home 첫 번째 로드시 LCP **`< 2.5s`**
    - Home 두 번째 이후 로드시 LCP **`< 1.5s`**
    - 개선 전
       

       <img width="1512" alt="스크린샷 2024-09-04 13 23 16" src="https://github.com/user-attachments/assets/32239bbc-26be-456a-b345-ff5330a02b63">
        
    - 개선 후
        
        <img width="1458" alt="최종결과_webPageTest" src="https://github.com/user-attachments/assets/8ae88c0a-982e-4473-a52d-5a1433c9c9b6">

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x]  소스코드 크기 줄이기
    - minify & uglify
        
        terser를 사용하여 build를 진행할 때, minify와 uglify를 진행하도록 했습니다.
        
        ```jsx
        optimization: {
            minimize: true,
            minimizer: [
              new TerserPlugin({
                terserOptions: {
                  mangle: true, // 변수명 난독화(uglify) 활성화
                  compress: true, // 코드 압축(minify) 활성화
                  output: {
                    comments: false // 주석 제거
                  }
                }
              })
            ]
          }
        ```
        
        terser-webpack-plugin을 사용하기 때문에 webpack.config.js 파일에 위와 같은 옵션을 추가하였습니다.

        - terser 적용 전
            
           <img width="692" alt="스크린샷 2024-09-04 15 52 11" src="https://github.com/user-attachments/assets/b8271fbd-0eaa-4c64-9667-31ea06df8db8">
            
        - terser 적용 후
            
            <img width="747" alt="스크린샷 2024-09-04 15 50 20" src="https://github.com/user-attachments/assets/7b29a257-2501-46e0-a37f-bff9bc755c1a">

            
        
        terser를 적용하여 bundle.js의 사이즈가 1MB에서 213KB로 줄은 것을 볼 수 있습니다.
        
    - gzip
        
        compression-webpack-plugin을 사용하여 gz 압축 파일을 생성했다.
        
        ```jsx
         plugins: [
            new CompressionPlugin({
              algorithm: 'gzip',
              exclude: /\.(eot|svg|ttf|woff|woff2|png|jpg|gif|webp|txt|map|ico)$/i
            })
          ],
        ```
        
        bundle.js와 bundle.js.gz 파일의 크기를 비교해보면 많이 압축된 것을 확인할 수 있다.
        
       <img width="644" alt="스크린샷 2024-09-05 10 27 09" src="https://github.com/user-attachments/assets/cdfcff0a-c9eb-4668-964f-839f126d6f55">
        
        프론트엔드에서는 위 설정을 통해 gz 파일만 만들어주면 된다. 브라우저는 gz 파일을 압축해제하는 기능이 내장되어 있기 때문이다.
        
- [x]  이미지 크기 줄이기
    
    hero.png의 해상도가 4000이라는 말도 안되는 width를 가지기 때문에, 해상도를 2050으로 바꿔줬다. 또한, 확장자를 png에서 avif로 바꿔줬다. webp라는 선택지도 존재했지만 avif가 webp보다 용량도 더 작고 이미지 품질이 좋기 때문에 avif 확장자를 사용했다. 
    
    gif 파일은 webm으로 바꿔줬다. 해당 확장자를 사용하면 용량이 더 작은 것을 볼 수 있다.

   <img width="745" alt="스크린샷 2024-09-05 13 48 31" src="https://github.com/user-attachments/assets/2531f1d6-f6cb-467a-b59d-fc5c63904c42">
    **🚀 트러블 슈팅**
    
    webm 파일을 적용하면서 문제가 발생했다.
    
    <img width="1512" alt="스크린샷 2024-09-05 13 51 36" src="https://github.com/user-attachments/assets/6144449d-363b-4d33-b77d-885d0e169e8a">
    
    webm 파일을 정상적으로 받아오지만 화면에 렌더링을 하지 못하고 있다. 이유는 아래 코드를 통해 파악할 수 있었다.
    
    ```tsx
     <div className={styles.featureItem}>
      <img className={styles.featureImage} src={imageSrc} />
      // ...
    </div>
    ```
    
    gif 파일은 이미지로 분류되기 때문에 img 태그를 통해 실행될 수 있었다. 하지만 난 gif가 아닌 webm을 사용했다. webm은 동영상으로 분류되기 때문에 img 태그로는 적용될 수가 없었다.
    
    따라서 webm을 사용하기 위해서는 img 태그가 아니라 video 태그를 사용해줘야 한다.
    
    ```tsx
     <div className={styles.featureItem}>
      <video className={styles.featureImage} autoPlay loop muted>
        <source src={imageSrc} type="video/webm" />
      </video>
     // ...
    </div>
    ```
    
    video 태그를 사용해줬더니 정상적으로 출력되는 것을 볼 수 있다!
    
  <img width="1512" alt="스크린샷 2024-09-05 14 03 36" src="https://github.com/user-attachments/assets/d18bf319-7086-4cad-8dcf-d29ea37f2a0a">
    
    srcSet을 사용하여 화면 해상도에 따라 적절한 해상도의 hero를 보여주도록 했습니다. 디스플레이 해상도나 브라우저의 뷰포트 너비에 따라 적절한 이미지를 렌더링하도록 하여 최적의 페이지의 로딩 속도와 이미지 해상도를 제공하기 위함입니다.
    
    ```tsx
     <img
      className={styles.heroImage}
      src={heroImage}
      alt="hero image"
      srcSet={`${heroSmallImage} 1025w, ${heroMediumImage} 1367w`}
    />
    ```

**2 필요한 것만 요청하기**

- [x]  아이콘 패키지 Tree Shaking
    - Tree shaking?
        
        빌드 시에 사용하지 않는 코드를 제거하는 최적화 과정
        
        webpack-bundle-analyzer를 사용하여 불필요하게 react-icons가 모두 불러와지고 있음을 확인할 수 있다. 따라서, Tree shaking을 하여 불필요한 react-icons 코드를 제거하였다.
        
        react-icons 트리 쉐이킹을 위해 webpack의 설정을 변경하였다. mode가 production일 경우 사용하는 것만 불러온다. 
        
        ```jsx
        const isProduction = process.env.NODE_ENV === 'production';
        
        module.exports = {
          mode: isProduction ? 'production' : 'development',
          // ...
        }
        ```
        
- [x] 페이지별 리소스 분리
    - code splitting?
        
        프론트엔드 애플리케이션의 번들을 작은 조각으로 분할하여 필요한 부분만 로드하는 최적화 기법이다. 코드 스플리팅을 통해 초기 로딩 속도를 개선할 수 있다.
        
        dynamic import, lazy와 Suspense를 사용하여 컴포넌트를 필요한 시점에서 로드할 수 있도록 수정했다.
        
        해당 코드에서는 Home과 Search를 필요한 시점에서 로드하도록 했다.
        
        ```tsx
        import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
        import { lazy, Suspense } from 'react';
        
        import NavBar from './components/NavBar/NavBar';
        import Footer from './components/Footer/Footer';
        
        import './App.css';
        
        const Home = lazy(() => import('./pages/Home/Home'));
        const Search = lazy(() => import('./pages/Search/Search'));
        
        const App = () => {
          return (
            <Suspense fallback={<div>...loading</div>}>
              <Router>
                <NavBar />
                <Routes>
                  <Route path="/" element={<Home />} />
                  <Route path="/search" element={<Search />} />
                </Routes>
                <Footer />
              </Router>
            </Suspense>
          );
        };
        
        export default App;
        
        ```

**3 같은 건 매번 새로 요청하지 않기**
- [x]  CDN을 적용하고, 한 번 요청한 리소스는 CDN 캐시에서 불러와야 한다.
    
    S3, CloudFront 캐시 설정을 다음과 같이 기본 캐시 정책으로 설정했다.
    
    <img width="753" alt="스크린샷 2024-09-09 00 20 49" src="https://github.com/user-attachments/assets/05fc7ecf-6828-4056-92f8-08aa1586c365">
    
- [x]  GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
    
    cacheStorage를 사용하여 treding API가 매번 새롭게 요청되지 않도록 했습니다.
    
    세션 스토리지를 사용할 수 있었지만 캐시 스토리지를 사용한 이유는 다음과 같습니다.
    
    - 데이터의 유효 기간이 길어야 할 경우, 캐시 스토리지는 데이터를 더 오래 보관할 수 있습니다. 자주 변하지 않는 이미지, css, js 파일 등을 캐시에 저장하면 사용자가 웹 사이트에 재방문할 때 더 빠르게 로드할 수 있습니다. 세션 스토리지는 브라우저 탭이나 윈도우가 닫히면 데이터가 삭제되기 때문에 적합하지 않습니다.
    - 데이터의 크기가 큰 경우(대용량 정적 자원(이미지, 동영상 등))를 저장할 때는 캐시 스토리지가 더 적합합니다. 세션 스토리지는 작은 용량을 저장할 때 좋습니다.
    - 정적 자원이 반복 사용될 경우, 캐시를 통해 로드 속도를 개선할 수 있습니다. 세션 스토리지는 사용자 세션 동안에만 필요한 데이터를 저장하는 것에 더 적합합니다.
    - 네트워크 요청을 최소화 할 때, 캐시 스토리지는 자주 사용되는 정적 자원을 캐시에 저장하면 네트워크 트래픽을 줄일 수 있습니다. 세션 스토리지는 서버 요청을 줄이는 것 보다 사용자 세션 동안 필요한 데이터를 유지하는데 더 적합합니다.
    
   <img width="1512" alt="스크린샷 2024-09-09 01 27 52" src="https://github.com/user-attachments/assets/d0715151-3c46-4d84-ae02-f0ade609ef56">

**4 최소한의 변경만 일으키기**

- [x]  검색 결과 > 추가 로드시 추가되는 결과에 대해서만 화면 업데이트가 새로 일어나야 한다.
    
    React.memo를 통하여 검색 결과(Gif [...]

2024-09-09 16:39 UTC, 00kang requested changes
소하, 안녕하세요 ~ 초코에요
다른 캠퍼스에서 지내다가 이렇게 만나니 괜히 더 반갑네용 ❤️ 

소하의 성격대로 꼼꼼하게 작성되어 있던 PR 잘 읽었습니다! 
학습 키워드 별 개념 정리부터, 어떤 이유로 어떻게 코드에 적용하였는지 잘 정리되어 있어서 작업 내용을 확인하기 아주 좋았어요. 💯 
몇 가지 코멘트 남겼으니 확인해주세요~

2024-09-09 16:39 UTC, 00kang commented on index.html
> +      onload="this.media='all'"
오, 저는 `preload`만 알고 있었는데 덕분에 새로운 개념 알아가용 👍 

> `meadia="print"`를 사용해서 당장 화면에 필요하지 않다고 속여서 브라우저가 폰트 로딩을 페이지 렌더링의 차단 요소로 취급하지 않는다. 폰트가 로드되면 `onload="this.media='all'"`을 통해 모든 상황에서 폰트를 사용하게 한다.

2024-09-09 16:39 UTC, 00kang commented on src/App.css
> +  unicode-range: U+0000-007F;
우와 꼼꼼한 소하의 성격이 보이는 부분이네요. 하나 더 배워갑니다.
> `unicode-range: U+0000-007F;` 로 기본적인 라틴 알파벳, 숫자, 일반적인 구두점을 포함하는 문자 범위를 나타내며, 이 범위의 내의 문자가 사용된다면 필요한 문자만 포함된 더 작은 폰트 파일을 다운로드한다.

2024-09-09 16:39 UTC, 00kang commented on src/pages/Home/Home.tsx
> +import heroSmallImage from '../../assets/images/hero_small.avif';
👍

2024-09-09 16:39 UTC, 00kang commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      </video>
사실 저도 gif이미지를 webm이미지로 바꾸면서 이 부분을 놓쳤더라고요?(ㅋㅋ) 
다행히도 소하의 PR 중 트러블슈팅 기록을 보고 잡을 수 있었답니다~ 감사 🙇

2024-09-09 16:39 UTC, 00kang commented on webpack.config.js
> +  mode: isProduction ? 'production' : 'development',
개발 환경과 프로덕션 환경을 구분하는 게 어떻게 성능 개선에 도움이 되는건가요?? 
(저는 잘 몰라서 사용하지 않은 방법이라 질문드려용, 압박질문 같은 거 절대 아닙니다)

2024-09-09 16:39 UTC, 00kang commented on webpack.config.js
> +      new TerserPlugin({
제가 알기로는 Webpack5에서는 프로덕션 모드에 자동으로 `TerserPlugin`을 사용한다고 알고 있어요. 기본적으로 제공하는 기능을 잘 사용하는 것도 좋지 않을까요~?

2024-09-09 16:39 UTC, 00kang commented on src/apis/gifAPIService.ts
> +const getTrendingFromCache = async (): Promise<GifImageModel[] | null> => {
캐시에서 데이터를 가져오는데, 주기적으로 캐시를 갱신하는 로직은 어떻게 되나욤? 이 부분이 고려되어 있는 건지 궁금해요!

2024-09-11 01:01 UTC, soi-ha commented on index.html
> +      onload="this.media='all'"
ㅎㅎ 저도 몰랐다가 일리 폰트 적용 슥-샥-숑- 하면서 알게됐어욯ㅎ

2024-09-11 01:02 UTC, soi-ha commented on src/App.css
> +  unicode-range: U+0000-007F;
초코가 검색한 내용까지 코멘트로 남겨줘서 저도 너무 좋아효!

2024-09-11 01:50 UTC, soi-ha commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      </video>
오, 도움이 되었다니 다행입니댜!

2024-09-11 01:57 UTC, soi-ha commented on webpack.config.js
> +  mode: isProduction ? 'production' : 'development',
원래는 react-icons를 사용하지 않는 것도 모두 불러오게 됩니다. 
그런데, mode가 production일 경우에는 사용하는 icon만 불러오게 됩니다! 따라서 mode를 production으로 하는 것 만으로도 tree shaking이 됩니다~!
(GPT)[https://chatgpt.com/share/1babd8f7-7456-4f79-8c65-c93f33840a7d]를 쥐어짜낸 답변이에요! 한번 읽어보시면 좋을 것 같아용

2024-09-11 01:58 UTC, soi-ha commented on webpack.config.js
> +      new TerserPlugin({
앗! 마자요! webpack에서 기본으로 제공하지만 제가 알기로는 추가 option을 설정하고 싶다면 TerserPlugin을 사용해야 한다고 들었습니다! 그래서 TerserPlugin을 사용해줬어용

2024-09-11 02:10 UTC, soi-ha commented on src/apis/gifAPIService.ts
> +const getTrendingFromCache = async (): Promise<GifImageModel[] | null> => {
제가 남겨주신 코멘트를 정확히 이해하고 있는지는 모르겠지만...
해당 커밋의 코드는 캐시에 데이터가 있으면 캐시 스토리지에 저장하고, 없다면 api를 요청해서 캐시 스토리지에 넣습니다.
그렇기에 말씀해주신 것 처럼 주기적으로 캐시를 갱신하지 않고 있어요...! 만약 값이 a에서 b로 바뀐다해도 b로 변경된 사항을 반영하지 못할 것입니댜...

이 부분은 코드를 작성하면서 생각하지 못했던 부분인데..! 알려줘서 고마워요 초코!!! 해당 부분은 반영하도록 하겠습니댱

2024-09-11 02:22 UTC, soi-ha commented on src/apis/gifAPIService.ts
> +const getTrendingFromCache = async (): Promise<GifImageModel[] | null> => {
[해당 코멘트 반영사항 commit](32dd81c4a1798a908b4f83b367442c0ec18bd4fe)

초코 덕분에 놓쳤던 부분을 적용할 수 있었어요! 
1시간마다 캐시를 갱신하도록 했습니다. 1시간으로 설정한 이유는 요청하는 api가 trending gif로 자주 변경될 것이라고 생각되지 않았기 때문이에요! 그래서 '분' 단위가 아닌 '1시간'으로 설정했습니댱~

꿀 같은 피드백 넘 고마워용!

2024-09-11 04:15 UTC, 00kang commented on webpack.config.js
> +  mode: isProduction ? 'production' : 'development',
오호 고마워용

2024-09-11 04:24 UTC, 00kang commented
소하~~ 미션 하느라 수고했어요 :)
merge하도록 하겠습니다~ 
레벨4 바쁘겠지만 앞으로 미션도 화이팅!!

2024-09-11 04:24 UTC, merged