[개인 미션 - 성능 오답노트] 쑤쑤(현수연) 미션 제출합니다.
woowacourse/perf-basecamp pull request #133
Opened 2024-09-08 19:31 UTC by soosoo22

# To. 마이 씨스터 웨디
안녕하세요! 웨디! 
너무나 좋아하고 존경하는 웨디가 저의 코드를 리뷰해 주신다니 너무 영광입니다😊
우테코 첫 개강날 기억 나시나요...? 그때 제 옆에 앉으셨잖아요. 우테코 와서 처음으로 대화 나눈 크루가 웨디였어요~

**박**수가 절로 나오더라고요. 너무 예뻐서....
**세**심하면서 은근히 유머러스함까지 겸비한
**현**명한 웨디! 리뷰 잘 부탁드립니다❤️

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://dashnhnnoks6c.cloudfront.net/
- 개선 전후 성능 측정 결과

| | Lighthouse | WebPageTest |
|----------|----------|----------|
| [개선 전 (GitHub Pages)](https://soosoo22.github.io/perf-basecamp/)| <img width="637" alt="스크린샷 2024-09-09 오전 12 56 46" src="https://github.com/user-attachments/assets/7db39330-8d80-49e6-942a-fb984b8d1225"> | ![스크린샷 2024-09-04 오전 12 34 10](https://github.com/user-attachments/assets/3404dddf-79f1-4584-b8c9-f9532688b580) |
| [개선 후 (CloudFront)](https://dashnhnnoks6c.cloudfront.net/) | <img width="634" alt="스크린샷 2024-09-09 오전 12 54 15" src="https://github.com/user-attachments/assets/938279e2-1205-414a-b7f7-21f0b93cb59e"> | <img width="1379" alt="스크린샷 2024-09-09 오전 12 54 47" src="https://github.com/user-attachments/assets/48983011-34f0-48f2-a7a0-1081bbbf3e32">|
 

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [X] 소스코드 크기 줄이기
- js 파일 최적화 => Webpack5 부터 기본적으로 TerserPlugin이 제공돼서 production 모드로 빌드하게 되면 자동으로 minify(압축), uglify(난독)를 진행합니다. 참고로 minimize 옵션을 true로 변경해주었다가 디폴트값이 true인 것을 알고 지웠습니다!
- css 파일 최적화 => 불필요한 공백을 제거해주는 CssMinimizerPlugin, css를 별개의 파일로 분리해주는 MiniCssExtractPlugin을 활용했습니다.
찾아보니 MiniCssExtractPlugin과 style-loader가 겹친다고 하네요! 현재 미션에서는 lazy를 이용한 코드 스플리팅으로 페이지마다 번들을 생성하고, 그에 맞게 css도 분리해서 필요한 것만 불러오는게 좀 더 효율적인 것 같습니다. 그래서 style-loader는 제거했습니다!
```js
// webpack.config.js
 rules: [
    // ...
    {
      test: /\.css$/i,
      use: [MiniCssExtractPlugin.loader, 'css-loader']
    }, 
    // ...
  ]
```
<img width="325" alt="스크린샷 2024-09-09 오전 1 32 00" src="https://github.com/user-attachments/assets/c61ff503-d2ee-46c7-9e92-258db477ce42">

- [x] 이미지 크기 줄이기

일단, 인터넷에서 흔히 사용 가능한 파일 변환기를 활용했습니다. 이미지와 gif 파일이 몇 개 없기도 하고, 코드를 추가해서 ImageMinimizerPlugin을 사용하는 것보다 인터넷 도구를 사용하는 것이 더 간편하다고 느꼈습니다. 그리고 webp는 png나 jpg에 비해 화질이 크게 떨어지지 않으면서도 파일 크기를 20-30% 정도 더 줄일 수 있다고 하네요! [WebP 설명](https://developers.google.com/speed/webp?hl=ko)
- [convertio](https://convertio.co/kr/)를 사용해서 png를 jpg로 변환했습니다.
<img width="667" alt="스크린샷 2024-09-09 오전 2 06 00" src="https://github.com/user-attachments/assets/278aeb60-68a5-4301-adf4-6c364ececc76">

- [Squoosh](https://squoosh.app/)를 사용해서 jpg 파일을 webp로 변환하고, 사이즈를 1440 x 961로 조정하고 품질을 60으로 설정했습니다. 사이즈와 품질을 조정한 이유는 `히어로 이미지 크기 < 120kb` 성능 수치를 맞추기 위해서 입니다.
<img width="645" alt="스크린샷 2024-09-09 오전 2 09 09" src="https://github.com/user-attachments/assets/41fd7871-9af8-4244-ac7c-1fd78e2ef20e">

- [convertio](https://convertio.co/kr/)를 사용해서 gif를 mp4로 변환했고, video 태그를 활용해서 보여줬습니다.
<img width="667" alt="스크린샷 2024-09-09 오전 2 22 57" src="https://github.com/user-attachments/assets/830223d0-06e3-4375-8717-6c3edcdc9ad4">

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
   - lazy, suspense 사용
      - 라우트별로 lazy를 적용해서 Home 페이지에 접속했을 때, Search 페이지 코드가 로드되지 않도록 했습니다. 이렇게 하면 필요한 코드만 로드되니까 로딩 시간을 줄일 수 있습니다.

- [x] 아이콘 패키지 Tree Shaking
  - 기존에 react-icons/ai처럼 모든 아이콘을 불러오는 것이 아닌 react-icons/all-files를 사용해서 필요한 아이콘만 불러오도록 수정했습니다. 아무래도 필요한 아이콘만 불러오는게 효율적이겠죠🤔

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 / S3 메타데이터 설정 (설정값, 해당 값을 설정한 이유 포함)
  - 추후 작성...
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
   - cache 객체를 사용해서 처음 페이지 로딩 시에만 API에서 트렌딩 GIF 데이터를 가져오고, 이후 Search 페이지에 재접속할 때는 캐시된 데이터를 활용해 불필요한 API 호출을 방지하도록 했습니다.
```tsx
// useGifSearch.tsx
const cache: { trendingGifList: GifImageModel[] | null } = { trendingGifList: null };

// ...
  useEffect(() => {
    const fetchTrending = async () => {
      if (status !== SEARCH_STATUS.BEFORE_SEARCH) return;

      if (cache.trendingGifList) {
        setGifList(cache.trendingGifList);
        return;
      }

      try {
        const gifs = await gifAPIService.getTrending();
        cache.trendingGifList = gifs;
        setGifList(gifs);
      } catch (error) {
        handleError(error);
      }
    };

    fetchTrending();
  }, []);

```

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
   - GifItem 컴포넌트에 React.memo() 적용
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
   - `transform: translate3d()`를 사용해서 Layout Shift 없이 애니메이션을 적용했습니다. transform을 적용하면 요소는 새로운 쌓임 맥락을 형성하고, 이 쌓임 맥락 내에서만 다른 요소와 상호작용합니다. 즉, 페이지 전체 레이아웃에는 영향을 주지 않고, 다른 요소에 영향을 주지 않아 reflow가 발생하지 않습니다.
   - 혹시 [쌓임 맥락](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context)에 대해 궁금하신가요? [쑤쑤의 z-index의 동작 방식](https://youtu.be/ln9vfw-JAr8)을 보고 오시길 바랍니다^^
```tsx
  // CustomCursor
  cursorRef.current.style.transform = `translate3d(${mousePosition.pageX}px, ${mousePosition.pageY}px, 0)`; 
```
```css
  // hover
  .gifItem:hover {
    transform: translateY(-0.75rem);
  }

  // 도움말 패널 열고 닫기 애니메이션
  .selectedItemContainer.showSheet {
    transform: translateX(-320px);
    opacity: 1;
   }
```
       
- [ ] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.
  - // 추후 작성

## 🧐 공유

https://victor-log.vercel.app/post/js-file-minimize-with-webpack-mode-optimization-devtool/

## 질문
추후 작성

2024-09-11 14:15 UTC, pakxe requested changes
안녕하세요 쑤쑤! 이렇게 만나게 되어 정말 좋네요. 삼행시도 감사합니다 ㅋㅋㅋㅋ

감사한 마음을 담아 저도 쑤쑤에게 삼행시로 보답해보려고 합니다.

**한**사람만 내 눈에 비친다.
**수**연... 그녀의 취향이
**연**하였으면 좋겠다...

프로젝트와 함께 미션하시느라 고생 많으셨습니다. 세세한 디테일이 많이 보였어요.
특히나 문제를 해결한 방법을 상세히 적어주셔서 저도 도움을 많이 받았습니다. 

대부분의 요구 사항을 모두 반영해주시느라 수고하셨어요. 모두 적절히 해결해주신 것 같습니다!

다만 Frame drop을 막는 요구 사항을 좀 더 고민해보시면 좋을 것 같습니다. 
partially presented frame이 발생하고 있는 부분(노란색으로 표시되는 Frames 행 영역)의 아래에 함께 뜨는 다양한 분석 결과를 보시면 단서를 얻을 수 있을 것 같은데요.

<img width="921" alt="image" src="https://github.com/user-attachments/assets/8368a062-5089-406c-bb44-4af05e0027ee">


커서 움직임이 없을 때와 활발할 떄의 Main 행 영역을 보시면 활발할 때 더 많은 일이 나타나고 있는 것을 알 수 있죠. 해당 영역에 커서를 올려 어떤 이벤트들이 실행되고 있나 확인해보면 노란 색의 Mouse관련된 이벤트들이 자주 감지되었을 떄 partially presented frame도 함께 발생하고 있는 것 같아요. 
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/a3e289d9-76d4-4fe9-8707-559844a52583">
노란 영역이 길고 많이 발생해 partially presented frame이 지속되는 거라면 이 노란 영역이 지금보다 덜 발생하도록 하면 요구 사항을 모두 만족할 수 있을 것 같은데요. 잠깐 생각해보자면 마우스 관련된 이벤트를 덜 발생시키는 방법이 가능할 것 같습니다.

> 첫 번째 방식은 NavBar와 Footer가 먼저 로드된 후, Suspense로 감싼 Home 페이지가 나중에 로드돼요. 이 과정에서 NavBar와 Footer가 붙었다 떼어지니까 페이지의 레이아웃이 변동되면서 Layout Shift가 발생하게 돼요. 두 번째 방식은 Suspense로 Router 전체를 감싸면 NavBar, Footer, Home이 동시에 로드되어서 레이아웃 변동 없이 한 번에 렌더링돼요. 그래서 점수가 높게 나왔던 거예요🤯

문제 원인을 스스로 파악하고 해결까지 하셨군요! 서스펜스의 위치를 바꿔가며 라이트하우스를 돌라고 비교하셨을 것 같은데 이것저것 실험해보는 모습이 멋집니다. 쑤쑤를 리뷰하면서 레이아웃 쉬프트에 대하여 더 알게된 것 같아요. 로딩 펄백에 화면 전체를 차지하도록 크기를 주는 방법을 쿠키에게 전해들었는데요. 쿠키에게 이 방법을 어떻게 생각하게 된거냐 물어보니 쑤쑤가 알려주었다고 하더라구요. 덕분에 저도 사용했었습니다 ㅎ.ㅎ 그때 사용할 때는 '이거 하면 레이아웃 쉬프트가 없다니 그냥 써야겠네'라고 생각하며 사용했는데요. 이렇게 해야했던 이유를 들으니 더 기억에 오래남을 것 같아요. 

고생많으셨습니다. 성능 개선에 대한 좋은 경험치를 쌓으셨길 바래요 ☺️

2024-09-11 14:15 UTC, pakxe commented on index.html
> +      onload="this.onload=null; this.rel='stylesheet'"
이 부분에 대한 설명이 pr 메세지에 상세히 적혀있어서 이해가 잘 되었어요. 감사합니다.

2024-09-11 14:15 UTC, pakxe commented on src/pages/Home/components/CustomCursor/CustomCursor.tsx
> +      cursorRef.current.style.transform = `translate3d(${mousePosition.pageX}px, ${mousePosition.pageY}px, 0)`;
쑤쑤의 pr안에 레이아웃 쉬프트를 피하기 위해 transform을 사용했다고 적혀있었는데요! 알쓸신잡으로 한 가지 알려드리고 싶어욧.

transform이 새로운 쌓임 맥락에서 계산되는 이유는, 이 트랜스폼 연산이 다른 css에 비해 복잡한 연산이 필요하기 때문입니다. 따라서 레이아웃 단계가 딜레이되지 않도록 렌더 트리에서 분리된 것이라고 합니다. transform말고도 다양한 속성이 분리되어 계산됩니다.

```
transform
clip
effect(blur, filter, opacity 등)
scroll
etc...
```

혹시 브라우저 렌더링 파이프라인에 대해 궁금하신가요? [빡세의 브라우저 렌더링 파이프라인](https://velog.io/@pakxe/Browser-rendering-pipeline)을 보고 오시길 바랍니다^^

2024-09-11 14:15 UTC, pakxe commented on src/pages/Home/Home.tsx
> +        <picture>
srcSet에 width와 그 width일 때 보여줄 이미지를  명시해 이미지를 브라우저 크기에 따라 다르게 로드할 수 있다고 알고 있었는데요. 이런 방식으로도 구현할 수 있군요. srcSet에 문자열을 길게 쓰는 것보다 가독성이 좋다고 느껴집니다!

2024-09-11 14:15 UTC, pakxe commented on src/pages/Search/components/GifItem/GifItem.tsx
> +export default memo(GifItem);
오? 이렇게 export 에서 memo를 써도 되는군요. 처음알았습니다. 정말 대단한 쑤쑤

2024-09-11 14:15 UTC, pakxe commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(-320px);
이건 혹시 왜 -320px로 바뀐건가요?

2024-09-11 14:15 UTC, pakxe commented on webpack.config.js
> +    filename: '[name].[contenthash].bundle.js',
번들 이름도 신경써주셨네요.

2024-09-11 14:15 UTC, pakxe commented on src/App.tsx
> +    <Router>
basename을 지우는 것이 어떤 의미인가요?

2024-09-11 14:15 UTC, pakxe commented on src/App.tsx
> +      <Suspense fallback={<div style={{ width: '100vw', height: '100vh' }}>Loading...</div>}>
네비게이션과 푸터가 붙었다 떨어져서 레이아웃 쉬프트가 일어난거군요...! 👍 원인을 몰랐는데 쑤쑤정말 대박

2024-09-12 18:52 UTC, soosoo22 commented on src/pages/Home/components/CustomCursor/CustomCursor.tsx
> +      cursorRef.current.style.transform = `translate3d(${mousePosition.pageX}px, ${mousePosition.pageY}px, 0)`;
transform이 쌓임 맥락을 형성한다고는 알고 있었는데 딥~한 부분까지는 모르고 있었어요! transform은 복잡한 연산을 필요로 해서 페이지 레이아웃 단계와 분리되어 별도로 처리된다는 얘기군요! 고맙습니다! 웨디!

![스크린샷 2024-09-13 오전 3 35 57](https://github.com/user-attachments/assets/8ddf6ca3-ddeb-42aa-8d6d-026665fdf85c)

2024-09-12 23:18 UTC, soosoo22 commented on src/pages/Home/Home.tsx
> +        <picture>
저는 오히려 웨디가 말한 srcSet에 width를 명시해줘서 브라우저 크기에 따라 다르게 보여주는 방식을 모르고 있었어요. 이번에 실제 리뷰미 서비스에 이미지 최적화하는 과정에서 처음 알았어요. 같이 적절하게 사용하면 좋을 것 같네요👍

2024-09-12 23:26 UTC, soosoo22 commented on src/pages/Home/components/CustomCursor/CustomCursor.tsx
> +      cursorRef.current.style.transform = `translate3d(${mousePosition.pageX}px, ${mousePosition.pageY}px, 0)`;
빡세의 브라우저 렌더링 파이프라인....야무지네요😉

2024-09-13 00:18 UTC, soosoo22 commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform: translateX(-320px);
selectedItemContainer가 right: -320px로 적용이 되어 있어서 오른쪽 범위를 넘어가니 다시 왼쪽으로 같은 px만큼 옮겨서 오른쪽 벽에 붙도록 했어요.

```css
.selectedItemContainer {
  position: fixed;
  right: -320px;
  top: 0;
  width: 320px;
  height: 100%;
  z-index: 10;
  background: rgba(255, 255, 255, 0.9);
  box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
  backdrop-filter: blur(5px);
  -webkit-backdrop-filter: blur(5px);
  opacity: 0;
  transition: 0.5s all cubic-bezier(0.82, 0.085, 0.395, 0.895);
}
```

2024-09-13 00:36 UTC, soosoo22 commented on webpack.config.js
> +    filename: '[name].[contenthash].bundle.js',
[name] 을 추가하게 되면 번들 이름을 구분할 수 있어서 좋고, [contenthash]는 파일 내용이 변경될때마다 새로운 해시 값을 생성해줘서 캐시를 무효화 시켜줘요. 캐싱 측면에서 효율적인 것 같네요😊

2024-09-13 00:43 UTC, soosoo22 commented on src/App.tsx
> +    <Router>
basename을 붙이게 되면 로컬에서 접근할 때, `http://localhost:8080/perf-basecamp` 이런 식으로 접근을 해야 하니까 일단 지웠습니다!

2024-09-13 00:51 UTC, soosoo22 commented on src/App.tsx
> +      <Suspense fallback={<div style={{ width: '100vw', height: '100vh' }}>Loading...</div>}>
도움이 된 것 같아서 뿌듯하네요~^,^

2024-09-13 04:52 UTC, soosoo22 reviewed
안녕하세요! 웨디!

Frame Drop 관련해서 세세하게 알려주셔서 감사해요! 도움이 많이 되었습니다! 웨디의 설명 덕에 힌트를 얻을 수 있었어요. 리뷰어, 리뷰이로써 있으면서 코드 리뷰란 활동이 정말 의미있는 활동인 것 같다는 생각이 드네요!!

웨디가 저의 코드를 리뷰해주셔서 너무 영광이었습니다😉

2024-09-13 04:52 UTC, soosoo22 commented on src/pages/Home/hooks/useScrollEvent.tsx
>    }, [onScroll]);
requestAnimationFrame을 활용해 봤는데요. 효과가 미미하네요..😅
<img width="696" alt="스크린샷 2024-09-13 오후 1 41 41" src="https://github.com/user-attachments/assets/6f9f22a3-27c1-4674-846f-e3eda861bbb7">

2024-09-13 06:06 UTC, pakxe commented on src/pages/Home/hooks/useScrollEvent.tsx
>    }, [onScroll]);
저걸로도 안되면 저희가 강제로 스로틀링을 흉내내는 것이 필요한걸까요.. 저도 방법을 고민해볼게요

2024-09-13 06:07 UTC, pakxe commented
요구사항 만족하시느라 고생 많았습니다! 어뿌루뿌~~~!!

2024-09-13 06:07 UTC, merged