[개인 미션 - 성능 오답노트] 파슬리(김윤아) 미션 제출합니다.
woowacourse/perf-basecamp pull request #139
Opened 2024-09-09 06:52 UTC by anttiey

안녕하세요, 마루! 👍 이렇게 코드 리뷰를 받게 되어 영광입니다... 제가 성능을 개선해 보는 게 처음인 관계로 부족한 부분이 정말 많은 상태인데 날카로운 쓴소리 많이 부탁드릴게요 🌱

## 🔥 결과

- 배포한 CloudFront 접근 경로: [링크](https://d342bfygyo91m3.cloudfront.net)
- 개선 전후 성능 측정 결과

> 프랑스 파리에서 `WebPageTest` 가 실행되지 않는 관계로 네덜란드 암스테르담에서 성능을 측정했습니다 ✈️

| 개선 전 | 개선 후 |
|---------|---------|
| <img width="847" alt="스크린샷 2024-09-09 오후 1 41 43" src="https://github.com/user-attachments/assets/24b86072-e8aa-4958-88b2-075f65f1099d"> | <img width="842" alt="스크린샷 2024-09-09 오후 1 42 29" src="https://github.com/user-attachments/assets/d6a0604d-038d-4939-a13c-8210203e2c86"> |
| <img width="1439" alt="스크린샷 2024-09-09 오후 2 37 28" src="https://github.com/user-attachments/assets/91acd0ee-c57b-4753-b02e-bfdddff16dcc"> | <img width="1446" alt="스크린샷 2024-09-09 오후 2 19 33" src="https://github.com/user-attachments/assets/1e228583-ca12-4e3a-b4c2-87331936be77"> |

## ✅ 개선 작업 목록

### 1. 요청 크기 줄이기

- [x] 소스코드 크기 줄이기

| 개선 전 (253kB) | 개선 후 (58.7kB) |
|---------|---------|
| <img width="723" alt="스크린샷 2024-09-09 오후 1 50 56" src="https://github.com/user-attachments/assets/1ae47fad-7401-422d-8c02-f91527edf91e"> | <img width="721" alt="스크린샷 2024-09-09 오후 1 51 15" src="https://github.com/user-attachments/assets/be8a3732-1f67-4ad5-8412-c500efedbb5c"> |

- `webpack.config.js` 의 `optimization` 이 작동되도록 설정했습니다.
- `MiniCssExtractPlugin` 으로 CSS 파일을 분리하고 `CssMinimizerPlugin` 으로 최적화했습니다.
- `CloudFront` 의 `자동으로 객체 압축` 정책을 설정했습니다.
<br />

- [x] 이미지 크기 줄이기

| 개선 전 (10.7MB) | 개선 후 (92.5kB) |
|---------|---------|
| <img width="721" alt="스크린샷 2024-09-09 오후 1 53 50" src="https://github.com/user-attachments/assets/9e7fbb04-3dfa-4d0b-ad1b-6aa72536faa8"> | <img width="721" alt="스크린샷 2024-09-09 오후 1 54 17" src="https://github.com/user-attachments/assets/e5e82e77-e694-46fe-b5b1-c8ce175dcd6e"> |

- 이미지 파일 포맷을 `webp` 와 `jpg` 로 변경하고 `webp` 를 지원하는 브라우저에서는 `webp` 파일을, 이외의 브라우저에서는 `jpg` 파일을 사용하도록 설정했습니다. (두 파일 모두 크기가 120kB 이하가 되도록 조정했습니다)
- 이미지 파일 크기를 `webp` 파일의 경우 `1440px` 으로, `jpg` 파일의 경우 `1350px` 으로 줄였습니다.
- `ImageMinimizerPlugin` 으로 이미지 파일 품질을 절반으로 최적화했습니다.
<br />

### 2. 필요한 것만 요청하기

- [x] 페이지별 리소스 분리

| Home | Search |
|---------|---------|
| <img width="721" alt="스크린샷 2024-09-09 오후 2 01 20" src="https://github.com/user-attachments/assets/bb43529d-55d5-4b69-94af-a16e08e7902d"> | <img width="721" alt="스크린샷 2024-09-09 오후 2 01 36" src="https://github.com/user-attachments/assets/b6684519-ae6f-4885-b601-a17f7d817d40"> |

- 코드 스플리팅을 통해 페이지 별 리소스를 분리하여 각각의 페이지에서 필요한 리소스만 불러올 수 있도록 설정했습니다. 위의 이미지에서 `Search` 페이지에 들어가서야 비로소 `Search` 페이지에 필요한 리소스를 불러오는 걸 확인할 수 있습니다.
- `React.lazy()` 를 사용해 동적 import를 적용하고, 컴포넌트를 지연 로드하도록 설정했습니다.
<br />

- [x] 아이콘 패키지 Tree Shaking

<img width="1462" alt="스크린샷 2024-09-09 오후 2 05 20" src="https://github.com/user-attachments/assets/c9428799-05c3-4ca5-9104-27d18bd13699">
<br />
<br />

- 기존에 설치되었던 `react-icons` 라이브러리를 제거하고 `@react-icons/all-files` 라이브러리를 설치하여 필요한 아이콘 파일만 불러오도록 변경했습니다. 위의 이미지에서 프로젝트 내에서 사용하는 3개의 아이콘만 빌드 파일 안에 포함된 것을 확인할 수 있습니다.

### 3. 같은 건 매번 새로 요청하지 않기

- [x] CloudFront 캐시 설정 / S3 메타데이터 설정 (설정값, 해당 값을 설정한 이유 포함)

| CloudFront | S3 |
|---------|---------|
| <img width="767" alt="스크린샷 2024-09-09 오후 3 07 02" src="https://github.com/user-attachments/assets/295acf1c-8d3d-4bd4-b499-bc8425d85a93"> | <img width="789" alt="스크린샷 2024-09-09 오후 3 02 24" src="https://github.com/user-attachments/assets/954000e9-1b71-4455-b64b-a96a7ed8372e"><br /><img width="728" alt="스크린샷 2024-09-09 오후 3 26 54" src="https://github.com/user-attachments/assets/d4a83fd2-5a52-4d62-9148-9c4c708e5b6f"> |

- `CloudFront` 캐시는 기본 설정을 따르도록 했습니다.
- `index.html` 을 제외한 정적 자원들의 경우 `[contenthash]` 를 통해 빌드 시 자원 이름이 달라지고 있어 `Cache-Control` 값을 1년으로 길게 설정했습니다.
- `index.html` 의 경우 리소스 로딩의 진입점이므로, `Cache-Control` 값을 1일로 짧게 설정했습니다.
<br />

- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

<img width="750" alt="스크린샷 2024-09-09 오후 2 24 59" src="https://github.com/user-attachments/assets/7c6d9983-9c89-4a2b-866c-cce2adb54e90">
<br />
<br />

- `sessionStorage` 를 사용해 `trending API` 로 요청한 데이터를 저장하고 같은 세션 안에서는 데이터를 새로 요청하지 않도록 설정했습니다.
- 실시간으로 데이터가 업데이트될 필요는 없지만, 사용자가 새로운 세션에 접속했을 때는 `trending API` 가 최신화되어야 한다고 생각되어 세션 종료 시 데이터가 무효화되는 `sessionStorage` 를 사용했습니다.

### 4. 최소한의 변경만 일으키기

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.

| 개선 전 | 개선 후 |
|---------|---------|
| ![image](https://github.com/user-attachments/assets/57183e50-29ff-447f-9c81-c79c513c4e7b) | ![image](https://github.com/user-attachments/assets/36a27ec8-1be9-479e-a8ba-b377055d1cc3) |

- `React.memo` 를 사용해 `GifItem` 컴포넌트를 메모이제이션하여 추가된 목록만 새로 렌더되도록 설정했습니다.
<br />

- [x] Layout Shift 없이 애니메이션이 일어나야 한다.

| 개선 전 | 개선 후 |
|---------|---------|
| <img width="654" alt="스크린샷 2024-09-09 오후 2 38 58" src="https://github.com/user-attachments/assets/85047602-d715-4af5-8b77-73b70307d2c7"> | <img width="629" alt="스크린샷 2024-09-09 오후 2 39 32" src="https://github.com/user-attachments/assets/ee94d9a9-c430-41dd-96ab-8820d93ef003"> |

- `CustomCursor` 에서 커서 위치에 따라 요소 위치를 조절하는 코드를 `transform` 을 통해 수행하도록 변경했습니다.
- `GifItem` 에서 hover 시 요소 위치를 조절하는 코드를 `transform` 을 통해 수행하도록 변경했습니다.
<br />

- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

![image](https://github.com/user-attachments/assets/6ae01fbc-cf13-44e6-8324-79cb8b13d19d)
<br />
<br />

- 스크롤 이벤트에서 간헐적으로 프레임 드랍 현상이 발생하는 모습을 확인할 수 있었습니다.
- 스크롤 이벤트에 `requestAnimationFrame` 을 적용해 브라우저의 리페인트 주기에 맞게 콜백 함수를 실행하여 프레임 드랍 현상을 개선했습니다.

## 🧐 공유

- `Home` 페이지에서 불러오는 `gif` 파일의 용량이 대부분 1.5MB를 넘어가서 `mp4` 로 파일 확장자를 변경한 후 `muted autoPlay loop` 설정으로 반복 실행되도록 변경했습니다. 각 이미지마다 대략 80% 정도의 파일 크기가 줄어든 것을 확인할 수 있었어요.
- 생각보다 웹팩 설정으로 최적화할 수 있는 요소들이 많아서 놀랐어요. 이번 미션에서 적용하지는 않았지만 이미지 크기를 리사이징할 수 있는 옵션도 있더라고요. 무작정 남을 따라하는 것이 아닌, 웹팩을 어떻게 하면 더 잘 사용할 수 있을지 고민해 보는 시간이 필요하다고 생각했어요.

2024-09-10 09:05 UTC, rbgksqkr reviewed
안녕하세요 파슬리~! 꼼꼼한 코드 잘 봤습니다 😁
비슷한 부분이 많아서 코드를 이해하기 쉬웠어요!!! preload 폰트 관련해서 몇가지 코멘트 남겨봤습니다 확인 부탁드려요:)

2024-09-10 09:05 UTC, rbgksqkr commented on index.html
> +    <meta name="description" content="Memegle - Search and find the best GIFs for your moments." />
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
와우 SEO 까지 챙겼네요 굿굿

2024-09-10 09:05 UTC, rbgksqkr commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
폰트에 preload도 적용하셨군요! 그런데 같은 폰트를 불러오는데 태그를 분리해서 작성해야 하는 건가요?? (단순 궁금)

2024-09-10 09:05 UTC, rbgksqkr commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
# 🙏 제안 🙏
<!-- ex) 이렇게 바꿔보는 건 어떨까요? 이렇게 해보는 것도 좋은 것 같아요! -->
preload가 제대로 동작하지 않는 것 같아요!
저도 잘 몰라서 작년 레포를 찾아봤는데 preload가 적용되면 폰트가 모두 다운받아진 후 자바스크립트 파일을 다운받는 것 같아요!  `@vue/preload-webpack-plugin` 를 사용하는 것 같더라구요 참고 자료 첨부합니다:)

현재 상황

<img width="400" alt="image" src="https://github.com/user-attachments/assets/5073abab-6bbb-44f0-ba94-0c88619d2474">

preload 적용 시

<img width="400" alt="image" src="https://github.com/user-attachments/assets/28a595af-2b6d-4e84-8cbd-bdc1b3220bee">

2024-09-10 09:05 UTC, rbgksqkr commented on src/apis/gifAPIService.ts
> +    const cachedData = sessionStorage.getItem(cacheKey);
# 🌸 칭찬 🌸
<!-- ex) 천재 만재 썬데이. 레전드 훅 분리 미쳤다 ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ -->
오호 sessionStorage로 캐시 데이터를 관리하셨군요! PR에 작성된대로 새로고침 시 트렌딩을 보게 하는 것도 좋은 의도인 것 같네용

2024-09-10 09:05 UTC, rbgksqkr commented on src/pages/Home/hooks/useScrollEvent.tsx
> +      animationFrameRef.current = requestAnimationFrame(() => {
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
와우 requestAnimationFrame으로 최적화하는 경험을 하셨네요 ㄷ ㄷ 저도 적용해보고 싶었는데 저는 오히려 frame drop이 더 생기더라구요 혹시 원리를 설명해주실 수 있나요??
조사한 바로는 한 프레임을 그릴 때 16.6ms 를 초과하는 작업을 다음 프레임에 넘긴다고 이해했는데, 스크롤 함수 실행을 넘기는 건가요? 원리가 궁금하네욥 

별개로 `requestAnimationFrame(onScroll)` 와 지금 형태와는 다르게 동작하는지도 궁금합니다! (단순 궁금)

2024-09-10 09:05 UTC, rbgksqkr commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" fetchPriority="high" />
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
webp를 지원하지 않는 이미지에 jpg 이미지를 보여주도록 설정하셨는데, fallback image에 fetchPriority="high" 를 설정한 이유가 궁금합니다!

2024-09-10 09:05 UTC, rbgksqkr commented on webpack.config.js
> +              jpeg: {
# 💭 질문 💭
<!-- ex) 이건 어떤 기능인가요? 이 속성을 넣은 이유는 무엇인가요? -->
png 대신 jpg를 선택해주셨군요! jpg를 설정한 이유도 궁금합니다!

2024-09-10 09:06 UTC, rbgksqkr requested changes
안녕하세요 파슬리~! 꼼꼼한 코드 잘 봤습니다 😁
비슷한 부분이 많아서 코드를 이해하기 쉬웠어요!!! preload 폰트 관련해서 몇가지 코멘트 남겨봤습니다 확인 부탁드려요:)

2024-09-10 16:28 UTC, rbgksqkr commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
엇 제가 다시 조사해보니 로컬폰트만 아래 형태가 가능한 것 같아요ㅜ 그렇다면 코멘트를 바꿔 웹폰트를 사용하면 폰트 깜빡임이 일어날 수밖에 없는건지 궁금합니다!

2024-09-12 06:39 UTC, anttiey commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" fetchPriority="high" />
위와 같이 `<picture>` 태그와 `<source>` 태그로 이미지를 제어하게 되면 `<img>` 태그의 fetchPriority 속성이  `<source>` 태그의 이미지에도 적용되기 때문입니다!

fetchPriority 속성은 `<img>` 태그에만 적용 가능한 속성이므로, fetchPriority="high" 설정을 `<img>` 태그에 추가하게 되면 WebP 포맷을 지원하는 브라우저에서는 해당 우선순위가 WebP 이미지에 적용됩니다 ☺️

> fetchPriority="high" 가 없을 때

<img width="534" alt="스크린샷 2024-09-12 오전 11 36 36" src="https://github.com/user-attachments/assets/ca4bbbf8-79aa-474b-bc0f-29e931c76a0f">

> fetchPriority="high" 가 있을 때

<img width="534" alt="스크린샷 2024-09-12 오전 11 36 49" src="https://github.com/user-attachments/assets/be6b874c-9859-45c0-8047-d98e9a8af2d6">

2024-09-12 06:39 UTC, anttiey commented on webpack.config.js
> +              jpeg: {
PNG는 `무손실 압축` 을 사용하기 때문에 이미지의 파일 크기가 크게 나오는 경우가 많은데, JPG는 `손실 압축` 을 지원하기 때문에 이미지의 품질을 어느 정도 희생하면서 파일 크기를 크게 줄일 수 있는 장점이 있기 때문입니다 👏 실제로 다른 처리 없이 이미지 포맷을 JPG로 바꾸기만 했는데도 파일 크기가 반 정도 줄더라고요! (10.7MB > 5.7MB)

2024-09-12 06:39 UTC, anttiey commented on src/pages/Home/hooks/useScrollEvent.tsx
> +      animationFrameRef.current = requestAnimationFrame(() => {
기존 스크롤 이벤트는 스크롤이 발생할 때마다 onScroll을 계속 호출하다 보니 빠르게 스크롤하면 프레임당 여러 번 호출되어 프레임 드롭이 생길 수 있는 가능성이 있었어요.

`requestAnimationFrame` 은 **브라우저가 다음 프레임을 렌더링하기 직전에 주어진 콜백 함수를 호출하는 방식**으로 작동하기 때문에 프레임당 한 번만 콜백을 실행하도록 제어할 수 있습니다. 즉, 스크롤 이벤트가 자주 발생하더라도 불필요한 중복 호출을 방지하여 프레임 드롭을 개선할 수 있겠다고 생각했어요. 그리고 `requestAnimationFrame` 은 일반 이벤트 핸들러와는 다른 **별도의 큐에서 작업을 처리**하기 때문에 이로 인한 지연도 감소가 되고요.

그러나 마루의 리뷰 덕분에 추가적으로 조사한 결과, 만약 콜백 함수가 복잡하여 `16.6ms` 이내에 작업이 완료되지 않으면 해당 작업이 다음 프레임을 밀어내면서 프레임 드롭이 발생할 수 있다고 하더라고요. `requestAnimationFrame` 만으로는 프레임 드롭 문제를 완벽하게 해결하기는 어렵고, 프레임 드롭이 계속 발생한다면 onScroll 함수 자체를 최적화하는 방법을 고려해 볼 것 같습니다. (현재는 프레임 드롭이 발생하지 않아서 정확히 얼마나 최적화가 되는지 판단하기가 힘드네요 🥲)

> 별개로 requestAnimationFrame(onScroll) 와 지금 형태와는 다르게 동작하는지도 궁금합니다!

기능적으로 동일하게 작동하겠네요! 단순히 onScroll 함수만을 호출하고 있으므로 위와 같이 쓰는 게 좋겠어요 👍

2024-09-12 06:39 UTC, anttiey commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
> 같은 폰트를 불러오는데 태그를 분리해서 작성해야 하는 건가요??

`<link rel="preload">` 는 폰트를 미리 로드하기 위한 태그인데 폰트만 미리 다운로드할 뿐, 실제로 브라우저가 폰트를 적용하려면 스타일시트가 필요하여 분리하게 되었습니다!

<hr />

> preload가 적용되면 폰트가 모두 다운받아진 후 자바스크립트 파일을 다운받는 것 같아요!

![image](https://github.com/user-attachments/assets/d87b8e52-d7c5-4652-b6bd-477c509be532)

일반적으로 브라우저에서는 폰트 파일과 같은 기타 리소스들을 마지막으로 불러오게 됩니다. 따라서 `preload` 로 특정 리소스를 우선적으로 다운로드하라는 지시를 브라우저에게 부여하면, 이미지와 같이 **preload 되는 리소스와 자바스크립트 파일을 병렬로 다운로드**하게 돼요.

다만, 마루의 리뷰대로 원래의 코드에는 as 속성이 적절하게 부여되지 않아서 폰트가 preload 되지 않고 있던 게 맞았어요. 따라서 as 속성을 적절하게 부여하여 아래와 같이 preload 되도록 수정했습니다.

> `preload` 적용하지 않았을 때

<img width="1155" alt="스크린샷 2024-09-12 오후 3 11 48 복사" src="https://github.com/user-attachments/assets/b47b6d53-cfe9-45a2-93f7-5fd53d333b5a">

- CSS 파일을 불러온 후 폰트 파일을 불러오는 모습을 확인할 수 있습니다.

<br />

> `preload` 적용했을 때 (현재)

<img width="1029" alt="스크린샷 2024-09-12 오후 3 12 07 복사" src="https://github.com/user-attachments/assets/d1c0ed6e-894b-4845-979c-985650b618da">

- CSS 파일과 폰트 파일을 병렬적으로 불러오는 모습을 확인할 수 있습니다.

<hr />

> 웹 폰트를 사용하면 폰트 깜빡임이 일어날 수밖에 없는건지 궁금합니다!

웹 폰트를 사용하게 되면 추가 네트워크 요청이 필요하므로 `FOIT(웹 폰트가 로드될 때까지 텍스트가 투명하게 처리되며 보이지 않다가, 로드 후 나타나는 현상)` 또는 `FOUT(웹 폰트가 로드되기 전 기본 시스템 폰트로 텍스트가 먼저 표시되고, 이후 웹 폰트로 교체되는 현상)` 현상이 필연적으로 나타날 수밖에 없을 것 같아요. 이를 해소하기 위해서는 `preload` 로 웹 폰트를 미리 가져와 그 간극을 줄이는 게 최선일 것 같고요 🤔

2024-09-12 06:50 UTC, anttiey commented
안녕하세요, 마루! 👍 정성이 담긴 리뷰 정말 감사합니다 🫡

마루 덕분에 폰트 `preload` 가 제대로 동작하지 않는 버그를 발견할 수 있었어요.

해당 부분 수정하여 다시 요청 보냅니다 🌱

2024-09-12 10:21 UTC, rbgksqkr commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
와우 ㅎㅎㅎ 코멘트를 자세하게 달아주셔서 파슬리의 생각을 한번에 이해할 수 있었어요!!

> 리소스와 자바스크립트 파일을 병렬로 다운로드하게 돼요.

다만 `병렬` 다운로드라는 말이 걸려서 코멘트 남겨봅니닷
검색했을 때 다른 블로그에도 병렬적으로 다운로드한다는 글이 많은데 폭포 탭에 마우스를 올려보면 초록색 바는 waiting이고, 파란색이 컨텐츠 다운로드더라구요! 우선순위를 높여 폰트를 먼저 다운받도록 설정하고, 로드된 나머지 리소스는 기다리는 느낌으로 이해했는데, 어떻게 생각하시나용

2024-09-12 10:27 UTC, rbgksqkr approved these changes
안녕하세요 파슬리! 원래도 개선이 잘되어 있어서 질문 위주로 남겼었는데 답변 잘해주셔서 감사합니다 ㅎㅎ 
preload 잘 반영된 것 확인했는데, 네트워크 탭에서 보니 1개는 preload가 잘 되는데, 2개의 폰트 리소스가 추가로 더 불러와지더라구요! 확인하시면 좋을 것 같고 preload 관련해서 코멘트도 하나 남겨뒀습니다!  
나머지는 잘 반영해주셔서 이만 approve 하겠습니다 4단계 앞으로도 화이팅~!~!~!~

2024-09-12 10:27 UTC, merged

2024-09-23 06:02 UTC, anttiey commented on index.html
> +      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
너무 늦게 답변을 달게 되었네요 😅

<img width="350" alt="스크린샷 2024-09-23 오후 2 57 48" src="https://github.com/user-attachments/assets/99d96519-77d4-40c8-ba22-6c80529ce09a">
<br />
<br />

저도 폭포 탭을 자세히 살펴 봤는데 초록색 바는 `서버 응답을 기다리는 중` 상태로 표시가 되더라고요! 병렬적으로 다운로드하게 된다는 게, 더 정확히 말하자면 병렬적으로 `서버로 요청이 시작된다` 라고 볼 수 있을 것 같아요. 그래서 저는 폰트가 먼저 다운로드된 후 나머지 리소스가 다운로드되는 게 아닌, 병렬적으로 서버에 요청을 보내고 서버로부터 응답이 돌아오면 콘텐츠를 다운로드한다고 이해했어요.

<img width="944" alt="스크린샷 2024-09-23 오후 3 00 01" src="https://github.com/user-attachments/assets/094f249a-253a-4a4f-8092-cf3e21c81930">
<br />
<br />

실제로 서버 응답 속도에 따라 폰트보다 스크립트가 먼저 다운로드될 때도 있더라고요 😊