[성능 베이스캠프] 심바(임선빈) 미션 제출합니다.
woowacourse/perf-basecamp pull request #17
Opened 2021-08-31 04:51 UTC by 0imbean0

## 배포한 CloudFront 접근 경로: [d3txrdsoqpzfop.cloudfront.net](d3txrdsoqpzfop.cloudfront.net)

## 🔥 결과

### Lighthouse 95점 이상
**개선 전 (S3)** 
<img width="1054" alt="스크린샷 2021-08-31 오후 12 52 24" src="https://user-images.githubusercontent.com/75007375/131441468-2c604ada-8146-49c5-b924-44529f8f807c.png"> 
**개선 후 (CloudFront)** 
<img width="1051" alt="스크린샷 2021-08-31 오후 1 21 27" src="https://user-images.githubusercontent.com/75007375/131441702-70b42178-99f7-4861-9e09-96075ba699d6.png"> 

### Home 페이지 접속했을 때
- 스크립트 리소스 크기 < 60kb 
- 히어로 이미지 크기 < 120kb

**개선 전 (S3)** 
<img width="420" alt="스크린샷 2021-08-31 오후 1 39 38" src="https://user-images.githubusercontent.com/75007375/131443296-de36f367-5920-4a2f-8e5d-c474483b1342.png">
**개선 후 (CloudFront)** 
<img width="421" alt="스크린샷 2021-08-31 오후 1 40 18" src="https://user-images.githubusercontent.com/75007375/131443268-bf03fb33-3d56-44c1-9cc1-b03594a752ca.png">

### 프랑스 파리에서 Fast 3G 환경으로 접속했을 때
- Home 첫 번째 로드시 LCP < 2.5s
- Home 두 번째 이후 로드시 LCP < 1.5s

**개선 전 (S3)** 
<img width="1084" alt="스크린샷 2021-08-31 오후 1 46 27" src="https://user-images.githubusercontent.com/75007375/131443504-0ca00691-d0c1-4c87-8617-7493c1987e27.png">
**개선 후 (CloudFront)** 
<img width="1080" alt="스크린샷 2021-08-31 오후 1 25 58" src="https://user-images.githubusercontent.com/75007375/131441860-bec25c3c-2667-46ea-ade6-b4aa49eeaffd.png">

## ✅ 개선 작업 목록
**1 요청 크기 줄이기**
- [v]  소스코드 크기 줄이기
- [v]  이미지 크기 줄이기

**2 필요한 것만 요청하기**
- [v]  페이지별 리소스 분리

**3 같은 건 매번 새로 요청하지 않기**
- [v]  CloudFront 캐시 설정
- [v]  GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**
- [v]  검색 결과 > 추가 로드시 추가된 목록만 렌더되어야 한다.
- [v]  LayoutShift 없이 hover 애니메이션이 일어나야 한다.

## 🧐 공유
/* 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 */

2021-09-01 02:58 UTC, GwangYeol-Im requested changes
변경사항 모두 확인했습니다 :) 여러 부분에서 더 꼼꼼히 봐준 것 같아 확인하면서 좀 더 알게된 부분도 몇가지 있었어요. 그래서 코멘트에 궁금한 사항 몇 개 남겨 놨습니다 ㅎㅎ

상세 코멘트에 쓰지 못한 부분은 여기에 남겨 놓을게요!
- `trendingGif` 캐시를 컴포넌트가 아닌 api 레이어에 해보는 건 어떨까요? App에서 저장하기 위해 props를 내려주고 있는데, `trendingGif`를 저장하는 것이 컴포넌트의 관심사는 아닐 수도 있다는 생각이 사뭇 드네요 ㅎㅎ 최적화 측면에서는 고치지 않아도 무방하지만 고민의 여지를 위해 제안 남겨봅니다!
- lighthouse 제안에 따라 코드 일부를 수정한 부분이 눈에 띄는데 이것은 웹 접근성을 위해서였을까요? 궁금해서 질문 남겨요!!

고생 많으셨습니다 :)

2021-09-01 02:58 UTC, GwangYeol-Im commented on webpack.config.js
> +const ImageMinimizerPlugin = require("image-minimizer-webpack-plugin");
이 세 플러그인을 썼을 때 어떤 부분의 성능 최적화를 적용할 수 있었나요?? 개인적인 경험을 먼저 말씀드리자면, 저는`CssMinimizerPlugin`을 도입해봤지만 측정 시 번들 사이즈에 딱히 차이가 없어서 다시 지우게 되었어요! 이 부분 관련해서 심바의 경험을 들어보고 싶네요! 😊

2021-09-01 02:58 UTC, GwangYeol-Im commented on webpack.config.js
>          loader: "file-loader",
저도 이번에 알게된 사실인데 webpack5부터는 `file-loader`보다 [asset modules](https://v4.webpack.js.org/loaders/file-loader/)를 더 권장한다고 해요 ㅎㅎ 미션의 요구사항은 아니었지만 공유해봅니다~!

2021-09-01 14:54 UTC, 0imbean0 commented on package.json
> +    "build:dev": "webpack --mode=development --profile",
`React Profiler`을 사용하려고 설정했어요. (저는 옵션을 빼면 사용이 안되던데, 혹시 아닌가요..? 👀)

적용 전

![image](https://user-images.githubusercontent.com/75007375/131693392-ee62906a-8911-4ba9-99e9-f8e05f33def8.png)

적용 후

![image](https://user-images.githubusercontent.com/75007375/131693802-629f359f-5eee-454e-b6bf-152ef3a88512.png)

사용 예

<img width="1431" alt="KakaoTalk_Photo_2021-09-01-23-53-22" src="https://user-images.githubusercontent.com/75007375/131693921-a673a6d2-b993-4cf4-9026-ca6714ba93eb.png">

2021-09-01 15:15 UTC, 0imbean0 commented on webpack.config.js
> +const ImageMinimizerPlugin = require("image-minimizer-webpack-plugin");
설정 없음
![image](https://user-images.githubusercontent.com/75007375/131695918-8474721f-e7a5-465d-abd9-01fc2ed6ca66.png)

`minimize: true` 적용 
![image](https://user-images.githubusercontent.com/75007375/131695800-04b49816-8f9c-4f11-87cf-7b6e0d2bba7b.png)

`MiniCssExtractPlugin` 적용
![image](https://user-images.githubusercontent.com/75007375/131695476-dcbf87d4-84e7-4dd4-9fba-c9595e6e9c4c.png)

`CssMinimizerPlugin ` 적용
![image](https://user-images.githubusercontent.com/75007375/131696476-cf33ea8e-3628-4bbd-88fc-8f7d8052ad67.png)

번들 사이즈 줄이는 방법을 찾아보면서 알게된 걸 이것 저것 시도해보면서 크게 고민하지 않았던 부분인 것 같아요.(새로운거! 적용한다!! 😂)

결론적으로 이제와서 비교해보니 `8kb -> 6kb` 로  `2kb` 정도의 차이가 있네요. 확실히 지금은 큰 차이가 아니네요.

그래도 비율로 보면 `25%` 정도의 차이가 있는데(이렇게 생각해도 되나? 🤔), 
css 사이즈가 커지면 유의미한 결과가 있지않을까 생각해볼 수 있는 시간이었습니다. 👍👍👍

2021-09-01 15:17 UTC, 0imbean0 commented on webpack.config.js
>          loader: "file-loader",
좋은 정보 감사합니다!! 😀

2021-09-01 15:39 UTC, 0imbean0 commented
> trendingGif 캐시를 컴포넌트가 아닌 api 레이어에 해보는 건 어떨까요? App에서 저장하기 위해 props를 내려주고 있는데, trendingGif를 저장하는 것이 컴포넌트의 관심사는 아닐 수도 있다는 생각이 사뭇 드네요 ㅎㅎ 최적화 측면에서는 고치지 않아도 무방하지만 고민의 여지를 위해 제안 남겨봅니다!

맞습니다. 너무 단순하게 접근했던 것 같아요. 카일 코멘트와 크루들의 코드를 보면서 다시 생각해보고 공부할 수 있었어요. 👍👍👍 c38f5be

> lighthouse 제안에 따라 코드 일부를 수정한 부분이 눈에 띄는데 이것은 웹 접근성을 위해서였을까요? 궁금해서 질문 남겨요!!

이것도 맞습니다. 쉽게 바로 적용할 수 있을 것 같아서 연습(?)이라고 생각하고 적용해 봤어요. 😀

2021-09-02 13:15 UTC, GwangYeol-Im commented on package.json
> +    "build:dev": "webpack --mode=development --profile",
오 정말 그런가 보네요..? 저는 적용 여부에 상관없이 확인할 수 있어 따로 옵션을 써주지는 않았는데 나중에 동일한 이슈가 생긴다면 적용해봐야겠네요 :) 설명 고마워요 !!

2021-09-02 13:17 UTC, GwangYeol-Im commented on webpack.config.js
> +const ImageMinimizerPlugin = require("image-minimizer-webpack-plugin");
css를 먼저 추출하고 minify를 해야만 실측정이 가능한 거였군요 :) 현재 유의미한 사이즈가 아니더라도 추후 규모가 있는 프로젝트를 다루게 될 때를 대비해서 적용을 해보는 것도 충분히 의미있는 설정이었다고 생각합니다 👍🏻

2021-09-02 13:24 UTC, GwangYeol-Im commented
cache 수정 방향도 좋고 이미지를 곁들인 설명 덕분에 이해 하는 게 정말 편했습니다 :) 웹 접근성까지 신경 썼다니 꼼꼼하시네요 👍🏻 궁금한 점도 모두 해결이 되어서 이만 리뷰 마치도록 할게요! 고생 많으셨습니다 ㅎㅎ

2021-09-02 13:24 UTC, merged