[성능 베이스캠프] 동동(김동희) 미션 제출합니다.
woowacourse/perf-basecamp pull request #3
Opened 2021-08-29 11:15 UTC by bigsaigon333

## 🔥 결과
/* 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. */

- 배포한 CloudFront 접근 경로: https://d1h6h8foqqyqno.cloudfront.net/
- 개선 전후 성능 측정 결과
    - 개선 전 (CloudFront)
![before](https://user-images.githubusercontent.com/31029000/131248117-4ea3e1b8-7232-4fd4-8baa-c8bbd1a5a058.png)
    - 개선 후 (CloudFront)
![after](https://user-images.githubusercontent.com/31029000/131248122-199c1ced-4c34-45d9-9d1e-ee20a14e4439.png)

## ✅ 개선 작업 목록
/* 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요 
   코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
*/

**1 요청 크기 줄이기**
- [x]  소스코드 크기 줄이기
  1. tree-shaking이 적용되지 않는 react-icons 패키지를 tree-shaking이 적용되는 @react-icons/all-files 패키지로 변경
  **Before**
![127 0 0 1_8888_](https://user-images.githubusercontent.com/31029000/131248313-4a74fa35-e2f8-47dc-b486-d3bc65921886.png)
  **After**

 2. CloudFront gzip
   html, js, css 파일 
 
![compress](https://user-images.githubusercontent.com/31029000/131248439-c64e923f-4711-40a8-806e-de24f8beca9a.png)

- [x]  이미지 크기 줄이기
   1. png -> webp 로 이미지 파일 형식 변경
   2. gif -> webm/mp4 비디오로 형식 변경
   3. hero.webp 반응형 이미지 적용(img요소의 `srcset`, `sizes` 속성 활용)
```
sm	640px	@media (min-width: 640px) { ... }
md	768px	@media (min-width: 768px) { ... }
lg	1024px	@media (min-width: 1024px) { ... }
xl	1280px	@media (min-width: 1280px) { ... }
2xl	1536px	@media (min-width: 1536px) { ... }
```

**2 필요한 것만 요청하기**
- [x]  페이지별 리소스 분리
  - `React.lazy`를 활용하여 Route-based 코드 스플리팅 구현

**3 같은 건 매번 새로 요청하지 않기**
- [ ]  CloudFront 캐시 설정
- [ ]  GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**
- [x]  검색 결과 > 추가 로드시 추가된 목록만 렌더되어야 한다.
  - `React.memo`를 활용하여 GifItem memoization
- [x]  LayoutShift 없이 hover 애니메이션이 일어나야 한다.
  - :hover 시 top 속성 변경 -> transform: translateY() 사용

## 🧐 공유
/* 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 */

2021-08-31 11:16 UTC, SunYoungKwon commented
> webpagetest.org 속도를 올리려면...
이론적으로 찾아보거나 한 건 아니지만,,, 그냥 느낌적인 느낌으로는
많이 테스트를 해서 파리에서 사이트로 많이 접근을 하고 && CloudFront에 올린지 시간이 좀 많이 지나면,
aws에서 파리 근처의 edge location 에 대한 최적화를 해주는건지 속도가 빨라지는 것 같습니다.
( 분명 설정은 똑같은데 나중에 해보면 속도가 확실히 잘나오는 걸 체감했습니다..)

저도 같은 설정으로 여러 번 검사를 돌려 봤을 때, 개인적으로는 나중에 한 검사가 더 잘 나오는 것은 못 느꼈지만 편차가 좀 큰 경우가 한 번씩 보이긴 하더라고요!

개인적으로 궁금한 것이 저도 첫 접속 LCP가 3s 쯤 나왔는데, 두 번째 접속은 그 절반 정도(1.6s)였어요. 올려주신 사진을 보니 첫 번째 접속과 두 번째 접속의 LCP 차이가 크네요! 여러번 검사를 해도 비슷하게 나오나요? 캐시를 적용한 영향일까요? 

---

이미지의 최대 사이즈를 `1536px`로 설정하신 이유가 있나요? 
눈으로 확인될 만큼의 이미지 품질 저하가 있네요ㅠㅠ(저도 미션을 하며 딜레마였던 부분인데, 기준 용량을 맞추면 눈에 보일 정도로 품질이 저하되고 육안으로 보기엔 유사한 정도에 맞추면 기준 용량을 초과하더라구요...)

2021-08-31 12:11 UTC, SunYoungKwon requested changes
레벨4 첫 미션 수고하셨어요! 
궁금한 부분에 대해 코멘트 남겼어요. 확인하시고 다시 리뷰요청 부탁드려요!

2021-08-31 13:59 UTC, bigsaigon333 commented on src/service/fetchGif.js
> +    mp4Url: gif.images.original.mp4,
감사합니다~~~  :+1:

2021-08-31 14:00 UTC, bigsaigon333 commented on src/utils/cache.js
> +        });
감사합니다 :+1:  하지만 `cached`를 인자로 주입할 걸이라는 후회를 하고 있습니다 ㅠㅠ

2021-08-31 14:00 UTC, bigsaigon333 commented on src/pages/Home/Home.module.css
> +  color: #fff;
이건 제가 한게 아니라 stylelint가 자동으로 해준거에욤 ㅎㅎ...

2021-08-31 14:00 UTC, bigsaigon333 commented on src/pages/Home/Home.jsx
> +          ${heroImage2Xl} 1536w
무야~~~호 :+1:

2021-08-31 14:58 UTC, bigsaigon333 commented
>  개인적으로 궁금한 것이 저도 첫 접속 LCP가 3s 쯤 나왔는데, 두 번째 접속은 그 절반 정도(1.6s)였어요. 올려주신 사진을 보니 첫 번째 접속과 두 번째 접속의 LCP 차이가 크네요! 여러번 검사를 해도 비슷하게 나오나요? 이유가 뭐라고 생각하시나요?

![s2](https://user-images.githubusercontent.com/31029000/131516822-15e2e49d-6531-4522-8168-1a217ffade17.png)
![s1](https://user-images.githubusercontent.com/31029000/131516800-6c1e1d9b-0310-4f3a-86cd-dafa4df44b65.png)

썬꺼 돌려봤는데, 브라우저 캐시 때문인거 같아요! 
css, js, webp 파일에 cache-control: max-age 설정을 안해줘서 그 부분이 브라우저 캐시가 안되어서 두번째 접속때도 네트워크를 통해 가지고 와서 시간이 걸리는거 같아요

저는  css, js, webp, png, gif 모든 S3에 올린 파일에다가 cache-control: max-age=1년 으로 설정해뒀어요!
html만 cache-control: max-age=0, s-maxage=1년으로 해뒀어요

여기 설명이 자세히 되어 있는 링크를 하나 공유드릴게요! 
https://toss.tech/article/smart-web-service-cache

---

> hero 이미지의 최대 사이즈를 1536px로 설정하신 이유가 있나요?
눈으로 확인될 만큼의 이미지 품질 저하가 있네요ㅠㅠ(저도 미션을 하며 딜레마였던 부분인데, 기준 용량을 맞추면 눈에 보일 정도로 품질이 저하되고 육안으로 보기엔 유사한 정도에 맞추면 기준 용량을 초과하더라구요...)

눈으로 확인이 되나욤..? ㅋㅋㅋ 저는 눈으로 보니 똑같은거 같아서 그냥 한건데...  ㅎㅎ 
(근데 수정하고 보니 확실히 체감되네요...)


이건 반응형 디자인 할때의 breakpoint인데, 아무 생각없이 image 리사이즈시 적용해버렸네요...
```
sm	640px	@media (min-width: 640px) { ... }
md	768px	@media (min-width: 768px) { ... }
lg	1024px	@media (min-width: 1024px) { ... }
xl	1280px	@media (min-width: 1280px) { ... }
2xl	1536px	@media (min-width: 1536px) { ... }
```


아래와 같이 변경하였습니다!
```
sm	640px	@media (max-width: 640px) { ... }
md	1280px	@media (max-width: 1280px) { ... }
lg	1920px	@media (max-width: 1920px) { ... }
```

용량을 좀 크게 가져가더라도, 해상도를 맞추어서 사용자 경험을 향상시키는게 맞는 거 같아요 :+1: (최대 170Kb)

다른 크루들은 어떻게 120Kb 맞춘건지 궁금하네요 .. 

webpageTest 결과는 나쁘지 않네요! 
![11](https://user-images.githubusercontent.com/31029000/131526157-19c04981-4afa-40c0-93a2-e9fedcc020e0.png)

2021-08-31 15:00 UTC, bigsaigon333 commented on src/utils/cache.js
> +        });
수정했습니다 헤헤

https://github.com/woowacourse/perf-basecamp/pull/3/commits/c818d27903002e9b0f0581db3b93563ef3989b55

외부에서 cache를 주입해줘야 테스트가 용이하고 나중에 localStorage 로 바꾸는 등의 변경에 유연하게 대처할 수 있을 것 같아요 :smile:

2021-09-01 15:51 UTC, SunYoungKwon approved these changes
> 여기 설명이 자세히 되어 있는 링크를 하나 공유드릴게요!
https://toss.tech/article/smart-web-service-cache

정보 공유 감사합니다!

이미지는 확실히 품질이 향상된게 보이네요. 요즘 모니터의 해상도를 생각하면 이미지가 너무 작지 않은게 좋을 것 같아요. 캐시 로직 변경한 것도👍 좀 더 여러 방향으로 사용할 수 있는 로직이 된 것 같습니다.

미션 수고하셨어요!

2021-09-01 15:51 UTC, merged