[성능 베이스캠프 미션] 코카콜라(강인태) 미션 제출합니다.
woowacourse/perf-basecamp pull request #35
Opened 2022-09-04 12:19 UTC by intae92

## 🔥 결과

/_ 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. _/

- 배포한 CloudFront 접근 경로: [https://djfmtsb7ny87d.cloudfront.net](https://djfmtsb7ny87d.cloudfront.net)
- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
![스크린샷 2022-09-01 오전 7 55 02](https://user-images.githubusercontent.com/56149367/188303859-5a034973-74da-4cee-9d0b-11b05d42a2dd.png)
![스크린샷 2022-09-01 오전 8 44 01](https://user-images.githubusercontent.com/56149367/188303891-177f829c-0832-40b5-a81e-76ce8e8eca0a.png)

  - 개선 후 (CloudFront)
![스크린샷 2022-09-04 오후 5 01 35](https://user-images.githubusercontent.com/56149367/188303879-d22277c9-96b3-4926-a513-050da47127d7.png)
![스크린샷 2022-09-04 오후 4 13 16](https://user-images.githubusercontent.com/56149367/188303901-ad354a50-8958-4039-87ef-ae9a0ed04701.png)

## ✅ 개선 작업 목록

/_ 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요
코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
_/

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
![스크린샷 2022-09-04 오후 5 04 00](https://user-images.githubusercontent.com/56149367/188304119-050270da-d243-4f81-ae9c-77f816668f08.png)

- [x] 이미지 크기 줄이기
![스크린샷 2022-09-04 오후 5 21 54](https://user-images.githubusercontent.com/56149367/188304449-66e27176-2be1-49fd-a502-e2d4969c0344.png)

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
![스크린샷 2022-09-04 오후 7 23 42](https://user-images.githubusercontent.com/56149367/188308813-e92812ef-8ddb-49ea-8216-31891ee78b1c.png)

```javascript
const Home = React.lazy(() => import('./pages/Home/Home'));
const Search = React.lazy(() => import('./pages/Search/Search'));

const App = () => {
  return (
    <Router>
      <Suspense fallback={<h1>로딩중...</h1>}>
        <NavBar />
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/search" element={<Search />} />
        </Routes>
        <Footer />
      </Suspense>
    </Router>
  );
};
export default App;
```

- [x] 아이콘 패키지 Tree Shaking
```javascript
import { AiOutlineInfo } from '@react-icons/all-files/ai/AiOutlineInfo';
import { AiOutlineClose } from '@react-icons/all-files/ai/AiOutlineClose';
```

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
![스크린샷 2022-09-04 오후 9 18 54](https://user-images.githubusercontent.com/56149367/188313094-1dd3fbb2-efbf-4767-b657-0fba6d59b866.png)

- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
```javascript
const cacheData = new Map();

export const cacheApi = async (api: string, key: string) => {
  if (cacheData.has(key)) {
    return cacheData.get(key);
  }

  await fetch(api).then((res) => cacheData.set(key, res.json()));

  return cacheData.get(key);
};
```

![화면-기록-2022-09-04-오후-7 32 55](https://user-images.githubusercontent.com/56149367/188309211-ff7029fd-1b55-46da-a5d9-71727936f953.gif)

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - React.memo 사용하여 추가된 요소만 렌더링 했습니다.
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

![스크린샷 2022-09-04 오후 7 48 51](https://user-images.githubusercontent.com/56149367/188309655-86a057e7-76fb-4323-87fa-f4ac5cb432d7.png)
![스크린샷 2022-09-04 오후 7 50 10](https://user-images.githubusercontent.com/56149367/188309679-0cf28185-1427-4028-b34d-edb725debc4a.png)

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-06 08:34 UTC, usageness requested changes
안녕하세요, 콜라! 유세지입니다 😉😉
리뷰가 좀 늦어졌네요 ㅠㅠ 죄송합니다

전반적으로 최적화도 깔끔하게 잘 진행해주시고,
다양한 방법들을 시도하고 공부하신것 같아 리뷰 드릴게 많지는 않았어요.
먼저 공유해주신 내용에 대해서 제 생각을 답변드릴게요.

---

## 1. 이미지 크기 줄이기
> 디자니어와 영상 편집자 분들의 영역이라고 생각합니다. 정해진 해상도와 시안이 있는데 이걸 개발자가 임의로 변경 시키는 건 맞지 않다고 생각합니다. 또한 많은 리소스가 있다면 배포 하는데 시간이 늘어난다는 문제점이 있습니다.

우선 저는 파일 자체를 건드리는건 그렇게 좋은 방법은 아니라고 생각해요.
콜라도 말씀하셨듯이 이 부분은 기획과 디자인의 영역이라고 생각하는데,
단순히 표시되는 이미지 크기를 조금 줄이고 퀄리티를 감소시키는 정도는 괜찮지만
그 이상으로 원본을 가공하는건 기획 의도를 자의적으로 바꾸는 느낌이 들더라구요.

처음부터 각 크기별 에셋을 받거나, 직접 수정 요청을 하는게 최선이라고 생각합니다.
만약 받아들여지지 않는다면, 엔지니어로서 어느정도 감수해야 할 조건인것 같아요.

이번 미션을 예시로 들어보면 `gif` 파일 다운로드 서비스를 만드는 입장에서
용량을 줄인다고 `mp4` 형식으로 바꿔버리면, 정작 사용자는 gif 파일을 다운받을 수 없게됩니다.
(물론 저희는 `Home`에 표시되는 gif 파일에만 적용되는 이야기지만요!)

빌드에 걸리는 시간이 늘어나는건 저도 문제라고 생각합니다.
현재까지는 가공 과정을 development 모드에서 제외하여
개발 모드의 시간을 줄이는 것 말고는 뾰족한 수가 떠오르지 않네요 😥
이건 계속 고민해봐야 할 문제인 것 같아요.

어디까지나 개인적인 생각이고, 프론트 개발자로선 콜라의 의견도 타당하다고 생각합니다 :)
참고만 부탁드릴게요!

## Source-map
> production에서 devtool: false로 설정해 source-map을 생성하지 않습니다.
실제 서비스에 소스코드가 보여지는 것은 바람직 하지 않습니다.

맞습니다. 실제 서비스에 처리되지 않은 소스코드가 그대로 노출되는건 위험하다고 생각해요.
개인적으로는 팀 프로젝트 데모데이에서도 지적받았던 내용이라 식겁했습니다.
부끄럽네요 😭

## 모든 파일에 hash 값 부여(js, css, image, mp4....)
> 변경 부분만 빌드시 변경 되는게 좋습니다. 그러면 브라우저에서 해당 부분만 따로 빠르게 변경되는 것을 알수 있습니다.
또한 예를 들어 hash를 적용하지 않는 상황에서 다음과 같은 이슈가 발생합니다.
hero의 이미지가 변경되었지만 파일명, 해상도, 규격...등 같다면 브라우저는 새로운 hero 이미지를 업로드 하지 않을 것입니다.

변경 부분만 빌드되어야 한다는 의견에 동의합니다.
더불어 이 부분은 캐시 정책을 수립할때도 함께 신경써야 할 내용인듯해요.
변경되지 않은 부분이 S3에 함께 업로드 되어 eTag가 변하면
사용자가 같은 파일을 새로 다운받는 불상사가 생길지도 모르는 일입니다 😥

---

대체로 콜라가 고민하셨던 내용들이 저도 고민했던 부분들이라 많이 공감이 됩니다.
자세한 내용은 코멘트로 남겨두었으니 참고해주세요!

2022-09-06 08:34 UTC, usageness commented on src/pages/Search/components/HelpPanel/HelpPanel.tsx
> +import { AiOutlineClose } from '@react-icons/all-files/ai/AiOutlineClose';
라이브러리 교체 좋습니다! 👍

2022-09-06 08:34 UTC, usageness commented on webpack.config.js
> +          name: 'static/[name].[contenthash:8].[ext]'
웹팩 5버젼부터 `file-loader`가 내장으로 바뀌어서 `asset/resource`으로 대체할 수 있어요!
아마 이렇게 바꾸면 작동할 것 같아요 (아니라면 죄송합니다)

```js
{
  test: /\.(eot|svg|ttf|woff|woff2|png|jpg|gif|webp|mp4)$/i,
  type: 'asset/resource',
  generator: {
    filename: 'static/[name].[contenthash:8].[ext]'
  }
}
```

2022-09-07 06:14 UTC, intae92 commented on webpack.config.js
> +          name: 'static/[name].[contenthash:8].[ext]'
![스크린샷 2022-09-07 오후 3 05 46](https://user-images.githubusercontent.com/56149367/188800969-2d622515-0c71-4e73-81b8-9ee73ab182a6.png)

오 그러네요~~ 감사합니다.

2022-09-07 06:15 UTC, intae92 commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      <video className={styles.featureVideo} src={videoSrc} autoPlay loop muted playsInline />
조언 감사합니다!! 👍 

이번 미션에서는 mp4로도 충분히 커버가 되어서 현 상태를 유지 하겠습니다.

2022-09-07 06:36 UTC, intae92 commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" />
감사합니다~~!!

2022-09-07 06:39 UTC, intae92 commented
안녕하세요. 세지!
조언해주신 내용 잘 읽었습니다. 역시 아는게 많은 세지쿤~~!! 감사합니다.

2022-09-07 08:18 UTC, merged

2022-09-07 08:19 UTC, usageness reviewed
변경 내용 확인했습니다! 고생 많으셨어요 콜라~~!