[성능 베이스캠프 미션] 도리(박선호) 미션 제출합니다.
woowacourse/perf-basecamp pull request #38
Opened 2022-09-04 15:31 UTC by prefer2

## 🔥 결과

/_ 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. _/

- 배포한 CloudFront 접근 경로: https://dfsortnhws3gr.cloudfront.net/
- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
![스크린샷 2022-09-01 오전 11 23 44](https://user-images.githubusercontent.com/67692759/188318548-d13aa4f5-cbf6-4c03-8eb1-ecb1813d4771.png)

  
  - 개선 후 (CloudFront)
![스크린샷 2022-09-04 오후 11 28 21](https://user-images.githubusercontent.com/67692759/188318633-70380ae5-667d-4fc0-8b0f-ee9781a75ca6.png)

## ✅ 개선 작업 목록

/_ 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요
코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
_/

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
  - webpack에서 기본으로 terserPlugin이 적용되어 있어 난독화와 암호화가 가능합니다.
  ![스크린샷 2022-09-04 오후 11 45 26](https://user-images.githubusercontent.com/67692759/188319379-c8fad6eb-3bce-4894-8bde-1d460b5c512c.png)
  - css 파일을 분리하고 minimize해 주었습니다. 이번 미션에서는 css 파일의 비중이 크지 않아 css 파일 요청만 늘어나는 것 같기는 합니다. 언제 css 파일을 분리하는 것이 좋을지는 고민이 됩니다

- [x] 이미지 크기 줄이기
 ### 초기 시도(webpack 사용)

처음에는 webpack을 사용하여 build시 이미지 확장자가 변경되도록 하려고 했습니다. 다만 이렇게 변경하면 webp를 지원하지 않는 구형 브라우저에서는 문제가 발생할 수 있다고 생각이 되어 직접 파일을 변경하는 방식을 사용하기로 했습니다.

```tsx
{
    test: /\.(png)$/i,
    type: 'asset',
    generator: {
      filename: 'static/[name].webp[query]'
    }
}
```

### webp 이미지 사용

webp를 지원하지 않는 구형 브라우저에서도 잘 동작할 수 있도록 `<picture>`와 `<source>`태그를 사용하였습니다. 

```tsx
<picture>
	<source
    type="image/webp"
	  src={heroImageDesktop}
    srcSet={`${heroImageMobile} 375w, ${heroImageTablet} 768w, ${heroImageDesktop} 1980w`}
	/>
  <img className={styles.heroImage} src={heroImageDesktop} alt="hero image" />
</picture>
```

[https://web.dev/serve-images-webp/](https://web.dev/serve-images-webp/)

### gif 사용하지 않기

gif 이미지를 mp4 형식으로 변환했습니다.

[https://web.dev/replace-gifs-with-videos/](https://web.dev/replace-gifs-with-videos/)

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
code spliting을 통해 번들을 나누어주었습니다. Home 페이지까지 lazy를 걸어줄 필요는 없다고 생각해 Search 페이지에만 이를 적용했습니다.

- [x] 아이콘 패키지 Tree Shaking
tree shaking을 적용함. 사용하는 파일에 관해서 side-effect: false 설정. babel의 module을 false로 해주었습니다
![스크린샷 2022-09-04 오후 10 35 01](https://user-images.githubusercontent.com/67692759/188318817-704dd215-20b7-4feb-af05-310bc8bba6d8.png)

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
![스크린샷 2022-09-04 오후 11 34 44](https://user-images.githubusercontent.com/67692759/188318918-08ddc126-67e4-4426-826d-191f3f6f3dc2.png)
![스크린샷 2022-09-04 오후 11 39 53](https://user-images.githubusercontent.com/67692759/188319139-f52af133-39d6-4c7d-bba4-4d6b7f8cb73d.png)
자주 변경될 것 같은 js 파일들은 하루로, 변경되지 않을 것 같은 이미지 파일들은 1년으로 설정했습니다

- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
<img width="1437" alt="스크린샷 2022-09-03 오후 4 25 01" src="https://user-images.githubusercontent.com/67692759/188319682-ff4fe2f7-a452-4f1e-80e4-e4821f23fbd7.png">
cache 함수를 만들어서 값을 저장. cache 시간을 지정할 수 있도록 했습니다. search keyword에 대해서도 caching을 해주고 싶었으나 확인해본 결과 api 자체에서 caching을 해주고 있는 것 같아 trending에서만 사용중입니다. 캐싱 시간은 임의로 5분으로 설정했습니다.

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - React의 Memo를 사용하여 추가 로드 시 추가되는 결과에 대해서만 업데이트 해주었습니다. 
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
### CustomCuser
- 변화를 두 번(top, left)로 따로 주기에서 한 번만 변화주기로 변경
- top, left → transform
- translate3d가 translate보다 성능상 이점이 있다고하여 translate3d 적용
<img width="1437" alt="스크린샷 2022-09-03 오후 2 43 31" src="https://user-images.githubusercontent.com/67692759/188319787-5a4062d5-e18f-4d13-bd9b-01e30e93a8c4.png">
<img width="1437" alt="스크린샷 2022-09-03 오후 4 25 01" src="https://user-images.githubusercontent.com/67692759/188319789-0b301fe3-7866-4f92-ba42-e925216ac377.png">

### 검색결과 hover
- css transform으로 변경
<img width="1437" alt="스크린샷 2022-09-03 오후 4 12 42" src="https://user-images.githubusercontent.com/67692759/188320381-57364f02-6e64-41cd-8b2d-e79a65197f67.png">
<img width="1437" alt="스크린샷 2022-09-03 오후 2 44 32" src="https://user-images.githubusercontent.com/67692759/188320387-ae387d74-5d04-43d8-aecf-d8b4b6568c64.png">

### 도움말 패널 애니메이션
- right → transform 으로 변경
<img width="1437" alt="스크린샷 2022-09-03 오후 4 13 31" src="https://user-images.githubusercontent.com/67692759/188319948-e2412d44-701d-49c2-b195-d926915cb029.png">
<img width="1437" alt="스크린샷 2022-09-03 오후 2 45 15" src="https://user-images.githubusercontent.com/67692759/188319952-0337feab-d588-41c4-a129-788bdcd00ae5.png">

- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-06 16:05 UTC, euijinkk requested changes
안녕하세요 도리~ 
전체적으로 방향성이 비슷하네요! ㅎㅎ
좋은 질문 주셔서 저도 많이 생각해보게 되었습니다!
몇가지 코멘트 남깁니다.

## 캐시 버스팅
js 파일에 대해 캐시 버스팅을 통해 브라우저 캐싱을 막은 부분 좋았습니다! 그러면 캐싱 정책에서 js 파일 Cache-Control을 이미지 파일과 같이 1년으로 늘려도 괜찮겠네요? 이 작업 하셨는지 궁금하네요.

+ 현재 브라우저 네트워크 검사창에서 응답헤더에 Cache-Control이 나오지 않는데 제대로 동작하고 있는 것이 맞을까요? 

> Q. 다만 이미지 파일 같은 값들도 hash값을 붙여서 번들하는 것이 과연 좋을지 고민입니다.

A. 저는 상황에 따라... 필요하다고 생각합니다. hash 값을 붙여서 캐시 버스팅을 하는 이유는 브라우저 캐싱을 피하기 위해서 입니다. 그렇다면 문제 상황은 같은 파일 이름이 브라우저 캐싱되어서 최신 내용으로 업데이트 해주더라도 최신 파일을 바라보지 못 한다는 것입니다.
이미지 파일에서 그런 문제가 발생하는 경우는, 이미지 자체가 변경될 때겠네요. 로고가 바뀐다거나,,, 아이콘이 바뀐다거나 하는.
특히나 신규개발 서비스라면 더욱 잦게 발생하겠네요!! 그렇다면 캐시 버스팅을 해주는 것이 좋은 선택이지 않을까 생각이 듭니다!
도리 좋은 질문 감사합니다. 저도 hash를 붙이러 가야겠네요!

## 리액트 최적화
키보드 이벤트가 발생할 때 생각보다 많은 컴포넌트가 렌더링 되고 있어요.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/24906022/188681040-b3137eac-b68e-4401-91db-85ceb0294676.png">
시지프의 웹사이트 - 메모 처리를 해준 경우, 키보드 이벤트에 따른 성능 측정

<img width="802" alt="image" src="https://user-images.githubusercontent.com/24906022/188681084-f77f7d98-6122-4969-bdb3-9d883065395d.png">
도리의 웹사이트 - 메모 처리를 해준 경우, 키보드 이벤트에 따른 성능 측정

60밀리초 차이가 나네요. 현재 버벅거림을 느낄 수는 없지만 최적화 대상이 될 수 있다고 봅니다.
어디까지 memo를 걸어줄 것이냐는 고민이 되네요!
HelpPanel에서 500개 렌더링하고 있는 Item인 ArtistInfo만 memo처리해주면 될지,
HelpPanel 자체의 렌더링을 막을지는 저도 고민인 부분입니다!

## gif vs mp4
> gif를 mp4로 변경하는건 애매하다고 느꼈습니다. 만약에 사용자가 이 gif를 저장하고자 한다면 갑자기 동영상이 저장되어 혼란스럽지 않을까 싶었어요. mp4로의 변경을 추천하기도 하고 해서 우선은 바꿔보았는데요 gif에 대한 리뷰어님에 의견이 궁금합니다

실제로 저렇게 동영상으로 저장 버튼이 뜨네요 ㅋㅋ...
<img width="339" alt="image" src="https://user-images.githubusercontent.com/24906022/188681991-d1804aa0-bde9-4262-9d6e-d0abe74f87ad.png">

진부한 답변이지만! ㅋㅋ 상황에 따라 다를 것 같아요!
보통은 mp4나 webm을 쓰면 좋을 것 같고, 도리가 말한 특수한 상황(이미지 gif 저장이 중요한 경우)에는 gif를 그대로 노출시키는 것이 좋겠네요! gif도 webp로 하면 용량이 많이 줄어드니 webp로만 바꿔주면 나쁘지 않은 선택지 인 것 같아요!

## tree shaking
이건 제가 잘 모를수도 있는데요!! sideEffect: false 속성을 주어야 tree shaking이 된다고 생각했어요. TerserPlugin이 모두 다 지원해주는 건지 궁금하네요. 저는 sideEffect 속성을 주었을 때 미세하게 나마 bundle size가 줄어서 적용을 해보았습니다!

고생하셨습니다!! 
좋은 코드 잘 봤습니다! ☺️

2022-09-07 04:51 UTC, prefer2 commented on package.json
> +    "mini-css-extract-plugin": "^2.6.1",
css 파일이 분리되어 bundle 사이즈가 줄어듭니다. style-loader를 사용하면 현재 페이지에서 불필요한 css를 불어올 수 있다는 문제가 있는데 이를 해결해 줄 수 있습니다. 
분리해본 결과... 저는 아직 큰 효율을 느끼지 못해서 관련 플러그인은 사용하지 않았습니다. 이번 미션에서는 오히려 네트워크 소통만 늘어나는 느낌이 들더라고요. 조금 더 css 파일의 영향력이 클 때 사용할 것 같아요!

2022-09-07 04:58 UTC, prefer2 commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" />
공원의 수업 전까지는 jpeg에 대해서 잘 찾아보지 않아서 png로 제공하면 되지 않을까...?라는 생각이 들었어요. 이미지 크기 조절도 해줬고 압축도 해주었으니 이왕이면 무손실로 유지하는게 좋겠다고 생각했습니다. 확실한 기준을 찾아보지 않았었는데 이번에 배워가네요. 이번 미션에서는 이미지의 실제 품질이 중요하지 않으니 JPEG을 사용하는 것이 더 좋을 것 같네요!

2022-09-07 05:52 UTC, prefer2 commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" />
수정 완료! [649578c](https://github.com/woowacourse/perf-basecamp/pull/38/commits/649578c3b17d519f5f70a3c665917a17bb11d335)

https://github.com/woowacourse/perf-basecamp/pull/38#discussion_r963852590
jpeg으로 변경했지만 파일이 아직 너무 커서 imageMinimizerPlugin을 적용했습니다. 이와 관련해서 아래 코멘트와 함께 생각을 해보게되네요🤔 빌드시간을 줄이는 것도 고민을 해야할 것 같은데 이미지 파일 자체만으로 사이즈를 조절하는데는 한계가 있고... 적절선을 잘 찾아야하는거겠죠??

2022-09-07 05:56 UTC, prefer2 commented on src/utils/cache.ts
> +const cacheStorage: { [key: string]: GifsResult } = {};
인정합니다.. ㅋㅋ 우선 생각나는 방법으로 수정해보았어요. 타입 단언밖에 생각이 안나더라고요. 더 좋은 방법이 있다면 추천해주세요!!
[df2aec1](https://github.com/woowacourse/perf-basecamp/pull/38/commits/df2aec19b093b77f2a5fa855d1deb2ae8db1f95c)

2022-09-07 05:58 UTC, prefer2 commented on webpack.config.js
> +    ]
`chrome의 개발자도구에서 렌더링->webP 이미지 형식 사용 중지`를 사용하면 확인할 수 있더라고요! 이미지 관련해서는 위에 코멘트에 한꺼번에 답해놓았습니다

2022-09-07 06:21 UTC, prefer2 commented
리뷰 감사합니다 시짚~

s3 한번 다 지우고 나서 캐시 관련 설정을 안해줬었네요. 관련 부분 수정했습니다. 

코멘트 주신 부분 반영했습니다. searchResult 부분은 생각하지 못했는데 덕분에 하나 알아가네요! React.memo에 대해서 좀 더 공부해보고 고민해볼께요 🤨

좋은 의견과 리뷰 감사합니다 😊

2022-09-07 08:19 UTC, euijinkk commented on package.json
> +    "mini-css-extract-plugin": "^2.6.1",
오오.. 좋습니다!

2022-09-07 08:22 UTC, euijinkk commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImage} alt="hero image" />
jpeg로 바꾸면 200kB정도 되나요? 그쵸... 이것도 크긴하죠..
제가 imageMinimizerPlugin 에 대해서 잘 몰라서! 좀 더 공부가 필요할 것 같긴하네요.
빌드 타임은 얼마나 더 길어지는지... 
정적인 파일 자체를 수정해서 넣을수는 없는지...

답변 감사합니다!

2022-09-07 08:33 UTC, euijinkk commented on src/utils/cache.ts
> +const cacheStorage: { [key: string]: GifsResult } = {};
내부에서 as 처리 해주지 않아도 함수의 return 값만 T로 명시하면 될 것 같아요! 
그러면 unknown 타입이 할당되지 않아서 아마 any로 바꿔주면 좋을 것 같네요!

```ts
const caching = <T>(storageKey: string, apiFunc: Function, cacheTime: number): T => {
```

좀 더 신경쓰자고 하면, apiFunc의 타입을 Function이라고 하기 보다! 아래처럼 하면 더 좋겠네요.
```ts
apiFunc: () => T
```

2022-09-07 08:33 UTC, euijinkk commented on webpack.config.js
> +    ]
그러게요 찾는데 애먹었네요 ㅋ.ㅋ

2022-09-07 08:35 UTC, euijinkk approved these changes
정성스렁 코멘트 감사합니다!!
즐거웠습니다~~

머지합니다!

2022-09-07 08:35 UTC, merged