[성능 베이스캠프 미션] 소피아(전소이) 미션 제출합니다.
woowacourse/perf-basecamp pull request #42
Opened 2022-09-05 04:17 UTC by soyi47

## 🔥 결과

/_ 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. _/

- 배포한 CloudFront 접근 경로:
- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
  - 개선 후 (CloudFront)

## ✅ 개선 작업 목록

/_ 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요
코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
_/

**1 요청 크기 줄이기**

- [ ] 소스코드 크기 줄이기
- [ ] 이미지 크기 줄이기

**2 필요한 것만 요청하기**

- [ ] 페이지별 리소스 분리
- [ ] 아이콘 패키지 Tree Shaking

**3 같은 건 매번 새로 요청하지 않기**

- [ ] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
- [ ] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**

- [ ] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
- [ ] Layout Shift 없이 애니메이션이 일어나야 한다.
- [ ] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-06 00:37 UTC, woose28 requested changes
소피아 안녕하세요👋
리뷰를 하게 된 빅터입니다!
PR를 내용을 상세히 적어주셔서 어떤 흐름으로 작업을 진행하셨는지 쉽게 파악할 수 있어서 좋았습니다👍

# 고민 사항
> 지금처럼 잦은 변동이 없는 이미지 파일에 대해서는 이런 수작업(?)도 괜찮은 방법이라고 생각하는데요..! 번들링을 통해 이를 다루는 경우들이 있는지, 그렇다면 어떤 방법이 있는지 궁금하여 고민 중입니다.

저도 이번 미션을 하면서 이미지 최적화 작업에서 가장 많은 시간을 사용했어서 고민에 대해 공감이 가네요!
제 개인적인 생각일 뿐이지만, 변동이 거의 없는 이미지 파일의 경우 수작업(?)을 통해 변환을 해도 될 거라 생각해요ㅎㅎ

그리고 번들링을 통해 이미지를 최적화하고 webp 이미지를 생성하는 방법은… 공식 문서에 예시로 있는데, 저는 따라서 해도 이미지가 생성이 안됐습니다..!
일단 문서를 공유하면 다음과 같아요!

- [Optimize and generate webp images](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#optimize-and-generate-webp-images)
- [Generate webp images from copied assets](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#generate-webp-images-from-copied-assets)

<br>

# 필수 요구 사항
- 히어로 이미지 크기 < 120kb
  - 히어로 이미지의 크기가 157kb이네요! 요구사항은 120kb 미만으로 구현하는 것이니 조금 더 압축을 하면 좋을 거 같아요ㅎㅎ
  ![image](https://user-images.githubusercontent.com/52148907/188523803-b70fb179-2eb8-43c9-9949-bfbfa475cc21.png)

<br>

# 추가적인 제안 사항
이 부분은 작업 결과물이나 코드를 보면서 들었던 생각에 대해 정리한 부분입니다. 당연히 필수 요구사항이 아니므로 꼭 반영하실 필요는 없습니다. 가볍게 확인만 해주셔도 돼요!

## 정적 파일 이름에 Hash 사용
현재 설정해 주신 TTL처럼 캐시를 저장하는 기간이 짧다면 상관없겠지만, 만약 TTL을 길게 설정해야 할 때는 정적 파일 이름에 Hash를 사용한다고 합니다!

이와 관련해서 [Web.dev 문서](https://web.dev/i18n/ko/uses-long-cache-ttl/#http-%EC%BA%90%EC%8B%B1%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%A0%95%EC%A0%81-%EB%A6%AC%EC%86%8C%EC%8A%A4%EB%A5%BC-%EC%BA%90%EC%8B%9C%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)에는 아래와 같이 명시되어 있어요.

> 캐시 기간이 길 때의 위험 중 하나는 사용자가 정적 파일에 대한 업데이트를 보지 못한다는 것입니다. 각 버전이 고유하도록 정적 자산 파일 이름에 해시를 포함하도록 빌드 도구를 구성하고 브라우저가 서버로부터 새 버전을 가져오도록 하여 이 문제를 방지할 수 있습니다. (웹팩을 사용하여 해시를 포함하는 방법을 알아보려면 웹팩의 [캐싱](https://webpack.js.org/guides/caching/) 가이드를 참조하세요.)

알고 계셨을 수 있겠지만, 나중에 긴 TTL을 적용한 정적 파일의 이름에 해시 값을 추가하는 것도 고려하면 좋을 거 같습니다😊

## Search 페이지에서 새로고침 시  Access Denied 이슈
현재 Search 페이지에서 새로고침을 하면 Access Denined 이슈가 발생합니다.

![image](https://user-images.githubusercontent.com/52148907/188523958-1fe946d6-db7a-4f7a-88ca-ac6fd7186d81.png)
이 부분은 미션의 요구사항이 아니라 따로 처리를 하지 않으신 거라면 괜찮지만, 혹시 놓치신 부분이라면 CloudFront 설정 페이지 > 오류 페이지 > 사용자 정의 오류 응답 생성에서 해당 이슈에 대한 처리를 할 수 있으니 참고하시면 좋을 거 같아요!

## 기타
이외 의견이나 제안 사항은 코멘트로 남겨두었습니다!

<br>

미션 하시느라 고생 많으셨어요!! 히어로 이미지 크기만 요구사항에 충족되면 머지하도록 하겠습니다~!

2022-09-06 13:17 UTC, soyi47 commented on package.json
> +    "imagemin-webp": "^7.0.0",
깜빡했네요! 고마워요. 삭제했습니다!  https://github.com/woowacourse/perf-basecamp/pull/42/commits/6235a579d62a278ed0439967d8a054a320214647

2022-09-06 13:35 UTC, soyi47 commented on src/App.tsx
> +    </Suspense>
아하 요 방식이 더 좋을 것 같은데요!
대신 fallback 컴포넌트에 컨테이너 영역이 좀 더 지정되거나 해당 영역의 스켈레톤 UI 같은 게 필요할 것 같아요.

제안해준 방식은 NavBar, fallback 컴포넌트, Footer가 나타났다가 fallback 컴포넌트가 페이지 컴포넌트로 바뀌게 되는데,
지금 fallback 컴포넌트가 Loading...이라는 글자만 보여주는 상황이라, 
Footer가 위에서 잠깐 보였다가 페이지 컴포넌트가 렌더링될 땐 Footer가 아래로 밀려버려서, 
오히려 초기 로딩 동안 화면 변화가 더 많이 생기더라고요.

이번에는 지금 상황 유지하고 다음에 로딩 컴포넌트를 더 잘 구성해서 적용해볼게요.
좋은 의견 고마워요! 👍

2022-09-06 13:46 UTC, soyi47 commented on webpack.config.js
> +      new TerserPlugin(),
수정해봤어요! https://github.com/woowacourse/perf-basecamp/pull/42/commits/4c5aae400f8678b901db32793eee3157fa4f74d6

2022-09-07 02:27 UTC, soyi47 reviewed
와아 빅터~ 
고민 사항에 대한 빅터의 의견부터 추가 제안 사항까지 꼼꼼한 리뷰, 최고입니다. 👍
정말 고마워요! 짱짱! 👍

제안사항까지 다 반영하고 싶은데, 
시간 상  필수 요구사항 위주로 수정해서 다시 리뷰 요청합니다. 😥
이후에 여유되면 다른 부분들도 추가 적용해볼게요~!

#### 1. 히어로 이미지 크기 (필수 요구 사항)
이미지 해상도를 낮춰서 118kb로 줄였습니다.

![image](https://user-images.githubusercontent.com/71116429/188774000-bb224199-05f1-4736-b472-2bce111016d2.png)

#### 2. 정적 파일 이름에 Hash 사용과 캐시 TTL
이 부분들은 적용해보면 좋을 것 같은데, 아직 수정은 못 해봤어요. 여유되면 추가해보겠습니다. 제안 고마워요!

#### 3. Search 페이지에서 새로고침 시 Access Denied 이슈 
새로고침을 안 해봐서 몰랐네요. 
사용자 오류 응답 생성으로 대응하도록 했습니다. 
짚어줘서 고마워요!

2022-09-07 02:27 UTC, soyi47 commented on src/App.tsx
> +    </Suspense>
아하 요 방식이 더 좋을 것 같은데요!
대신 fallback 컴포넌트에 컨테이너 영역이 좀 더 지정되거나 해당 영역의 스켈레톤 UI 같은 게 필요할 것 같아요.

제안해준 방식은 NavBar, fallback 컴포넌트, Footer가 나타났다가 fallback 컴포넌트가 페이지 컴포넌트로 바뀌게 되는데,
지금 fallback 컴포넌트가 Loading...이라는 글자만 보여주는 상황이라, 
Footer가 위에서 잠깐 보였다가 페이지 컴포넌트가 렌더링될 땐 Footer가 아래로 밀려버려서, 
오히려 초기 로딩 동안 화면 변화가 더 많이 생기더라고요.

이번에는 지금 상황 유지하고 다음에 로딩 컴포넌트를 더 잘 구성해서 적용해볼게요.
좋은 의견 고마워요! 👍

2022-09-07 02:27 UTC, soyi47 commented on package.json
> +    "imagemin-webp": "^7.0.0",
깜빡했네요! 고마워요. 삭제했습니다!  https://github.com/woowacourse/perf-basecamp/pull/42/commits/6235a579d62a278ed0439967d8a054a320214647

2022-09-07 02:27 UTC, soyi47 commented on webpack.config.js
> +      new TerserPlugin(),
수정해봤어요! https://github.com/woowacourse/perf-basecamp/pull/42/commits/4c5aae400f8678b901db32793eee3157fa4f74d6

2022-09-07 05:04 UTC, woose28 approved these changes
수정 사항 모두 확인했습니다! 미션 하시느라 고생 많으셨어요👍
이만 merge 하도록 할게요~!

2022-09-07 05:08 UTC, merged