[성능 베이스캠프 미션] 샐리(이자선) 미션 제출합니다.
woowacourse/perf-basecamp pull request #43
Opened 2022-09-05 04:28 UTC by liswktjs

## 🔥 결과
- 배포한 CloudFront 접근 경로: https://d9tzd8512yq5p.cloudfront.net
- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
     
![성능개선전s3](https://user-images.githubusercontent.com/60773373/188359776-c7894313-7ad7-4cbb-92e7-b467881541ad.png)

  - 개선 후 (CloudFront)
 
![배포된성능](https://user-images.githubusercontent.com/60773373/188359816-cd145f4e-020f-4df1-95b2-ed4cc683614d.png)

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
     -  bundle.js의 크기를 줄이기 위해서 uglify와 minify를 production 모드로 빌드하여 처리하였습니다. 
     
<img width="369" alt="최소화전자바스크립트" src="https://user-images.githubusercontent.com/60773373/188360339-8cfc9891-4a01-43ea-ae6c-9504457deea5.png">
최소화 전 main.js의 크기 
<img width="370" alt="난독화후자바스크립트" src="https://user-images.githubusercontent.com/60773373/188360383-b813a421-abf1-4f63-add4-3fa849dffb46.png">
난독화와 최소화 작업 후 파일 크기 
     -  cdn의 경우 content-type: application/javascript 의 파일의 경우 compression을 지원해주기 때문에 최종적으로 배포된 페이지에 로드된 크기는 아래와 같게 되었습니다 
   
![스크린샷 2022-09-05 오후 1 26 22](https://user-images.githubusercontent.com/60773373/188360502-f2f7e929-0781-4678-b042-23bf640d3782.png)

추가로  웹팩이 빌드 될 때에 번들에 불 필요한 파일이  
- [ ] 이미지 크기 줄이기

**2 필요한 것만 요청하기**

- [ ] 페이지별 리소스 분리
- [ ] 아이콘 패키지 Tree Shaking

**3 같은 건 매번 새로 요청하지 않기**

- [ ] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
- [ ] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**

- [ ] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
- [ ] Layout Shift 없이 애니메이션이 일어나야 한다.
- [ ] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-06 08:33 UTC, kwannee approved these changes
안녕하세요 샐리 코드 잘 봤습니다! 배우는 점도 많았고 재밌는 시간이었어요 하하
궁금한 점이랑 생각해보면 좋을 것 같은 부분 코멘트 달았습니다. 수고 많으셨어요!

2022-09-06 08:33 UTC, kwannee commented on src/App.tsx
> +const Search = React.lazy(() => import('./pages/Search/Search'));
현재 저희는 search로 접근하면 에러가 나긴 하지만 search로 접근하는 경우가 있을 수도 있지 않을까요?!
그럼 Home도 스플리팅을 해줘야 할 것 같습니다!

2022-09-06 08:33 UTC, kwannee commented on package.json
> +    "imagemin-mozjpeg": "^10.0.0",
이거는 안쓰고 있군요. 보내주도록 합시다!

2022-09-06 08:33 UTC, kwannee commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +        alt="웹사이트의 특징이 보여지는 이미지입니다"
alt까지 넣어주셨군요 멋져요

2022-09-06 08:33 UTC, kwannee commented on webpack.config.js
> +        }
오우 에셋 모듈로 바꾸셨군요. 멋집니다

2022-09-06 08:33 UTC, kwannee commented on webpack.config.js
> +        loader: false
이거는 왜 false로 하셨나요?
 [링크](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#advanced-setup) 한번 찾아봤는데 이해가 잘 안되네요...

2022-09-06 08:33 UTC, kwannee commented on src/pages/Search/hooks/useGifSearch.tsx
> +    setGifList(JSON.parse(trendCache));
api call 관련해서는 gifAPIService에서 전부 담당하고 있는 거 같아서 위 로직을 그쪽으로 옮기는 건 어떤가 하는 생각이 드는데 샐리는 어떻게 생각하시나요?!
내부 구현이 바뀌어도 사용하는 쪽 코드는 변하지 않는게 좋을 것 같아요!

2022-09-06 09:21 UTC, kwannee requested changes
안녕하세요 샐리 코드 잘 봤습니다! 배우는 점도 많았고 재밌는 시간이었어요 하하
궁금한 점이랑 생각해보면 좋을 것 같은 부분 코멘트 달았습니다. 수고 많으셨어요!

1. 번들링 파일에 해쉬 값을 주면 파일명이 변경되기 때문에 새로운 파일로 인식해 캐시된 값을 보내주지 않을 것 같습니다. 그러면 캐시 기간을 길게 가져가도 될 것 같아요!
2. 파일을 번들링 하는 과정에서 확장자가 변경 되더라도 기존 파일을 유지하는 방법에 대해 고민이라고 하셨는데요... 그냥 파일 로더를 두번 쓰면 되지 않을까요?!
```
{
        test: /\.(png|jpg|gif)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'static/[name].[contenthash].[ext]'
            }
          }
        ]
      },
      {
        test: /\.(png|jpg|gif)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'static/[name].[contenthash].webp'
            }
          }
        ]
      }
```
이렇게 하면 파일 2개 다 나오긴 하네요! 다른 방법에 대해서는 잘 모르겠네요 검색을 계속 해봤는데 잘 안나오네요 허허...

2022-09-06 09:25 UTC, kwannee commented
> 안녕하세요 샐리 코드 잘 봤습니다! 배우는 점도 많았고 재밌는 시간이었어요 하하 궁금한 점이랑 생각해보면 좋을 것 같은 부분 코멘트 달았습니다. 수고 많으셨어요!
> 
> 1. 번들링 파일에 해쉬 값을 주면 파일명이 변경되기 때문에 새로운 파일로 인식해 캐시된 값을 보내주지 않을 것 같습니다. 그러면 캐시 기간을 길게 가져가도 될 것 같아요!
> 2. 파일을 번들링 하는 과정에서 확장자가 변경 되더라도 기존 파일을 유지하는 방법에 대해 고민이라고 하셨는데요... 그냥 파일 로더를 두번 쓰면 되지 않을까요?!
> 
> ```
> {
>         test: /\.(png|jpg|gif)$/i,
>         use: [
>           {
>             loader: 'file-loader',
>             options: {
>               name: 'static/[name].[contenthash].[ext]'
>             }
>           }
>         ]
>       },
>       {
>         test: /\.(png|jpg|gif)$/i,
>         use: [
>           {
>             loader: 'file-loader',
>             options: {
>               name: 'static/[name].[contenthash].webp'
>             }
>           }
>         ]
>       }
> ```
> 
> 이렇게 하면 파일 2개 다 나오긴 하네요! 다른 방법에 대해서는 잘 모르겠네요 검색을 계속 해봤는데 잘 안나오네요 허허...

2022-09-07 00:17 UTC, liswktjs commented on src/pages/Search/Search.tsx
> +export default react.memo(Search);
그렇네요! Search에서의 memo 제거하겠습니다

2022-09-07 00:19 UTC, liswktjs commented on src/App.tsx
> +const Search = React.lazy(() => import('./pages/Search/Search'));
오...! 그런 관점을 생각해보지 못했네요😮 그렇게 되면 모든 페이지가 스플리팅 방향이 맞겠네요👍

2022-09-07 00:24 UTC, liswktjs commented on package.json
> +    "imagemin-mozjpeg": "^10.0.0",
```
new ImageMinimizerPlugin({
        minimizer: {
          implementation: ImageMinimizerPlugin.imageminGenerate,
          options: {
            plugins: [
              'gifsicle',
              'pngquant',
              ['webp', { quality: 60, resize: { width: 1600, height: 0 } }]
            ]
          }
        },
```

현재, 웹팩의 이부분에서 image-minimizer등은 사용하고 있습니당 그런데 mozjpeg는 안 쓰고 있긴 하네요😅  바로 지우겠습니다:)

2022-09-07 00:29 UTC, liswktjs commented on webpack.config.js
> +        loader: false
이 부분의 경우, 하나의 png파일로 webp 버전의 파일과 png 버전의 파일을 2개를 만들어 내기 위해서 옵션을 켜봤었는데요 
 loader를 끄면 webp 가 안 나오지 않을까 하고 테스트겸 넣었던 건데 지우는 걸 깜빡했네요 바로 지우겠습니다 😅

2022-09-07 00:43 UTC, liswktjs commented on src/pages/Search/hooks/useGifSearch.tsx
> +    setGifList(JSON.parse(trendCache));
```
const setTrendingCache = async () => {
    const gifs: GifImageModel[] = await gifAPIService.getTrending();
    setGifList(gifs);
    sessionStorage.setItem('trendingAPICache', JSON.stringify(gifs));
  };

  const fetch = async () => {
    if (status === SEARCH_STATUS.BEFORE_SEARCH) {
      await setTrendingCache();
    }
  };

  useEffect(() => {
    const trendCache = sessionStorage.getItem('trendingAPICache');
    if (!trendCache) {
      fetch();
      return () => setStatus(SEARCH_STATUS.LOADING);
    }
    setGifList(JSON.parse(trendCache));
  }, []);
```

이런 식으로 로직을 분리해보았습니다 😁

2022-09-08 03:56 UTC, merged