[성능 베이스캠프 미션] 민초(홍영민) 미션 제출합니다.
woowacourse/perf-basecamp pull request #61
Opened 2022-09-05 08:50 UTC by jswith

## 🔥 결과

/_ 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. _/

- 배포한 CloudFront 접근 경로: https://d31krdrcr0hkmm.cloudfront.net/

- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
  
    - WebPageTest
  
      ![image](https://user-images.githubusercontent.com/64275588/188067771-449ccee7-425d-4e5e-8675-b3679575c1ed.png)
  
    - LightHouse
  
      ![image](https://user-images.githubusercontent.com/64275588/188069050-a250720d-08f5-4cad-aebf-b231e12d7708.png)
  
  - 개선 후 (CloudFront)
  
    ![스크린샷 2022-09-05 17 46 04](https://user-images.githubusercontent.com/64275588/188408242-386d59ae-f416-42fb-82a4-053f6772c72f.png)
  
    ![스크린샷 2022-09-05 17 46 39](https://user-images.githubusercontent.com/64275588/188408256-29d1a5c9-6d61-4801-a089-1f97759272cf.png)

## ✅ 개선 작업 목록

/_ 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요
코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
_/

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
- HTML 파일 최적화: HtmlWebpackPlugin의 minify 속성을 true로 지정.

- CSS 파일 최적화: CssMinimizerPlugin 적용.

- JS 파일 최적화: TerserPlugin 적용.

- CloudFront gzip 설정
  ![image](https://user-images.githubusercontent.com/64275588/188317983-5f34ecc5-4b1d-4043-9902-82a8eeac5d6d.png)
- [x] 이미지 크기 줄이기
  - hero image를 webp 포맷으로 교체
  - gif images를 mp4 포맷으로 교체

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
  - Home, Search 컴포넌트 React.Lazy 적용
- [x] 아이콘 패키지 Tree Shaking
  - @react-icons/all-files로 필요한 아이콘만 import
  - 참고 : https://github.com/react-icons/react-icons/issues/574

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
  - 메타데이터 max-age 설정 이미지 리소스는 1년, 기타 리소스는 1일
  - 이미지는 변화할 가능성이 적다고 판단하여 1년으로 설정하였고, 기타 리소스는 주기적으로 변화하는 리소스라 판단하여 1일을 주기로 설정.
- [ ] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
  - CacheStorage를 사용하여 trendingGifs에 대한 캐싱을 시도하고 있는데 Response body is already used 오류가 발생하고 있어 해결 예정입니다

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - GiftItem에 React.memo 적용
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
  - gifItem:hover -> transform
  - CustomCursor style -> transform
- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

- CSS, JS 리소스들에 해시값을 적용하고 있어서 해시값이 변동되면 새로 파일을 받아오므로, max-age 값을 좀 더 길게 가져가도 되지 않을까 생각이 드는데 리뷰어분의 생각은 어떤지 궁금하네요.

2022-09-05 13:12 UTC, DomMorello commented on src/apis/gifAPIService.ts
> +      }
저도 안 써봐서 잘 모르고 하는 소리지만 clone.. 이라는 메서드를 써야된다고 어디서 본 기억이 나요..ㅎㅎㅎ

(https://somedaycode.github.io/develop/2021/03/12/cacheStorage/)

같은 상황인지는 저도 모르겠습니다ㅜㅜ

2022-09-05 16:14 UTC, compy-ryu requested changes
안녕하세요, 민초!
리뷰를 맡게된 콤피🦖 입니다.

남겨주신 내용에 대해 리뷰와 약간의 코멘트 달아보았습니다!
한번 확인해주시고, 반영 부탁드릴께요!

---
> 웹팩 자체에서 변환해주는 플러그인이 존재하긴 하지만, 개발할 시점부터 어떤 이미지를 넣어줄지 알 수 있으므로, 굳이 다른 형식의 파일로 업로드 한 뒤 webp or mp4로 재차 변환하는 것은 비효율적이라 판단하여 애초에 webp or mp4로 변환한 후 업로드 해주었습니다.

일단 매번 최적화되지 않은 파일을 추가 해놓고 webp와 같이 변환하고 리사이즈하는 것이 비효율적인 것 같은 찝찝한 느낌은 저도 공감합니다!

하지만, 상황에 따라 다르게 생각해보아도 괜찮을 것 같습니다!

예를 들어, 개발자와 디자이너 등등 여러명이 협업하는 상황에서는
개별적으로 이미지를 압축하고 리사이즈 하는 것보다는 한번 더 웹팩 플러그인을 통해 압축을 강제하는 것이 좋을 수도 있다 생각도 들어요.

실제 프로젝트에서는 분명 로컬, 개발, 프로덕션 환경으로 나눌꺼고, 여기서 CI/CD 환경이 구성되어있다면
개발 환경에서는 이미지 변환 옵션을 꺼두면 되니, 느려지는 문제는 일단 해결할 수 있다봅니다.

그리고 프로덕션 배포 전에 실수로 압축을 하지 않고, 배포를 해버리는 상황을 미연에 방지할 수도 있고
개발자, 디자이너 간에 압축 옵션 혹은 기기 별 사이즈를 틀리게 하였을 때도 어느정도 통일성 있게 유지할 수 있지 않을까요?

또, 이미 개발자 혹은 디자이너가 이미지를 알맞게 최적화를 해두었다면
빌드 시에 이미 압축되어 있어 속도가 매우 느려지는 상황도 없을 것 같아보입니다!

추가로 추후 모바일이나 테블릿 환경 제공 시에 이미지 사이즈와 확장자 변환이 필요한 케이스는
웹팩 플러그인을 활용하면 import 할 때 옵션을 주어서 상황에 맞게 편하게 변환할 수도 있더라구요.

정답은 저도 모르겠지만 ㅎㅎ
그때 그때 상황에 맞추어 써볼 수도 있을 것 같아보입니다 ㅋㅋ 🤔

---
## 요구사항 관련
* Layout Shift 없이 애니메이션이 일어나야 한다.
* Partially Presented Frame 역시 최소로 발생해야 한다.

👀👀👀👀👀👀

![레이아웃 변경 2](https://user-images.githubusercontent.com/94832610/188486547-708f5b9b-3746-4eac-8468-db601ac9e649.png)

![레이아웃 변경](https://user-images.githubusercontent.com/94832610/188486563-afdadca0-9367-4b38-a4fa-b71d22fcc658.gif)

---
* 검색 페이지에서 새로고침 시 오류 출력

![검색 페이지 새로고침 시 오류 발생](https://user-images.githubusercontent.com/94832610/188486776-3760c370-922a-44c4-ad15-3d3996f5a9b4.png)

---

* webp 브라우저 호환성

이건 공원이 남겨주신 리뷰인데 webp 이미지 파일이 구형 브라우저에서 출력이 안되더라구요!

![webp 브라우저 호환성](https://user-images.githubusercontent.com/94832610/188486880-26946a7c-3f48-413f-8a35-92ece072c985.png)

지원 범위를 확인해보니 당장 iOS 14부터 작동되지 않아서 꽤 크리티컬한 문제인 것 같습니다.
요 부분도 리뷰 반영하시면서 개선해보시는건 어떨까유?

---

* 트랜딩 API 캐싱은 리뷰 반영과 함께 고쳐주시면 될 것 같습니다!

2022-09-05 16:20 UTC, usageness commented on src/apis/gifAPIService.ts
> +      }
`clone()` 으로 해결할 수 있습니다!! 저도 그렇게 해결했어요.
response 객체 자체가 한 번 풀면 더 이상 사용할 수 없더라구요. 😉

2022-09-06 03:59 UTC, jswith commented on src/apis/gifAPIService.ts
> +      }
감사합니다 참고할게용!

2022-09-06 05:48 UTC, compy-ryu commented on src/App.tsx
> +        <Footer />
아!! 페이지 이동 시에 레이아웃 변경 막으려고 이렇게 하신거였군요.
페이지 이동 때는 생각지도 못했네유... 배워가요!!!

2022-09-07 07:33 UTC, jswith commented on webpack.config.js
> +    ]
라이센스 파일 내용까지 번들링 되는건 몰랐네요! 배워갑니당 
txt 파일이 생성되도록 다시 롤백했습니다. [81035b9](https://github.com/woowacourse/perf-basecamp/pull/61/commits/81035b9d8b21e6c90bb1fd18575b9fcc651bf5b7)

2022-09-07 07:36 UTC, jswith commented on package.json
> +    "terser-webpack-plugin": "^5.3.6",
별 다른 이유는 없고 HTML, CSS, JS 순으로 하나하나 적용해나가다보니 별도로 설치했었습니다. 
공식문서를 읽어보니 그렇네요! [webpack docs](https://webpack.kr/configuration/optimization/#optimizationminimize)

설치했던 플러그인을 삭제했습니다! 
[81035b9](https://github.com/woowacourse/perf-basecamp/pull/61/commits/81035b9d8b21e6c90bb1fd18575b9fcc651bf5b7)

2022-09-07 07:37 UTC, jswith commented on webpack.config.js
> +    filename: '[name].[contenthash].js',
👍🏻

2022-09-07 07:37 UTC, jswith commented on src/pages/Search/components/SearchBar/SearchBar.tsx
> +import { AiOutlineSearch } from '@react-icons/all-files/ai/AiOutlineSearch';
👍🏻

2022-09-07 07:37 UTC, jswith commented on src/pages/Search/components/GifItem/GifItem.tsx
> +export default memo(GifItem);
👍🏻

2022-09-07 07:37 UTC, jswith commented on src/pages/Search/components/GifItem/GifItem.module.css
> +  transform: translateY(-0.75rem);
👍🏻

2022-09-07 07:37 UTC, jswith commented on src/pages/Home/components/CustomCursor/CustomCursor.tsx
> +      cursorRef.current.style.transform = `translate(${mousePosition.pageX}px, ${mousePosition.pageY}px)`;
👍🏻

2022-09-07 07:37 UTC, jswith commented on src/App.tsx
> +        <Footer />
👍🏻

2022-09-07 09:55 UTC, merged

2022-09-07 09:55 UTC, compy-ryu commented
굳, 고생하셨습니다!!