[성능 베이스캠프 미션] 아놀드(한수빈) 미션 제출합니다.
woowacourse/perf-basecamp pull request #65
Opened 2022-09-05 09:04 UTC by sanaandmomo

## 🔥 결과
<img width="516" alt="스크린샷 2022-09-05 오후 6 04 29" src="https://user-images.githubusercontent.com/38878617/188411962-09b9f5ee-db2e-4683-ae08-0f431f29cc89.png">

/_ 개선 목표에 있는 측정 항목들에 대해 개선 작업 전/후의 성능 측정 결과를 적어주세요. _/

- 배포한 CloudFront 접근 경로:
- 개선 전후 성능 측정 결과
  - 개선 전 (S3)
  - 개선 후 (CloudFront)

## ✅ 개선 작업 목록

/_ 각 요구사항을 위해 어떤 개선 작업을 진행했는지 적어주세요
코드 변경사항으로 확인하기 어려운 CloudFront 설정 사항 등은 리뷰어가 확인할 수 있게 스크린샷이나 적용한 항목들을 적어주면 좋겠지요? 🙂
_/

**1 요청 크기 줄이기**

- [ ] 소스코드 크기 줄이기
- [ ] 이미지 크기 줄이기

**2 필요한 것만 요청하기**

- [ ] 페이지별 리소스 분리
- [ ] 아이콘 패키지 Tree Shaking

**3 같은 건 매번 새로 요청하지 않기**

- [ ] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
- [ ] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**

- [ ] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
- [ ] Layout Shift 없이 애니메이션이 일어나야 한다.
- [ ] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-06 13:49 UTC, uk960214 requested changes
안녕하세요 아놀드! 미션 진행하느라고 고생 많으셨습니다.

코드 차원에서는 저와 유사하게 구현한 부분이 많아서 크게 어려움 없이 리뷰 할 수 있었습니다.
그래서 수정할 내용은 거의 없고 궁금한 부분들에 대해서 몇 가지 코멘트만 남겼습니다.

더불어서 설정해주신 캐시 정책과 그 이유에 대해서와 같이 최적화를 위해서 하신 선택들에 대한 이유를 더 상세하게 알려주시면 더 건설적인 피드백을 할 수 있을 것 같아요! 아놀드의 생각이 궁금합니다!

마지막으로 배포된 실제 페이지에서 레이아웃 시프트가 발생하는 것을 발견했는데 확인 부탁드립니다!

> 검색 결과 위에 hover 했을 시

![image](https://user-images.githubusercontent.com/43166681/188650375-65dc1c3c-4b7c-416f-a493-72706aeb6c8c.png)

> 도움말 패널을 열었을 시

![image](https://user-images.githubusercontent.com/43166681/188650159-1626fa6e-2435-4ca0-b30a-e23b027f4ee1.png)

코드를 봐서는 레이아웃 시프트가 해소되었어야 할 것 같은데 업로드 된 빌드 파일이 최종본이 아닌지 이미지에서 보시듯이 레이아웃 시프트가 발생하네요!

2022-09-06 13:49 UTC, uk960214 commented on webpack.config.js
> +    minimize: true,
`minimize: true`는 웹팩의 기본 설정 값으로 알고 있는데 직접 설정을 해주신 이유가 있나요?

2022-09-06 13:49 UTC, uk960214 commented on src/pages/Search/hooks/useGifSearch.tsx
> +const CACHE: Record<string, any> = {};
코드 상으로는 `CACHE`는 항상 `data`만 담고 있는 객체일 것 같은데 타입을 조금 더 자세하게 설정할 수 있지 않을까요?

2022-09-06 13:49 UTC, uk960214 commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImageJpg} alt="hero image" />
기본으로 제공하는 png 형식을 아예 지우고 기본 이미지의 확장자를 jpg로 설정하신 이유가 있나요?

2022-09-07 05:01 UTC, sanaandmomo commented on src/App.tsx
> +      </Suspense>
![](https://user-images.githubusercontent.com/19251499/188699509-e5864cce-8aa9-432b-a3a2-92e36d98dfb9.gif)
Routes 컴포넌트만 감싸면  위처럼 layout shift 현상이 발생하기 때문입니다.

2022-09-07 05:02 UTC, sanaandmomo commented on webpack.config.js
> +    minimize: true,
최적화 미션인 만큼 명시적으로 표시하고 싶었습니다!

2022-09-07 05:03 UTC, sanaandmomo commented on src/pages/Search/hooks/useGifSearch.tsx
> +const CACHE: Record<string, any> = {};
추후에 어떤 데이터를 담을지 몰라서 일단 타입을 any로 설정했습니다!

2022-09-07 05:08 UTC, sanaandmomo commented on src/App.tsx
> +const Search = lazy(() => import('./pages/Search/Search'));
생각해보니까 search는 첫 랜더링시 api 요청이 없어서 안해도 되겠네요!

2022-09-07 05:09 UTC, sanaandmomo commented on src/pages/Home/Home.tsx
> +          <img className={styles.heroImage} src={heroImageJpg} alt="hero image" />
파일 크기가 jpg가 더 작기 때문에 로드면에서 더 유리할 거라 판단했습니다!

2022-09-07 07:23 UTC, uk960214 commented on src/App.tsx
> +      </Suspense>
해당 컴포넌트를 Suspense로 감싸는 것이 Layout Shift를 방지하는 최선의 선택인가요? 사용자가 Header와 Footer를 보고 페이지가 로딩 중인 것을 인식하는 것도 중요하지 않을까요?
[이 글](https://web.dev/cls/#cls%EB%A5%BC-%EA%B0%9C%EC%84%A0%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)을 참고해서 의견 주시면 감사하겠습니다!

2022-09-07 07:32 UTC, uk960214 commented on src/pages/Search/hooks/useGifSearch.tsx
> +const CACHE: Record<string, any> = {};
`data`의 경우는 서버의 응답에 따라서 달라지기 때문에 `any`나 `unknown`을 설정하는 것이 맞지만 
CACHE 객체는 항상 `{ data: ... }`의 형태일 것 같은데 CACHE의 타입을 좀 더 자세하게 설정할 수 있을 것이라고 생각했습니다! 어떻게 보시나요?
예를 들자면 타입을 `{ data: any }`와 같은 방식으로 말이죠!

2022-09-07 07:33 UTC, uk960214 commented on src/App.tsx
> +const Search = lazy(() => import('./pages/Search/Search'));
Search 같은 경우는 Home 루트에서 불러오지 않기를 바라서 코드 분할을 하기 위해서 설정한 것이지 않나요? 
Search를 lazy하게 불러오지 않아도 code splitting이 되나요?

2022-09-07 08:07 UTC, sanaandmomo commented on src/App.tsx
> +const Search = lazy(() => import('./pages/Search/Search'));
아 아닙니다. 둘 다 레이지하게 import 해야 코드 스플리팅이 됩니다. 결국 둘 다 하는 게 맞네용!

2022-09-07 08:36 UTC, sanaandmomo commented on src/App.tsx
> +      </Suspense>
로드되는 건 suspense의 fallback으로 보여줄 수 있어서 그랬습니다. 
body 부분의 height를 지정해도 상관 없습니다.

2022-09-07 08:41 UTC, sanaandmomo commented on src/pages/Search/hooks/useGifSearch.tsx
> +const CACHE: Record<string, any> = {};
맞는 말씀이네요! 추후를 고려하는 건 야그니 원칙에 위배되겠죠

2022-09-07 08:46 UTC, merged