Naveowo
woowacourse/perf-basecamp pull request #87
Opened 2023-09-06 11:15 UTC by NaveOWO

## 🔥 결과

- 배포한 CloudFront 접근 경로:
- 개선 전후 성능 측정 결과
  - 개선 전 (GitHub Pages)
  - 개선 후 (CloudFront)

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [ ] 소스코드 크기 줄이기
- [ ] 이미지 크기 줄이기

**2 필요한 것만 요청하기**

- [ ] 페이지별 리소스 분리
- [ ] 아이콘 패키지 Tree Shaking

**3 같은 건 매번 새로 요청하지 않기**

- [ ] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
- [ ] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**

- [ ] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
- [ ] Layout Shift 없이 애니메이션이 일어나야 한다.
- [ ] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유

2023-09-07 07:14 UTC, HyeryongChoi requested changes
안녕하세요 네이브😄
성능 최적화를 꼼꼼하게 잘 해주셔서 크게 수정할 내용은 없어보여요~~
소소한 코멘트 몇개 달아보았는데 궁금한 점 있으시면 코멘트 남겨주세요! 

고생 많으셨습니다'◡'

2023-09-07 07:14 UTC, HyeryongChoi commented on src/pages/Home/components/FeatureItem/FeatureItem.tsx
> +      <video className={styles.featureImage} src={imageSrc} autoPlay muted loop playsInline />
gif처럼 동작하도록 설정해주었군요👍👍👍

2023-09-07 07:14 UTC, HyeryongChoi commented on webpack.config.js
> +      minimizer: [new TerserPlugin(), new CssMinimizerPlugin()]
```suggestion
      minimizer: [`...`, new CssMinimizerPlugin()]
```

[웹팩5](https://webpack.kr/plugins/json-minimizer-webpack-plugin/#root)에서 Production 모드일 때 TerserPlugin으로 자동으로 최적화를 해주기 때문에 위와 같이 수정하면 좋을 것 같아요~~

2023-09-11 05:09 UTC, NaveOWO commented on index.html
> +    <link rel="preload" href="https://fonts.googleapis.com" />
`preload` 속성은 랜더링 전에 폰트를 미리 다운로드 시켜놔서 폰트의 적용시간을 단축시키는 속성이어서 적용해봤어요!! preconnect는 생각해보지 못했는데 감사해요~!!

2023-09-11 05:09 UTC, NaveOWO commented on index.html
>      />
헉 그렇네요!! 수정했습니다~!!!

2023-09-11 05:10 UTC, NaveOWO commented on src/App.tsx
> +      </Suspense>
그렇네요~!! 그부분까지 신경을 못썼어용😂 감사합니다~!!

2023-09-11 05:11 UTC, NaveOWO commented on webpack.config.js
> +      minimizer: [new TerserPlugin(), new CssMinimizerPlugin()]
앗 감사합니다~!!수정했어요!!

2023-09-11 05:15 UTC, HyeryongChoi commented on index.html
>      />
```tsx
<link
      rel="preload stylesheet"
      href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
      as="style"
    />
```
앗 요거 이렇게 수정해야하더라고요~!! 다시 정정합니다 ㅎㅎ

2023-09-11 05:22 UTC, HyeryongChoi approved these changes
네이브~~ minimizer 부분 코멘트 달아놨어요 참고만 해주세요!
크게 수정할 부분은 없어보여서 이만 approve할게요 ~
이번 미션 고생 많으셨습니다~👍👍👍

2023-09-11 05:22 UTC, HyeryongChoi commented on webpack.config.js
> +      minimizer: [[`...`], new CssMinimizerPlugin()]
````tsx
minimizer: [`...`, new CssMinimizerPlugin()]
````

네이브~~ 제가 알기론 요렇게 배열로 감싸지 않고 `'...'`만 추가하면 되는 걸로 알고 있는데 요 부분 참고만 해주세요ㅎㅎㅎ

2023-09-11 05:23 UTC, merged