[개인 미션 - 성능 오답노트] 노아(김홍동) 미션 제출합니다.
woowacourse/perf-basecamp pull request #88
Opened 2023-09-06 13:57 UTC by nlom0218

안녕하세요 루루!! 🙇🏻‍♂️
한편으론 재밌었고 한편으론 마음대로 되지 않아 은근 힘들었던 성능 미션이었어요 😭
천천히 살펴보시고 부족한 점 리뷰 부탁드립니다!

# 🔥 결과

## 배포한 CloudFront 접근 경로
[CloudFront 접근 경로](https://d23ica09ppfqao.cloudfront.net/)

## 개선 전후 성능 측정 결과

### 개선 전 (GitHub Pages)
<img width="952" alt="개선 전Lighthouse" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/9c59e1bf-d62a-4cef-b28e-ab269cdc9aa7">

### 개선 후 (CloudFront)
<img width="799" alt="개선 후Lighthouse" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/d13c5499-8694-4238-a24b-cd66f623602a">

### 개선 후 webpage test
<img width="831" alt="webpage test" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/ea1a6ebb-3c44-4117-a9a1-d70466de1465">

<img width="1444" alt="webpage test" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/3eb0518e-e452-4625-80f2-3d0497537f68">

# ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
- [x] 이미지 크기 줄이기

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
- [x] 아이콘 패키지 Tree Shaking

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

# ✅ 상세 작업 목록

## **1 요청 크기 줄이기**

### 1-1. 소스코드 크기 줄이기

1. webpack optimization의 `minimize` 값 `true`로 변경
2. `TerserPlugin` 적용 및 불필요한 `console` 제거 옵션 추가

### 1-2. 이미지 크기 줄이기

1. png 파일 `webp` 파일로 변경 후 적용 -> cwebp 명령어 사용
2. gif 파일 `webm`, `mp4` 파일로 변경 후 적용 -> ffmpeg 명령어 사용

`png` 보다 `webp` 가 더 용량이 작고
`gif` 보다 `mp4`, 그리고 이 보다 `webm` 이 더 용량이 작은 것을 확인할 수 있어요.

<img width="698" alt="스크린샷 2023-09-05 오전 11 02 14" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/0111ec85-e029-465f-8730-4f3f240dd107">

## **2 필요한 것만 요청하기**

### 2-1. 페이지별 리소스 분리

`React.lazy`을 적용했습니다.

```tsx
const Home = lazy(() => import('./pages/Home/Home'));
const Search = lazy(() => import('./pages/Search/Search'));
```

이를 적용하여 모듈을 사용하는 것에 따라 나눌 수 있었고 하나의 페이지에서 모든 모듈을 불러오지 않고 사용하고 있는 모듈만 불러오는 것을 확인할 수 있었습니다.

<img width="1322" alt="스크린샷 2023-09-05 오후 3 25 24" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/19517237-7c9d-4f46-8725-bbbff154818b">

### 2-2. 아이콘 패키지 Tree Shaking

사용하고 있는 아이콘만 불러오기 위해선 여러 방법을 찾아봤지만 좋은 해결책을 찾을 순 없었어요. 외부 라이브러리를 사용하지 않고 웹팩으로 분리를 할 수 있지 않을까 하는 생각에 가장 많이 고민을 했고 시간을 투자 했던 부분이었어요.

제가 내린 결론은 `webpack optimization의 minimize 값 true로 변경`만 해도 사용하고 있는 아이콘만 불러오는 `Tree Shaking`을 한다. 입니다. 이유는 다음과 같아요.

먼저 `minimize`을 `false`로 하고 build를 하게 되면 `react-icons`의 `Parsed size`은 약 644KB입니다. 기존과 다를바 없어요.

<img width="1319" alt="스크린샷 2023-09-06 오후 10 42 16" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/bcdca700-e302-43ee-b6f8-15a14bc82d96">

하지만 `minimzie`을 `true`만 하게 되어도 `Parsed size`은 약 2.4KB입니다. 확실히 줄어들었기 때문에 별다른 설정을 하지 않았습니다!

<img width="1325" alt="스크린샷 2023-09-06 오후 10 45 01" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/efc81480-7cba-42a4-9cb2-a2dec7c7199b">

혹시 이 부분에 대해서 제가 잘못 알고 있다면 리뷰 남겨주세요! 저도 조금 더 찾아보고 공부해오겠습니다 😁

## **3 같은 건 매번 새로 요청하지 않기**

### 3-1. CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)

2023-haru-study-cache-policy 을 적용하였습니다.

<img width="1188" alt="스크린샷 2023-09-06 오후 10 48 14" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/df894484-5b60-4354-ac0e-f11e37f1232b">

자주 변경되지 않는 정적 페이지기 때문에 TTL을 1년으로 설정했습니다!

### 3-2. GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.

```ts
const asyncMemoizer = () => {
  let memo: Record<string, unknown> = {};

  return async function (api: string) {
    if (memo[api]) return memo[api];
    else {
      const data = await fetch(api).then((res) => res.json());
      memo[api] = data;

      return data;
    }
  };
};

const asyncMemoization = asyncMemoizer();
```

`asyncMemoizer` 함수를 만들었습니다. 해당 함수의 반환 값인 함수로 `fetch` 요청을 하게 된다면 먼저 `memo`가 된 데이터 있는지 확인하고 있다면 `fetch`을 진행하지 않고 `memo`가 된 데이터를 반환할 수 있도록 했습니다 :)

## **4 최소한의 변경만 일으키기**

### 4-1. 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.

`GifItem`에 `React.memo`을 적용했습니다 😁

```tsx
export default React.memo(GifItem);
```

<img width="573" alt="스크린샷 2023-09-06 오후 4 21 59" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/2d343351-db96-4724-bf24-97ca3383596c">

### 4-2. Layout Shift 없이 애니메이션이 일어나야 한다.

1. CustomCursor

`top`, `left`로 계산하고 있었던 위치를 `transform`으로 바꾸었습니다.

```tsx
  useEffect(() => {
    if (cursorRef.current) {
      cursorRef.current.style.transform = `translate(${mousePosition.pageX}px, ${mousePosition.pageY}px)`;
    }
  }, [mousePosition]);
```

2. 검색 결과 > hover

이 부분도 `top`이 아니라 `transform`으로 바꾸었습니다.

```css
.gifItem:hover {
  transform: translateY(-0.75rem);
}
```

3. 도움말 패널 열고닫기 애니메이션

`transform` 속성으로 바꾸었고 `calc`을 사용하여 위치를 계산했습니다 :)

```css
.selectedItemContainer {
  position: fixed;
  transform-origin: center right;
  transform: translateX(calc(100vw + 320px));
  // ...
}

.selectedItemContainer.showSheet {
  transform: translateX(calc(100vw - 320px));
  opacity: 1;
}
```

### 4-3. Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

해당 목표와 같은 경우, 크롬 개발자 도구의 Performance를 활용하여 문제를 분석하고 해결하고자 했습니다. 하지만, `Frame Drop` 현상은 발견할 수 없었고 `Partially Presented Frame` 인 경우는 있긴 하지만 많이 발생하지 않았다고 판단했습니다. 어찌 보면 이전에 했던 작업으로 인해 이미 최적화가 이루어진 것인지도 모르겠습니다. 

혹시 제가 분석에서 미쳐 생각하지 못했던 것이 있거나, 잘못 생각하고 있는 것이 있다면 리뷰로 알려주세요!

1. (대상) 메인 페이지의 CustomCursor

<img width="850" alt="스크린샷 2023-09-07 오전 12 42 06" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/1cc1fb69-cf95-4628-8bac-553e4b793d5b">

2. 스크롤 애니메이션

<img width="867" alt="스크린샷 2023-09-07 오전 12 42 48" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/a48d9e94-437f-416f-8205-4b8a4acd402c">

# 🧐 공유

최적화가 완료되고 `webpage test`를 진행했습니다. 모든 것이 통과될 줄 알았는데,  첫 로드시 `Largest Contentful Paint` 부분이 2.5s가 초과되었습니다. 문제는 `hero.png(webp)` 문제였습니다. 여러 시도 끝에 다음과 같이 `index.html`에 `link` 태그를 추가하였습니다.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    // ...
    <link rel="preload" as="image" href="/static/hero.webp" />
  </head>
  // ...
</html>
```

이는 다음과 같은 차이를 불러왔습니다.

## 적용 전

번들 파일이 모두 불러와진 후, `webp`가 불러와집니다.

<img width="1047" alt="스크린샷 2023-09-07 오전 12 59 42" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/b73478fb-6490-4343-803b-15c6d4e3a94c">

<img width="1073" alt="스크린샷 2023-09-07 오전 12 53 12" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/18ebd517-1ba2-44dd-bbe3-005d1078055c">

## 적용 후

번들 파일과 함께 불러와집니다.

<img width="1087" alt="스크린샷 2023-09-07 오전 1 00 02" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/6d0aae98-fe4e-490b-8593-8bab9d8a9852">

<img width="1101" alt="스크린샷 2023-09-07 오전 12 53 25" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/4a402d1b-621c-4f57-a043-88cac86b344b">

즉, 비교적 무거운 파일을 불러오기 위해 link 태그의 rel 속성을 `preload`로 하는 것이 최적화하기에 적합하다는 것을 알게되었습니다 :)

---

혹시 궁금한 점 있거나 같이 토론이 필요한 경우 언제든지 찾아와 주세요:) 감사합니다. 🙇🏻‍♂️

2023-09-07 06:43 UTC, hafnium1923 requested changes
안녕하세요 노아!!! 루루에요!!😆

미션 너무 깔끔하게 해주셔서 코멘트가 많지 않네요..😅 
개인적인 궁금증만 몇개 달았으니 확인 부탁드립니다~

그리고 공유해주신 이미지 preload덕분에 제 webPageTest 성능도 개선할 수 있었어요ㅋㅋ 
감사해요!

추가로 제 해결책과 약간 다른 부분만 따로 말해보자면
### 2-2. 아이콘 패키지 Tree Shagking
저도 webpack optimization의 minimize 값 true로 변경한 건 동일한데요~
package.json에 아래와 같이 추가해줬어요
```
"babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react",
      {
        "modules": false
      }
    ],
    "plugins": [
      "@babel/plugin-transform-runtime"
    ]
  },
  "sideEffects": [
    "*.css"
  ]
```
에서 sideEffects를 false로 해서 tree shaking을 해보았어요!
[Tree Shaking](https://webpack.kr/guides/tree-shaking/)
 "modules": false을 한 이유는 balel이 commonJS로 변환하기도 하는데 그러면 sideEffects옵션이 작동하지 않는다고 하더라구요! 근데 저도 배운거라 확실하지는 않아서 더 공부해봐야 할 것 같아요ㅎㅎ

2023-09-07 06:43 UTC, hafnium1923 commented on src/pages/Home/Home.tsx
> +        <picture>
hero의 경우 png, webp 2가지 버전만 있는 것 같은데요, 모바일 같은 작은 화면에서는 큰 이미지를 볼 필요가 없을 것 같아서 srcSet을 이용해 화면 크기에 따라서도 이미지의 화질을 다르게 한다면 더 좋을 것 같아요

2023-09-07 06:43 UTC, hafnium1923 commented on index.html
> +    <link rel="preload" as="image" href="/static/hero.webp" />
☺️👍👍👍👍

2023-09-07 06:43 UTC, hafnium1923 commented on index.html
>        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
pont에도 preload가 있으면 좋을 것 같아요!

2023-09-07 06:43 UTC, hafnium1923 commented on src/apis/gifAPIService.ts
> +  let memo: Record<string, unknown> = {};
오 클로저인가요~!🤩

2023-09-07 06:43 UTC, hafnium1923 commented on src/pages/Search/components/GifItem/GifItem.tsx
> +import React from 'react';
memo는 바로 불러와서 사용할 수 있을 것 같아요!
```suggestion
import { memo } from 'react';
```

2023-09-08 06:05 UTC, nlom0218 commented on webpack.config.js
> +            drop_console: true
옵션중에 무엇을 추가하면 좋을지 보다가 가장 직관적으로 이해하기 쉬운 옵션을 넣어봤어요! [compressOptions](https://github.com/terser/terser#compress-options)

하지만 루루의 리뷰를 받고 나니 굳이 추가할 필요가 있을까? 라는 생각을 하네요! 제거하였고 `optimization`도 제거했습니다. `prod` 모드일 땐 자동으로 압축을 하니까요!

2023-09-08 07:37 UTC, nlom0218 commented on src/apis/gifAPIService.ts
> +  let memo: Record<string, unknown> = {};
네! 여러 레퍼런스를 참고하여 만들었습니다 :)

2023-09-08 07:38 UTC, nlom0218 commented on index.html
>        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
추가를 하니 Lighthouse에서 다음과 같은 `warinning`이 발견되어서 `pont`에는 `preload`를 제거했어요. 루루는 `warinning`없이 잘 되나요??

<img width="785" alt="스크린샷 2023-09-08 오후 4 36 46" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/183ac238-19eb-494a-a8f0-84d7103dfb72">

2023-09-08 08:03 UTC, nlom0218 commented on src/pages/Search/components/HelpPanel/HelpPanel.module.css
> +  transform-origin: center right;
`opactity`은 처음 `helpPanel`의 위치를 보기 위해서 잠깐 `1`로 바꾸었는데, 이후에 수정을 하지 못했네요 😭 수정하겠습니다!

`selectedItemContainer`와 `showSheep`에 둘다 `transform`을 사용한 이유는 단순하게 같은 css 속성을 변경하기 위해서였어요! 그리고 루루가 피드백 남겨주신 내용을 바탕으로 `.showSheet`에만 transform을 적용을 해도  Rendering과 Painting이 확 줄어든 것을 확인을 할 수 있었어요! 감사해요 :) 

### 개선 전

<img width="900" alt="스크린샷 2023-09-08 오후 4 45 44" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/1b869542-8928-4bba-80c6-c9695e3bf000">

### 개선 후

<img width="1004" alt="스크린샷 2023-09-08 오후 5 03 19" src="https://github.com/woowacourse/perf-basecamp/assets/57981252/17018724-e4e2-4909-883d-5d9853b6e657">

2023-09-08 08:54 UTC, nlom0218 commented on src/pages/Home/Home.tsx
> +        <picture>
다음과 수정했어요!

```jsx
<picture>
    <source
        src={heroImage}
        className={styles.heroImage}
        type="image/webp"
        srcSet={`${heroWebpSmall} 700w, ${heroWebpLarge} 2000w`}
     />
     <img className={styles.heroImage} src={heroImage}></img>
</picture>
```

거리에 따라 다른 이미지가 로드 되는것이 신기합니다!

2023-09-10 03:41 UTC, hafnium1923 approved these changes
노아의 성능 미션을 함께해서 영광이었습니다ㅋㅋ
제 궁금증도 해결되었고 사소한 픽스도 다 확인해서 이만 Approve 하도록 하겠습니다.

고생하셨어요!!👍👍👍👍

2023-09-10 03:41 UTC, hafnium1923 commented on index.html
>        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
```
 <link rel="stylesheet preload"
    href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
    as="style" />
```
저는 이런식으로 추가했는데 문제없이 잘 작동되었어요! 한번 확인해보시면 좋을 것 같아요😆

2023-09-10 03:41 UTC, merged