[개인 미션 - 성능 오답노트] 푸만능(황준승) 미션 제출합니다.
woowacourse/perf-basecamp pull request #90
Opened 2023-09-06 17:46 UTC by turtle601

안녕하세요 타미!! 반갑습니다~!
잘부탁드립니다 😁

🔥 결과
배포한 CloudFront 접근 경로: https://d2wdez7ghsif0g.cloudfront.net

__개선 전후 성능 측정 결과__
<img width="740" alt="스크린샷 2023-09-07 오전 2 10 38" src="https://github.com/woowacourse/perf-basecamp/assets/78203399/2b56239f-4332-4300-9364-7dae583d7015">

✅ 개선 작업 목록
1. 요청 크기 줄이기
- 소스코드 크기 줄이기 (b60924faf972f5d872a2a818452b9021e64cb3c4)
  - css minimizer plugin을 사용하여 CSS 파일의 크기를 줄이고 bundle된 js 파일의 크기를 줄였습니다. 
  
- 이미지 크기 줄이기 (259c6f55f0ac95ec90951930a4c5795eca90acce, 259c6f55f0ac95ec90951930a4c5795eca90acce)
  - 이미지 모바일 반응형에 따라 필요한 이미지 파일들을 생성 후 보여주는 식으로 구현
  - png -> webp (IE는 webp를 지원하지 않는다는 점 역시 고려, IE일 경우 png)
  - gif -> webm, mp4 (IE는 webm를 지원하지 않는다는 점 역시 고려, IE일 경우 mp4)

2. 필요한 것만 요청하기

- 페이지별 리소스 분리 (b1b08a9200fc73beb62cfd8c7ebe45ffb045d386)
  - code splitting 을 통해 한번에 불러오는 소스코드의 크기를 줄였습니다.
- 아이콘 패키지 Tree Shaking (3aa08552d7e4da309d0dc61706f1d117b1fd65d7)
  - react icons all files을 사용해 분리하였습니다. (혹시 webpack에서 하는 방법을 알고 계신가요?)

3. 같은 건 매번 새로 요청하지 않기
- CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)
Cache-Control: max-age=7776000 (3개월)
Cache-Control ~ max-age은 캐싱하려는 서버(cdn)에 원본서버에서 가져온 데이터를 몇초 동안 보관할지 설정하는 헤더라고 판단하였고, 해당 설정을 통해 원본(s3)에서 가져온 데이터를 cdn에 오랜기간 캐싱할 수 있게 하였습니다.
 
- GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다. ()

4 최소한의 변경만 일으키기
- 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다. (c6267cb548604dc52e98e3df9552c0c495eb55ea)
  - react.memo를 사용하였습니다.
- Layout Shift 없이 애니메이션이 일어나야 한다. (96e670b4fd3f3b661ad4f8e1e6bb04af41ace302)
  - 포지션을 직접변경하는 css를 transform을 이용해 변경하였습니다.

2023-09-07 07:12 UTC, xodms0309 requested changes
안녕하세요 만능~ 타미입니다~
미션을 너무 잘 해결해주셨네요 👍 제가 궁금한 것들 몇 개만 코멘트 남겨봤습니다!

> Cache busting: 이미지, 동영상 같은 파일의 경우 Cache기간이 길어도 상관없지만 js, html, css 파일은 변경사항이 잦다고 판단하였습니다. 따라서 각 파일의 hash값을 주어서 해결하려고 했습니다. (HTMLWebpackPlugin, CssMinimizerPlugin)

그리고 PR에 이렇게 남겨주셨는데 s3에서 메타데이터 종류에 따라 캐시 기간을 따로 설정할 수 있는 거 아셨나요..? 

<img width="830" alt="스크린샷 2023-09-07 오후 4 06 05" src="https://github.com/woowacourse/perf-basecamp/assets/55427367/e8ea85dd-281a-4933-8554-89a4ee8f1ddd">

저도 최근에 봐서 공유합니다 ㅋㅋ

그리고 파리로 보내는 거 저도 방금 해보니까 원래 2.x초 나오던게 5.7초가 나오더라고요..?! 사이트가 뭔가 이상한 것 같기도 하네요.. Lighthouse에서는 잘 나오는 거 확인했으니 크게 신경 안쓰셔도 될 것 같아요!

수고하셨습니다~~

2023-09-11 02:50 UTC, turtle601 commented on webpack.config.js
> +    minimize: true,
> 수정했습니다!!

2023-09-11 03:06 UTC, turtle601 commented on webpack.config.js
> +      : [new BundleAnalyzerPlugin()]
헉;; 그렇네요 ㅋㅋㅋ 

`optimization`에서도 설정을 하고 실행을 해도 잘 동작해서 인지하지 못했었습니다. 
압축을 하는 `plugin`은 아니니 `plugin`에 넣으면 좋을 것 같습니다!!

2023-09-11 03:16 UTC, turtle601 commented on webpack.config.js
> +          new TerserPlugin(),
> 이렇게 작성하면 원래 존재하는 플러그인들을 extend 할 수 있는 걸로 알아요~~

새로운 정보 알아갑니다... minimzer에는 minimzer 관련 플러그인들만 넣고 
`...`에는 이전에 설정된 최소화 플러그인들을 그대로 사용하는 식으로 설정하면 좋을 것 같네요!! 

너무 좋습니다 👍

2023-09-11 03:33 UTC, turtle601 commented on webpack.config.js
> +      },
> 헉;; 맞아요!! 제가 의도한 바에서는 Terser Plugin과 위와 같은 설정이 중복되는 것 같아요!!

하지만 develop 환경에서도 빈칸제거와 주석제거를 하고 싶다면 위와 같은 설정을 적어줘도 괜찮을 것 같네요 ㅎㅎ

2023-09-11 03:35 UTC, turtle601 commented on src/apis/gifAPIService.ts
> +const cache: { current: GifImageModel[] | null } = { current: null };
> 이렇게 쓰면 언제 캐시가 만료되고 갱신되나요?

`sessionStorage` 처럼 브라우저 창이 켜진 상태에서 계속 cache 정보를 저장하고 있다가 브라우저 창이 꺼지면 cache가 초기화되게 하려고 했습니다!!

2023-09-11 03:39 UTC, turtle601 commented on webpack.config.js
> +        exclude: /\.module\.css$/i, // 모듈 파일 제외 설정
> 만능 코드를 보면 module을 나눈 것 같은데(맞나요?) 이 부분의 이점이 궁금해요!

맞아요!!

사실 웹팩 설정 이것저것 찾아보면서 module.css 관련 설정이 따로 있길래 분기처리를 해줘야하구나!! 라고 생각하고 분기 처리를 해줬었습니다. (실제 프로젝트에서도 css(App.css)와 module.css 파일들이 있어서) 

생각해보니 `test: /\.css$/i,` 여기서 .css가 붙은 파일은 모두 번들링해주기 때문에 굳이 해줄 필요 없을 것 같아요.
(빌드된 결과도 확인해보니 똑같네요)

2023-09-11 04:00 UTC, turtle601 commented on package.json
> +    "compression-webpack-plugin": "^10.0.0",
소스코드를 줄이는 방법은 `minify & uglify` 과정과 `gzip` 두 가지 과정이 있다고 들었습니다. 

지금은 `minify & uglify` 과정을 사용하고 있지만 "compression-webpack-plugin"을 통해서 gzip으로 소스코드를 압축하는 방법도 있습니다!!

(지금은 사용하고 있지 않습니다!!)

2023-09-11 05:18 UTC, turtle601 commented on package.json
> +    "imagemin-webp": "^8.0.0",
png 파일을 webpack에서 webp파일로 변경하여 이미지 파일을 최적화하는 plugin입니다!!

제 시나리오는
1단계. 모바일 관련 이미지는 로컬에 있는 webp 이미지를 제공
2단계. 데스크탑 관련 이미지는 로컬에 있는 png 이미지를 제공 (이때, webp를 지원하는 브라우저는 png -> webp를 제공합니다!!)

2023-09-11 05:21 UTC, turtle601 commented on src/pages/Search/components/SearchBar/SearchBar.tsx
> +import { AiOutlineSearch } from '@react-icons/all-files/ai/AiOutlineSearch';
> 혹시 all-files를 쓰면 얼마나 더 최적호ㅏ 되나요?

사실 전혀 차이가 없었습니다!!
 
1. bandle-analzyer로 확인했을 때 용량도 줄지 않고
2. webpack 번들링된 파일들을 살펴봐도 tree-shaking이 잘 이뤄짐

따라서 둘 차이는 별다른 차이가 없더라구요. (다만  bandle-analzyer에서 확인했을 때 시각적으로 보이는 네모가 조금 작아져서 사용했습니다.)

2023-09-11 05:24 UTC, turtle601 commented on package.json
> +  ],
tree-shaking 관련입니다. 
위 [링크](https://velog.io/@rladpwl0512/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-%EB%AF%B8%EC%85%98-%EC%84%B1%EB%8A%A5%EC%B5%9C%EC%A0%81%ED%99%94-2-%ED%95%84%EC%9A%94%ED%95%9C-%EA%B2%83%EB%A7%8C-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B8%B0)를 참고하여 설정했습니다!!

2023-09-11 05:32 UTC, turtle601 commented
> 그리고 PR에 이렇게 남겨주셨는데 s3에서 메타데이터 종류에 따라 캐시 기간을 따로 설정할 수 있는 거 아셨나요..?
저도 공원 강의 듣고 키워드를 얻어서 학습했네요 ㅎㅎ (수정해보았습니다!!)

타미랑 코드 리뷰하면서 많은 것들을 배워갑니다~~ 너무 감사해요!! 🤩🥳😍👏

2023-09-11 06:12 UTC, xodms0309 approved these changes
수고했어요 푸만능~~ 저도 만능 코드 보면서 많이 배워갑니다!

2023-09-11 06:13 UTC, merged