[개인 미션 - 성능 오답노트] 쿠마(박영진) 미션 제출합니다.
woowacourse/perf-basecamp pull request #92
Opened 2023-09-06 19:12 UTC by yogjin

안녕하세요 해온!

리뷰 잘 부탁드려요.
피드백 부담 없이 날려주세요😊

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://dcu6vmv7eey5.cloudfront.net
- 개선 전후 성능 측정 결과
  - 개선 전 (GitHub Pages)
    <img width="187" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/755bef57-ce15-44da-b588-ceb7694130a6">

  - 개선 후 (CloudFront)
    <img width="184" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/8a476030-7218-4745-961d-91375216522f">

## ✅ 개선 작업 목록

** 개선 목표 **
- [x] Lighthouse performance **`95점`** 이상
- [ ] Home 페이지에서 불러오는 스크립트 리소스 크기 **`< 60kb`**
  60.2kb
  <img width="428" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/b74b2fc1-fd78-4b03-8b75-f061ece4c7d7">

- [x] 히어로 이미지 크기 **`< 120kb`**
  <img width="390" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/2e1be767-0d5f-4e0f-8346-d01797abc2cc">

- [x] **`프랑스 파리`**에서 **`Fast 3G`** 환경으로 접속했을 때
    - Home 첫 번째 로드시 LCP **`< 2.5s`**
    - Home 두 번째 이후 로드시 LCP **`< 1.5s`**
    <img width="273" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/fc90b37a-044e-4063-a9c4-2366087d0dc0">

### **1. 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
  - [x]  `minify`, `uglify`
    - 줄바꿈, 공백, 들여쓰기 등을 삭제하여 코드 경량화
    - webpack(≥ v4) 의 `optimization.minimize` true 로 설정하여 terser plugin 활성화
    - https://webpack.kr/configuration/optimization/#optimizationminimize
    - 적용결과 (dev webpack serve 기준 `bundle.js` 1.6MB → 448KB)      
      <img width="330" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/2416106f-86f5-432f-b35e-bafabc797bb8">
      
      <img width="336" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/e037c388-32dd-4f49-b751-d286bd62b04e">
  - cloudfront의 캐시정책에 gzip, brotli 압축 설정을 이용
    <img width="156" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/f8fc3e6d-c5a9-483b-8665-412f0544df3d">

- [x] 이미지 크기 줄이기
  - 최적화 전
    <img width="554" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/8a6c3d18-fb6d-45e2-a2e2-19e64f352576">
  - 구글이 제공하는 이미지 변환 사이트인 https://squoosh.app/ 를 이용하여 이미지 최적화
    - png → webp, gif → mp4 확장자 변경
      <img width="610" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/160ae4fa-e54d-430d-893b-9cced9512952">
- `webp` 는 `safari` 에서도 14 버전부터 지원하기 시작했다.
    - 대신 `animated webp` (움짤)은 `safari`에서 지원은 하지만 버벅이는 문제가 있다.
    - 따라서 움짤의 경우 `picture` 태그를 이용해 대체 이미지를 보여주면 좋을 것 같고, 그 외의 경우 딱히 필요없을 듯 하다.
    - 물론 반응형 대응이 필요하면 `picture` 태그를 이용하면 좋을 듯 

### **2. 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
  - `React.lazy` 를 이용해 code spliting
  - 적용 전
    - `Home` 페이지에 들어가면 검색에 필요한 `giphy` 모듈과 함께 모든 모듈이 `bundle.js`에 담겨서 다운로드됨
    <img width="430" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/4b568967-0300-4377-ad53-9b7a57aa117f">
  - 적용 후
    - `Home` 페이지에 들어가면 `giphy` 모듈이 포함된 `615.bundle.js`는 불러와지지 않음
    <img width="697" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/0dfa7cb7-bd4b-48ed-a42e-4442252177f7">

    <img width="434" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/fd4cb34a-65cb-4dd4-818b-716601878e44">
  - `Search` 페이지에 들어가야 `615.bundle.js`(giphy 라이브러리 포함) 을 불러오는 모습
    <img width="698" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/59b2d928-a792-4207-b6ee-d08a5932c60d">

- [x] 아이콘 패키지 Tree Shaking
  - webpack이 tree shaking을 해주고 있음
    ㅡ<img width="527" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/6f99ae90-b4a5-458b-ba1d-2ee4133e2c33">

### **3. 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)    

- cloudfront TTL 설정
  <img width="1150" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/762bdd7c-080c-468e-813f-566ba244da79">
- http 헤더 Cache-Control 설정
  <img width="697" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/74779804-9dad-4b09-b9c3-c0eeba3421e6">
  - 헤더의 `Cache-Control` 값을 `max-age=31536000`(1년) 으로 설정한 이유
    - 현재 `webpack`에서 [chunkhash]를 이용하여 빌드 시 번들의 네이밍이 항상 달라지고 있음
    - 또한 번들 파일을 s3에 배포 시 cloudfront 캐시 무효화를 통해 번들파일 최신화를 하고있음
    - 따라서 재배포를 하지 않는 한 번들 파일이 fresh 하다는 것이 보장되기 때문에, 캐싱기간을 길게 1년으로 설정함(브라우저, cloudfront 동일하게 1년)
  - `index.html`의 경우 파일명이 고정이기 때문에 cloudfront 에서 캐시 무효화를 해도 브라우저에서는 캐싱된 `index.html`을 사용하는 문제점이 있음(이전에 방문한 경우)    
    <img width="441" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/16492394-fb76-42b3-a007-bfb8abb77279">
    -  따라서 `index.html`의 `max-age`를 0으로 하여 브라우저가 매번 cloudfront에게 `index.html` 이 fresh한지 물어보도록 함
    - 또한 `s-maxage=31536000` 로 설정하여 cloudfront에서 `index.html` 을 1년간 캐싱하도록 설정함(설정하지 않으면 최소 TTL 마다  s3에 `index.html` 을 요청하게 되므로 자원낭비임. 또한 s3 배포 시 cloudfront 캐시무효화를 하고있기 때문에 `index.html`이 fresh 하다는 것도 자명함)
  
 - [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
  - gif 가 담긴 배열을 선언해서 배열 내부 아이템 유무에 따라 요청 여부를 결정하도록 함
  - 일종의 메모이제이션
  - 클래스로 선언해서 인스턴스를 내보냄
    <img width="470" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/6f89860f-a592-4530-8edf-34ed46e33c2c">

### **4. 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - `React.memo` 를 적용
  - React DevTools의 Profiler 기준으로 기존에 있던 아이템이 다시 렌더되지 않는지 확인
    <img width="472" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/a1e21af1-bb26-4d68-959f-3adeaba6c92b">
- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
### CustomCursor
  - 커서의 위치가 바뀔 때마다 top left를 수정하고 있음.  (top left는 layout paint commit 전부 일어나므로 성능이 좋지않다) 대신 commit만 일어나는 transform을 이용.
  - top left 를 이용한 기존 로직
    <img width="496" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/b3108399-8193-4954-b148-2230586667bd">
    <img width="503" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/6d159766-7efd-4f9f-bef6-6d79dab28593">
    - layout paint commit이 전부 일어나고, Layout shift이 일어남
  - transform을 이용
    <img width="427" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/5135e067-fb84-4ac9-aaaa-438666b99526">
    - commit만 일어나고, Layout shift이 사라짐.
### 검색 결과 > hover
- 동일하게 top을 transform으로 수정
  <img width="427" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/5135e067-fb84-4ac9-aaaa-438666b99526">

- [x] Frame Drop이 일어나지 않아야 한다.
  - Home 에서 scroll 시에 뒷 배경이 렌더링될 때 frame drop이 일어남.
    <img width="110" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/33623078/cda21815-854e-4729-9570-0f736af69583">
  - scroll 요청여부를 알려주는 state와  `requestAnimationFrame` 를 이용하여 1초에 60번까지만 애니매이션을 업데이트 하도록 하여 frame drop이 일어나지 않도록 함.

## 🧐 공유

- vscode extension 중에 `css-triggers` 추천드립니다!
css 속성에 커서올리면 해당 속성이 어떤 렌더링 과정을 거치는지 알려줘서 최적화 할 때 편했어요.

- "`react-icons`는 webpack이 tree shaking을 해주고 있음" 이라고 적었지만.. 사실 그렇게 동작하는게 맞는지 확신을 못했습니다ㅠ
parsed file size 가 기존 패키지 size 보다 훨씬 작아지길래, webpack이 해주는 거라고 추측했습니다. 혹시 이 부분 알고계신가요?

- 이미지 최적화는 webpack plugin을 사용하지 않았습니다.
처음에 plugin 사용하려다가 많은 오류를 만나고, 해결하려면 webpack을 major 버전까지 설치해야하고 또 peer dependency 문제까지 터지니 조금 어질어질 하더라구요. 
특히 이미지 최적화 하나만을 위해서 webpack major 업데이트를 한다는 게 개인적으로 좀 거슬렸어요.. ㅋㅋㅋㅋ
또 실제로 변환할 이미지가 몇 개 안되기도 하고, 실무에 가면 디자이너가 원하는 파일을 사용해야하는데 프론트단에서 임의로 압축하고 resize 하다가 의도와 다른 이미지가 적용될 수 있다고 생각해서 수작업으로 진행했습니다!

- https://www.webpagetest.org/ 테스트를 맨 처음 진행하면 `LCP` 가 `8s` 정도(...) 나오더라구요. 저 위에 사진은 사실 두번째 돌렸을 때 캡처한 눈속임 입니다🥲 
다른 크루들도 많이 이 문제를 겪고 있는 것 같은데, 알고 계신게 있을까요?

- 현재 `Home` 페이지에서 번들이 60kB 가 살짝 넘는데, 번들에 포함된 css 코드를 분리한다면 번들의 크기를 줄일 수 있을 것 같다.. 고 생각은 했습니다. 하지만 어차피 css 파일이 분리되었을 뿐이지 어차피 요청해야하니 큰 의미가 있나? 생각해서 따로 분리하지는 않았습니다. 혹시 어떻게 생각하시나요?

2023-09-07 07:29 UTC, hae-on requested changes
안녕하세요 쿠마~~ 🧸
잘 지내고 계신가용?

오늘 이상한 티셔츠를 입었다는 소문을 들었슴니다!
나중에 구경 갈게용 👀


> vscode extension 중에 css-triggers 추천드립니다!...

추천해주신 css-triggers 감사합니다 👍
저도 설치해봤는데 아주 잘 나오더라구요! 
프로젝트에 잘 적용해보겠습니다!

>"react-icons는 webpack이 tree shaking을 해주고 있음" 이라고 적었지만.. 사실 그렇게 동작하는게 맞는지 확신을 못했습니다ㅠ...

`react-icons`는 webpack이 tree shaking을 해주고 있는게 맞는 거 같아요!
optimization의 [usedExports](https://webpack.kr/configuration/optimization/#optimizationusedexports)라는 친구가 있는데 사용되지 않는 import를 번들링 하지 않는 역할을 한다고 해요.

usedExports의 기본값이 true로 설정되어 있어서 tree shaking이 적용 되고, 사용하지 않는 아이콘을 털어낸 것으로 보입니다!

제가 한번 false로 줘봤는데
<img width="406" alt="스크린샷 2023-09-07 오후 3 24 08" src="https://github.com/woowacourse/perf-basecamp/assets/80464961/c44e4f96-7891-4163-bc30-5b2befd33ff1">
요렇게 parsed size가 크게 나오는 걸 볼 수 있었어요!
(그래서 저도 이 부분에 대해서는 따로 뭔가 해주진 않았어요 🙂🙃🙂🙃)

> 이미지 최적화는 webpack plugin을 사용하지 않았습니다. ...

이미지 최적화 플러그인 사용하지 않은 이유 좋아요 👍
쿠마 말대로 여기에 이미지가 많은 것도 아닌데 플러그인은 너무 과다하다고 할까?
(저는 플러그인을 사용해보고 싶어서 썼다가 하루를 다 날렸어요 ㅠ.....)
수작업 진행 좋슴니당 😎

> https://www.webpagetest.org/ 테스트를 맨 처음 진행하면 LCP 가 8s 정도(...) 나오더라구요. ...

이 문제는 저도 잘 모르겠어요 ㅠ....
인지를 못하고 있다가 쿠마 말 듣고 제꺼 한번 돌려봤는데 저도 4초 이상으로 나오네용..
다른 크루들한테도 시켜보니까 다 크게 나오네요... 왜 이럴까요 흠 🤔

> 현재 Home 페이지에서 번들이 60kB 가 살짝 넘는데, 번들에 포함된 css 코드를 분리한다면 번들의 크기를 줄일 수 있을 것 같다.. 고 생각은 했습니다. ...

저도 css 코드를 분리하지 않았어요!
css 코드의 양이 별로 많지도 않고 했을 때의 장점을 여기서는 못 느끼겠더라구요!

https://patterns-dev-kr.github.io/performance-patterns/compressing-javascript/
여기 보면 아래 문장이 있어요.

`compress(a + b) <= compress(a) + compress(b) - 여러 개의 작은 번들보다 하나의 큰 번들의 압축률이 더 낫다. 이로 인해 중복 제거와 캐싱이 브라우저 성능 및 압축과 상충되는 세분화된 트레이드오프가 발생한다. 세분화된 청킹은 이러한 트레이드오프를 처리하는 데 도움이 될 수 있다.`

저도 이 말에 공감을 해서 분리 하지 않았습니다!

리뷰하면서 새로운 방법도 알 수 있고 재미있었습니다!
특히 Frame Drop이랑, trending API 부분이 인상 깊었어요! 
크게 수정할 부분은 따로 보이지 않네요. 수고하셨어요~~ 👏
그럼 스크립트 리소스 크기 줄이고 오시죵~~💨

2023-09-07 13:27 UTC, yogjin reviewed
해온☀️☀️☀️!!
정성스러운 답변 감사합니다🙇🏻‍♂️
덕분에 더 공부해보면서 새로 알게 된 부분(font flash, [usedExports](https://webpack.kr/configuration/optimization/#optimizationusedexports) 등) 이 많았어요!
또 제가 고민하던 부분 함께 고민하고 공유해주셔서 감사해요😊

코멘트 달아주신 부분 답변 달아두었습니다!

2023-09-07 13:27 UTC, yogjin commented on webpack.config.js
> +    splitChunks: {
아.. 이 부분
> 현재 Home 페이지에서 번들이 60kB 가 살짝 넘는데, 번들에 포함된 css 코드를 분리한다면 번들의 크기를 줄일 수 있을 것 같다.. 고 생각은 했습니다. 하지만 어차피 css 파일이 분리되었을 뿐이지 어차피 요청해야하니 큰 의미가 있나? 생각해서 따로 분리하지는 않았습니다. 혹시 어떻게 생각하시나요?

로컬에서 위 내용과 동일한 이유로 제거를 했었는데요,
제가 잊고 push를 안했네요🥲

결론은 장점을 느끼지 못해서 지웠습니다!

2023-09-08 11:46 UTC, hae-on commented on index.html
> +      as="style"
우왕 친절한 답변 감사해요~~
완벽히 이해할 수 있었습니다 짱! 🥳

2023-09-08 11:49 UTC, hae-on approved these changes
쿠마 수고하셨습니다~~!
덕분에 많이 공부하고 새로운 것도 알아가서 뜻깊은 시간이었어요!
이만 머지하도록 하겠습니다!
다음 미션도 화이튕~~🧸

2023-09-08 11:50 UTC, merged