[개인 미션 - 성능 오답노트] 첵스(최혜령) 미션 제출합니다.
woowacourse/perf-basecamp pull request #97
Opened 2023-09-07 02:14 UTC by HyeryongChoi

## 🔥 결과

- 배포한 CloudFront 접근 경로: https://dmswp65hubinu.cloudfront.net/
- 개선 전후 성능 측정 결과 (by [WebPageTest](https://www.webpagetest.org/))

  - 개선 전 (GitHub Pages)
    ![개선전 LCP](https://velog.velcdn.com/images/chex/post/2486a6fd-1676-45ae-9f55-599b11c271c5/image.png)
  
    ![개선전 Lighthouse](https://velog.velcdn.com/images/chex/post/75731974-ad13-47c0-9900-7fb3ac78dbaf/image.png)

  - 개선 후 (CloudFront)
    ![개선후 LCP](https://velog.velcdn.com/images/chex/post/375734b1-2034-445c-9979-72bdcc595092/image.png)
  
    ![개선전 Lighthouse](https://velog.velcdn.com/images/chex/post/c35e5307-00ee-4d7f-a3c2-4c68ea623755/image.png)

## ✅ 개선 작업 목록

**1 요청 크기 줄이기**

- [x] 소스코드 크기 줄이기
![](https://velog.velcdn.com/images/chex/post/aa78d11d-6439-41c9-ad0f-369772182636/image.png)
	
  - 홈 페이지에서 불러오는 스크립트 크기: `284kb` > `55.6kb`
  - 웹팩5에 내장된 `terser-webpack-plugin`으로 소스코드 크기를 줄였습니다.
  - `mini-css-extract-plugin`: 브라우저가 css, js파일을 동시에 다운로드 받을 수 있도록 js에서 스타일 코드를 css 파일로 분리했습니다.
  - `css-minimizer-webpack-plugin`: css 코드를 경량화했습니다.

- [x] 이미지 크기 줄이기
  ![](https://velog.velcdn.com/images/chex/post/0ef83109-bba6-4465-a822-0d11cf326ddf/image.png)

  - hero 이미지 크기: `10.7mb` > `115kb`
  - 이미지 포맷을 수동으로 변경하는 방법도 있었지만 이미지를 일일이 수동으로 변경하는 방법보다는 웹팩 플러그인을 이용해 이미지를 최적화하는 방법이 더 편리한 것 같아서 `image-minimizer-webpack-plugin`을 사용하여 이미지 최적화를 진행했습니다. (gif파일 최적화 및 png파일 webp 형식으로 변환)
  - hero 이미지는 가로 `4100px` > `1920px`(Full HD 해상도 기준)로 리사이징했습니다.

**2 필요한 것만 요청하기**

- [x] 페이지별 리소스 분리
  <img src="https://velog.velcdn.com/images/chex/post/9d8e7e6d-f287-433a-bb4d-6dff5700b7de/image.png" alt="" width="400px" />
  - `React.lazy`를 이용하여 Home과 Search 페이지 코드를 분리했습니다.

  ![](https://velog.velcdn.com/images/chex/post/929dc1cd-c010-43a8-980a-7851759c1e2d/image.png)

  - Home 페이지에서 불러오는 스크립트 리소스에는 Search 페이지에서 사용하는 giphy모듈이 포함되어 있지 않습니다.

- [x] 아이콘 패키지 Tree Shaking
  <img src="https://velog.velcdn.com/images/chex/post/4c26d73b-74dc-4810-b3f8-5aa6f9d318c8/image.png" alt="" width="400px" />
  - babel로 es6 모듈이 CommonJS모듈로 변환되는 것을 막아주었습니다. [참고](https://webpack.kr/guides/tree-shaking/#root)
  - 사이드 이팩트가 있는 코드를 명시해줌으로써 이를 제외하고 트리 쉐이킹을 할 수 있도록 설정했습니다.

**3 같은 건 매번 새로 요청하지 않기**

- [x] CloudFront 캐시 설정 (설정값, 해당 값을 설정한 이유 포함)

	```
		최소 TTL(초): 1 // 1초
		최대 TTL(초): 31536000 // 1년
		기본 TTL(초): 86400 // 1일
		Cache-Control: max-age=31536000 // 1년
	```

   캐시 정책의 경우 기본 값을 적용했습니다. 
   응답 헤더 `Cache-Control`은 `html`파일은 `no-cache`, 나머지 파일들은 `max-age` 1년으로 설정했습니다. 
   `html`에서 이전 버전의 `js`, `css`파일을 로드하지 않고 항상 최신 버전의 웹 서비스를 제공할 수 있도록 `no-cache` 옵션을 주었습니다.
   `no-cache` 설정의 경우 캐시를 저장하고 사용할 때마다 서버에 재검증 요청을 보낸다고 해요.
   `js`, `css`의 경우 `max-age`는 1년이지만 파일명에 해시값을 추가하여 파일 내용이 변경됐을 때 브라우저 캐시를 무효화하고 최신 리소스를 로드하도록 했습니다.
   - `js`: `chunkhash`
   - `css`, 정적인 asset파일들: `contenthash`
   		- `Home.js`와 `Home.css`는 같은 chunk이기 때문에 `chunkhash`를 적용하면 `js`를 수정했을 때 `css` 파일명도 바뀌게 되어서 `contenthash`를 적용했습니다.

    
- [x] GIPHY의 trending API를 Search 페이지에 들어올 때마다 새로 요청하지 않아야 한다.
  ![](https://velog.velcdn.com/images/chex/post/ba4e49e6-9b84-4b75-b36f-6bbd739b28b4/image.gif)
  - CacheStorage API를 이용해 trending API 요청의 결과물을 캐싱하고 10분 동안 살려주었습니다.
  - 나중에 확인해보니 데이터 업데이트 주기가 [하루](https://developers.giphy.com/docs/api/endpoint/)더라구요. 생명을 하루 연장시켜주는 것도 좋을 것 같습니다.ㅎ.,ㅎ

**4 최소한의 변경만 일으키기**

- [x] 검색 결과 > 추가 로드시 추가된 목록만 새로 렌더되어야 한다.
  - GifItem컴포넌트에 `React.memo`를 적용하였습니다.

- [x] Layout Shift 없이 애니메이션이 일어나야 한다.
  - 커스텀 커서
    ![](https://velog.velcdn.com/images/chex/post/f92c4da4-35ad-49f7-827d-5c82325701af/image.png)

  - 도움말 패널
    ![](https://velog.velcdn.com/images/chex/post/bdafbf0c-4cff-4280-8fd9-093f4503d7a5/image.png)

  - 애니메이션 처리 시 top | bottom | left | right 속성은 레이아웃 변경이 일어나 `transform` 속성을 사용하였습니다.

- [x] Frame Drop이 일어나지 않아야 한다.
  - (Chrome DevTools 기준) Partially Presented Frame 역시 최소로 발생해야 한다.

## 🧐 공유
웹팩5에서는 production 모드 빌드 시, 
반면 mode를 "production"으로 설정하면 빌드 리소스를 최적화 하기 위해 다음 7개 플러그인을 사용한다고 합니다. [참고](https://jeonghwan-kim.github.io/series/2020/01/02/frontend-dev-env-webpack-intermediate.html#41-production-%EB%AA%A8%EB%93%9C)

FlagDependencyUsagePlugin, FlagIncludedChunksPlugin, ModuleConcatenationPlugin, NoEmitOnErrorsPlugin, OccurrenceOrderPlugin, SideEffectsFlagPlugin, TerserPlugin

웹팩에서 자동으로 트리쉐이킹도 해주고 코드 압축, 난독화도 해주니 참 편하다고 생각했습니다. ^___^

[웹 서비스 캐시 똑똑하게 다루기](https://toss.tech/article/smart-web-service-cache) 
-> 요 글도 안 읽어보셨다면 읽어보세용 쉽게 설명되어있어서 좋더라구요!

이번 미션을 하면서 브라우저에도 캐시가 있다는 걸 인지하게 되었는데, 브라우저에 캐시가 저장되면 만료될 때까지는 캐시가 계속 브라우저에 남아 있게 되기 때문에 캐시 설정은 섬세하게 다뤄야하겠구나라는 걸 느꼈어요. 호호

2023-09-08 05:38 UTC, D0Dam requested changes
안녕하세요 첵스! 코드 잘 봤습니다! 너무 잘해주셔서 이러다가 리뷰를 달 게 없을 듯 해서 최대한 극한의 트집(?)을 잡아보았습니다..! 질문도 남겨보았어요! 잘 부탁드려요~!

> 웹팩5에서는 production 모드 빌드 시,
반면 mode를 "production"으로 설정하면 빌드 리소스를 최적화 하기 위해 다음 7개 플러그인을 사용한다고 합니다. [참고](https://jeonghwan-kim.github.io/series/2020/01/02/frontend-dev-env-webpack-intermediate.html#41-production-%EB%AA%A8%EB%93%9C)

오~! 정보 감사합니다~! production 환경에서 7개의 플러그인이 기본적으로 사용된다고 생각하면 될까요?
`웹팩5에서는 production 모드 빌드 시, 반면 mode를 "production"으로 설정하면` 이 문맥이 잘 이해가 안가네요..🥹

> 웹팩에서 자동으로 트리쉐이킹도 해주고 코드 압축, 난독화도 해주니 참 편하다고 생각했습니다. ^___^

맞아요! 웹팩 5를 사용한다는점이 참 다행인 것 같아요~! 반면에 저는 그런 생각도 해보았던 것 같아요. "웹팩에서 자동으로 해 주는 것을 모두 신뢰하고 맡겨도 될까?" 라고요..! 과연 이렇게 웹팩에게 맡기게 되면 어떤 문제 상황이 있을 수 있을까요??

> [웹 서비스 캐시 똑똑하게 다루기](https://toss.tech/article/smart-web-service-cache)
-> 요 글도 안 읽어보셨다면 읽어보세용 쉽게 설명되어있어서 좋더라구요!

저도 이 글 읽어 봤는데... 쉽던가요..? 전 어려웠는데..ㅠㅠㅜㅜ 좋은 글은 확실히 맞는 것 같습니다!ㅎㅎ


> 이번 미션을 하면서 브라우저에도 캐시가 있다는 걸 인지하게 되었는데, 브라우저에 캐시가 저장되면 만료될 때까지는 캐시가 계속 브라우저에 남아 있게 되기 때문에 캐시 설정은 섬세하게 다뤄야하겠구나라는 걸 느꼈어요. 호호

맞아요! 저는 이것 때문에 전 프로젝트 때 개발을 할 때 항상 개발 전에 크롬에 있는 캐시를 지워주곤 했답니다..! 웬만하면 브라우저 캐시와 같은 개인 환경에서는 캐시 검증 요청 정도는 필요한 것 같다는 생각이 들어요! 

## 이모저모
첵스의 사이트에 들어가서 performance test를 진행해 보았는데요..! cpu x6, 3g fast 환경에서 진행해본 끝에 제가 Frame Drop을 발견했답니다! 어느 부분의 영향이 컷을까요?
<img width="1107" alt="스크린샷 2023-09-08 오후 1 27 56" src="https://github.com/woowacourse/perf-basecamp/assets/51052049/2cd544f6-0b1c-4b94-ac1b-e89c6c10440f">

제가 보았을 때 2가지 정도를 생각해 볼 수 있을 것 같아요!

### gif 파일 크기

<img width="540" alt="스크린샷 2023-09-08 오후 1 29 03" src="https://github.com/woowacourse/perf-basecamp/assets/51052049/e3d79066-90e2-4a36-b066-0d5db3da0f20">

물론! 첵스가 이미지 최적화를 해 주었지만, gif를 **이미지**로 보고 있다는 점이 문제가 아닐까 싶어요!
gif는 이미지로 최적화 하는것이 한계가 있다...라는 것이 제 결론입니다!(첵스의 생각은 어떨지는 모르겠네요..🥲)
gif는 mp4로 변환한다면 기존에 쓰던 img 태그가 아닌 video 태그를 사용해서 보여줄 수 있어요!
gif를 사진이 아니라 영상의 관점에서 본다면 기존 용량보다 훨씬 작게 줄일 수 있을 것 같아요~!

### font 불러오기
과연 첵스의 사이트에서 가장 다운로드를 길게 해서 홈페이지를 저하시키는 나쁜 친구는 누구일까요??
제가 CCTV를 돌려서 그 범인을 잡아왔어요!

<img width="618" alt="스크린샷 2023-09-08 오후 1 30 33" src="https://github.com/woowacourse/perf-basecamp/assets/51052049/83113279-32c7-4e79-a157-29633a095d74">

보면 유독 한개의 초록 막대가 기다란 것을 볼 수 있어요! 이 친구가 범인 같아요! 바로 폰트 관련 css 파일입니다! 어떻게 하면 이 요청을 최적화 할 수 있을까요?

방향성은 두 가지가 있는 것 같아요!
- index.html에 google font를 불러오는 스크립트 태그에 어떤 속성들을 추가해서 로드를 먼저 빠르게 시킨다!
- 아예 빌드 시에 해당 폰트를 들고 있게 한다.

어느 방향이 더 좋은 것 같나요?  한 번 고민해 보는 것도 큰 도움이 될 것 같아요~!

큰 부분은 이 정도밖에 없는 것 같네요.. 한 번 리뷰도 확인하고 반영하고 싶은 부분만 추가적으로 반영해서 새로 request 주세요~! 수고하셨습니다!!!🙏

2023-09-08 05:38 UTC, D0Dam commented on README.md
README.md 를 작성하셨네요!! 별 것 아닐 수 있지만 이런 거 챙기는 거 너무 좋은 것 같아요!!
(저는 안했습니다.. 보고 배웁니다..)

2023-09-08 05:38 UTC, D0Dam commented on package.json
> +  ],
css 파일 말고 또 sideEffects가 일어날 만한 파일은 어떤 게 있을까요?

2023-09-08 05:38 UTC, D0Dam commented on package.json
> +    "imagemin-webp": "^8.0.0",
이 세 가지의 패키지는 크기가 얼마나 되나요? 프로젝트가 이 세가지의 패키지를 추가할 만한 가치가 있을까? 했을 때 아니라는 결론을 내렸었거든요! 첵스는 어떠한 생각으로 이 방법을 통해 이미지 최적화를 진행했는지 물어보고 싶어요~!

2023-09-08 05:38 UTC, D0Dam commented on src/App.tsx
> +const Home = lazy(() => import(/* webpackChunkName: "Home" */ './pages/Home/Home'));
이렇게  주석으로 이름을 설정하는군요!👍

2023-09-08 05:38 UTC, D0Dam commented on webpack.config.js
> +      filename: 'css/[name].[contenthash].css'
오호! 이걸로 build를 했을 때 css 폴더를 따로 둔건가요? 좋은데요?

2023-09-08 05:38 UTC, D0Dam commented on webpack.config.js
> +          enforce: true,
이건 어떤 옵션일까요?

2023-09-08 05:38 UTC, D0Dam commented on src/apis/gifAPIService.ts
> +      const cacheTime = 600000;
항상 같은 cacheTime을 설정해 주는 것이라면 외부에 두어도 좋을 것 같아요~!

2023-09-08 05:38 UTC, D0Dam commented on src/apis/gifAPIService.ts
> +      const cache = await caches.open('trending-cache');
`caches.open('trending-cache');` 여기에서 caches는 어디있는거죠..? 혹시 js 내장인가요..?🥲

2023-09-08 05:38 UTC, D0Dam commented on src/apis/gifAPIService.ts
> +      };
😆

```suggestion
      const cacheData = {
        trending,
        expirationTime: cacheTime + Date.now()
      };
```

2023-09-08 05:38 UTC, D0Dam commented on src/apis/gifAPIService.ts
> +      }
혹시 이렇게는 안될까요?

```suggestion
      if (cachedResponse) {
        const { expirationTime, trending } = await cachedResponse.json();

        if (Date.now() < expirationTime) return trending;
      }
```

2023-09-08 05:38 UTC, D0Dam commented on src/apis/gifAPIService.ts
>    getTrending: async function (): Promise<GifImageModel[]> {
오호! 이런 방법을 사용하셨군요! 좋은 것 같아요! 개인적으로 첵스가 생각하기에 아 코드에서 아쉬움이 남았던 부분은 없었나요??

2023-09-09 08:03 UTC, HyeryongChoi commented on webpack.config.js
> +          enforce: true,
<img width="662" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/24777828/cd246f28-cc69-4bf1-ac60-feb447ed67f5">

giphy모듈이 필요할 때만 불러와지는지 네트워크탭에서 확인하고 싶어서 설정한 옵션입니당
번들 파일명에 giphy를 붙여서 따로 번들링해줬어요!

2023-09-09 08:08 UTC, HyeryongChoi commented on src/apis/gifAPIService.ts
> +      const cache = await caches.open('trending-cache');
맞아요 ㅎㅎㅎ [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage)를 사용했어요~!

2023-09-09 08:26 UTC, HyeryongChoi commented on package.json
> +    "imagemin-webp": "^8.0.0",
이미지를 하나씩 수동으로 변경하는 작업이 번거롭다고 생각했습니다! 그리고 이번 미션에서 웹팩을 통해 이미지 최적화를 해보고싶어서 플러그인을 통한 최적화 방식을 사용했어요~~

2023-09-09 08:30 UTC, HyeryongChoi commented on src/apis/gifAPIService.ts
>    getTrending: async function (): Promise<GifImageModel[]> {
getTreding 함수에 캐시관리와 trending 데이터 요청이라는 2가지 관심사가 섞여있어서 아쉬움이 남았어요!
그래서 캐시 관리 로직을 분리했습니당

```tsx
const CacheManager = {
  async getCachedData<T>(cacheName: string, cacheKey: string): Promise<T | null> {
    const cache = await caches.open(cacheName);
    const response = await cache.match(cacheKey);

    if (response) {
      const { expirationTime, data } = await response.json();

      if (Date.now() < expirationTime) return data;
    }

    return null;
  },

  async cacheData<T>(cacheName: string, cacheKey: string, data: T, cacheTime: number = 86400) {
    const cache = await caches.open(cacheName);
    const expirationTime = Date.now() + cacheTime;

    const cacheData = {
      data,
      expirationTime
    };

    const cacheResponse = new Response(JSON.stringify(cacheData));

    await cache.put(cacheKey, cacheResponse);
  }
};

export default CacheManager;

```

2023-09-09 08:34 UTC, HyeryongChoi commented on package.json
> +  ],
사실 이 부분은 잘 모르겠네용..
css파일을 넣어줬던 건, 트리쉐이킹을 했을 때 css를 사이드이팩트에 추가하지 않으면 스타일이 깨졌기 때문이었어요!
도담이 생각하기에 사이드이팩트가 일어날 만한 파일은 어떤 것인가요~?

2023-09-09 09:02 UTC, HyeryongChoi commented
### [접속링크](https://dmswp65hubinu.cloudfront.net/)

도담~~ 코드리뷰 반영완료입니다!! 
넘 정성스럽게 코드리뷰를 해주셔서 감동했어요😆 
덕분에 많이 배웠고 Lighthouse 성능점수도 올라서 100점 달성했습니다~~ ㅎ,ㅎ

<img width="704" alt="image" src="https://github.com/woowacourse/perf-basecamp/assets/24777828/c48e4b8e-c6d7-464e-bfb1-5e953dbc36c9">

### 📝 코드리뷰 반영 목록
- [x] font preload 적용
- [x] getTrending 코드 리팩터링

### 그외 리팩터링 목록
- [x] meta 태그 추가
- [x] img alt 속성 추가
- [x] heading 태그 수정

### 기타
질문에 대한 답변은 코멘트로 달아놓았습니다.
그리고 웹접근성(alt, heading 태그 수정)이랑 검색엔진(meta 태그 추가) 최적화도 함께 진행해보았어요~

> 웹팩5에서는 production 모드 빌드 시,
반면 mode를 "production"으로 설정하면 빌드 리소스를 최적화 하기 위해 다음 7개 플러그인을 사용한다고 합니다.

이건 왜 이렇게 써놨을까요? 맨위 PR 코멘트에 다시 수정해놨습니다ㅎㅎㅎ

2023-09-11 05:20 UTC, D0Dam commented on src/apis/gifAPIService.ts
>    getTrending: async function (): Promise<GifImageModel[]> {
헉 멋지네요..!! 이렇게 하면 확장성도 좋은 것 같아요! 따봉

2023-09-11 05:21 UTC, D0Dam approved these changes
아니! 웹 접근성까지 챙기다니!! 대단한데요?
답변도 너무 잘 달아주신 것 같아요! 첵스의 캐시 매니저도 머싯었습니다!
이제 진짜 더이상 리뷰할 게 없네요! 빠르게 머지 하도록 하겠습니다~!

2023-09-11 05:21 UTC, merged